### ISSUE TITLE
Navbar links (e.g. to Primer) not working from Technical Guidance pages

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#103]
Go here:

http://beneficial-ownership-data-standard.readthedocs.io/en/schema-beta-2/schema/guidance/index.html

... or any subpages in the guidance section. Then click on 'Primer' or similar.

Not sure if this is a docs or theme issue and don't have time to investigate atm.

**Comment by timgdavies** [comment]
Ah - that section is two levels deep in menu which is perhaps causing problems @odscjames ? Is there a simple fix for that we can add in theme?

**Comment by odscjames** [comment]
Well the real fix for this is to use a Sphinx function pathto but that didn't work on RTD last week. Will look into this.

**Comment by odscjames** [comment]
Now pathto works fine in my test branch. I'll try it in schema-beta-2

**Comment by odscjames** [comment]
It now works fine on live RTD.

Stupid computers.
