### ISSUE TITLE
Docs: Links to JSON schema broken on Schema Browser page

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#108]
Here: http://standard.openownership.org/en/schema-beta-2/schema/schema-browser.html

**Comment by ScatteredInk** [comment]
Using James' link checker, the full list of missing links:

>   not found (404): http://localhost/schema/_static/ownership-or-control-statement.json
>     from http://localhost/schema/schema-browser.html
> 
>   not found (404): http://localhost/schema/_static/entity-statement.json
>     from http://localhost/schema/schema-browser.html
> 
>   not found (404): http://localhost/schema/_static/person-statementt.json
>     from http://localhost/schema/schema-browser.html

Note, that whatever the underlying cause of this, there is a typo in person-statement**t**.json

**Comment by kd-ods** [comment]
Fixed with commit 3433fc9
