### ISSUE TITLE
Document propertyOrder in the development handbook

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#112]
Has the propertyOrder already been rationalised along one particular line? If not, please could properties with non-object or non-object-array values be 'floated' to the top of (informal) groupings. This helps with flattened representations of the schema (e.g. in the [field-mapping tool](https://docs.google.com/spreadsheets/d/1wPwbVZhA86llJhGmf3L8b-y_GRSDLIojPUXqMhb9H_k/edit#gid=48825705)). For example, at the moment in Entity Statements, the key properties relating to the entity are in this order:

Name
AlternateNames
Jurisdiction **[object]**
Identifiers **array[object]**
uri
foundingDate
dissolutionDate
Addresses **array[object]**

This would be better:

Name
AlternateNames
foundingDate
dissolutionDate
uri
Jurisdiction **[object]**
Identifiers **array[object]**
Addresses **array[object]**

**Comment by timgdavies** [comment]
The property order was set to help with the workshop resources for Tbilisi as [json-editor](https://github.com/json-editor/json-editor) uses it. 

I don't believe it is respected by any of our other tooling, which just takes the order of the properties in the schema file as their basis (assuming they are reading using a python OrderedDict, as otherwise JSON is formally an unordered structure).

**Comment by kd-ods** [comment]
OK. So it looks like propertyOrder is something that we'll be using for UI purposes. I think that BODSkit should probably respect this property too, for instance, in the 'mapping sheet' command.

So the question is still open about what default propertyOrder values should go into the schema.

**Comment by kd-ods** [comment]
This needs to be documents in the Dev handbook.

**Comment by timgdavies** [comment]
I believe the outstanding task here is to write up how we use propertyOrder in the [bods-dev-handbook]{https://github.com/openownership/bods-dev-handbook).

@kd-ods If you think we should also re-order properties in the raw schema, to help with flattened representations / documentation display etc. it may be useful to open an additional issue for that.

**Comment by timgdavies** [comment]
See also https://github.com/openownership/data-standard/issues/171#issuecomment-598195791 where we discussed whether or not to remove propertyOrder from current version of the schema.

**Comment by rhiaro** [comment]
Closing as this is now documented in the dev handbook. (Whether or not to remove it from the schema remains open.)
