### ISSUE TITLE
Control in state-owned enterprises

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#113]
Our current ownership and control types are geared towards describing forms of private ownership. Following regulatory trends, these tend to de-emphasise management responsibility in favour of legal and informal rights to benefit from or control an entity. This may be much less useful in the case of a state-owned enterprise (SOE), where ownership may rest with a state, or a state body, and control be exercised by natural persons through senior management roles or board positions. From conversations, there is often overlap in board membership between different SOEs and between SOEs and private companies - so, for anti-corruption use cases, this may be something worth tracking.

At the moment, we have two control types that could be used for this:

`senior-managing-official` - added for describing trusts in the context of the CRS but could also work here.
`influence-or-control` - this is really intended to capture control not described by other enumerated forms of control, so not ideal.

Next steps here are to gather some more user needs on the SOE context. There is some secondary literature on SOE corruption risks that we can look at, and we will also be talking about this in the context of EITI-participating countries and in certain OO pilot countries.

**Comment by kd-ods** [comment]
We also need some way at the entity level of flagging that a company is an SOE. An SOE could be a legal or registered entity, so it may not make sense to add SOE as a category to the [entityType codelist](http://standard.openownership.org/en/v0-1/schema/reference.html#entitytype). A boolean flag may be an option.

**Comment by ScatteredInk** [comment]
EITI pilot data on OO Register showing SOEs controlled by state:

https://register.openownership.org/entities/59bfef7767e4ebf3402cedb1.json

It's useful to have a state modelled as its own thing here ("as an analyst I want to know which companies a state owns so that can I conduct comparative analysis of public ownership").

But also suggests we want some other modelling of SOEs / states so that we know what to expect at either end of the ownership relationship.

**Comment by stevenday** [comment]
I agree that we want to keep the states as an identifiable owner of some kind. 

One extreme option would be just a `describedByCountryCode` in the `ownershipOrControlStatement`? The set of state entities corresponding to the current ISO codes could just be assumed to exist by publishers, essentially making them defined by the standard itself. You could then add one of those `ownershipAndControlStatements` alongside some `describedByPersonStatements` for the people who're exercising control on behalf of the state, with some appropriate new control types to account for it.

Another thought this sparked: is there some kind of grey area around things like the UK’s ‘trading funds’ that would fall under ‘State Owned Enterprise’ but need a different entity categorisation from 'normal' registered companies?

**Comment by stevenday** [comment]
Another example from the register: https://register.openownership.org/entities/5e569474ac0ca34dfc6841b6 this was submitted by the company themselves, but our submissions form doesn't allow SOE's, so they couldn't really describe the ultimate owner. Note also that they've added an 'other' interest to mention it.

**Comment by kd-ods** [comment]
In [BODS 0.3](https://standard.openownership.org/en/0.3.0/schema/reference.html#interesttype) we now have the following interest types which may be used to clarify control in state-owned enterprises:

- appointmentOfBoard
- seniorManagingOfficial
- boardMember
- boardChair
- enjoymentAndUseOfAssets

@Blueskies00 - As someone who's recently been researching SOEs, do you think there are any obvious control mechanisms that link individuals with SOEs and which should be covered in BODS? (If nothing comes to mind at the moment, imo we can close this ticket.)

**Comment by Blueskies00** [comment]
I didn't come across any that I couldn't easily map using the current codelist.
