### ISSUE TITLE
Schema: description for 'Identifier' component is inaccurate

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#114]
The Identifier component is referenced from both the entity-statement and the person-statement schemas. However the description of the object and its properties sometimes refers to 'entity' only. e.g.

        "id": {
          "title": "ID",
          "description": "The identifier for this entity as provided in the declared scheme.",
          "type": "string"
        }

Suggested fix: replace 'entity' with 'entity or person' in relevant descriptions.

**Comment by ScatteredInk** [comment]
This whole Identifier block needs work. In particular, the schema description is out of sync with the documentation. I've updated that but this would benefit from a sense check:

 > "For entity statements, the scheme should be a entry from the [org-id.guide](http://www.org-id.guide) codelist. For person statements, the scheme should have the pattern {JURISDICTION}-{TYPE} where JURISDICTION is an ISO 3-digit country code and TYPE is one of PASSPORT, TAXID or IDCARD."

I'm not sure if that is too much info for a description string or if we actually want to point people out to the docs and, for beta-3, think of something a bit more sustainable, given that the codelist will just get bigger over time.

**Comment by kd-ods** [comment]
I don't think it's too much for a description string if those 'should's are as per RFC2119. In the long term, as you say, we can move to something more sustainable and backward-compatible.

**Comment by ScatteredInk** [comment]
Fixed in https://github.com/openownership/data-standard/commit/a72a22ca1cc1c850494d2167a71bb0683b577f90.

Long-term issues covered in #131.
