### ISSUE TITLE
Schema: description for source of person-statement is incorrect

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#115]
It looks like the description for the 'source' of a [person-statement](https://github.com/openownership/data-standard/blob/schema-beta-2/schema/person-statement.json) has been copied from the ownership-or-control-statement schema:

    "source": {
      "title": "Source",
      "description": "The source of the information that links the entity and the interested party, or that supports a null statement.",
      "$ref": "components.json#/definitions/Source"
    }

Suggested fix: change description to "The source of information about this person."

**Comment by ScatteredInk** [comment]
My suggestion is that we change this to:

>  "The source of information about this person, or that supports an unknown or anonymous person statement."

This keeps the link to missing data. We can then also change the entity statement source description to:

> "The source of information about this entity or that supports an anonymous or unknown entity statement"
