### ISSUE TITLE
PEP status

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#118]
#94 added a simple model of PEP (politically-exposed person) status.

EITI recommendation [2.5](https://eiti.org/document/standard#r2-5) has this on BO disclosure:

>  Information about the identity of the beneficial owner should include the name of the beneficial owner, the nationality, and the country of residence, as well as **identifying any politically exposed persons**. It is also recommended that the national identity number, date of birth, residential or service address, and means of contact are disclosed.

This means that PEP-status can be a binary flag and meet the EITI standard. We could model this with a simple binary field.

**Comment by ScatteredInk** [comment]
We probably also want a Source object, for provenance info. This should distinguish between cases where:

- PEP information is collected _with_ a beneficial ownership declaration;
- PEP information is drawn from an _external_ source (e.g., a national or global PEP database).

The current Source object lets us do that. The exception might be if we want to flag to people the difference between sources that are explicitly point-in-time (due-diligence done on submission) and sources that are updated independently of a BO system (a PEP database that politicians are required to declare to on an annual basis).

Our guidance should probably point publishers towards other mechanisms for publishing and updating data on PEPs. We want to prioritise inter-operability with e.g. Popolo, a national asset declaration register or a mooted global PEPs database.

**Comment by ScatteredInk** [comment]
Merged into schema, now needs documentation.

**Comment by kd-ods** [comment]
@ScatteredInk - I've added the PEP status changes to the changelog (in my local repo at least - look out for branch '0.2-dev-changelog-182' at some point). I think there's sufficient guidance in the property descriptions themselves to ensure publishers use (or don't use) the new hasPepStatus field appropriately.

> Our guidance should probably point publishers towards other mechanisms for publishing and updating data on PEPs. We want to prioritise inter-operability with e.g. Popolo, a national asset declaration register or a mooted global PEPs database.

I agree, but I don't think we have time to add a good quality PEP page to the guidance for the 0.2 release.

So, if you agree that it's enough to include the PEP field changes in the changelog this time around, this issue can be closed.

**Comment by ScatteredInk** [comment]
Closing, will add PEPs to the documentation to-do list.
