### ISSUE TITLE
Update readme to cover tests and translation

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#119]
README should cover:

- Docs build process
- Tests
- OC as steering group member

**Comment by kd-ods** [comment]
^ I suggest that any elements in the 'Translation' section of the ReadMe that aren't in the [Dev Handbook](https://github.com/openownership/bods-dev-handbook/blob/master/translations.md) already are move there. Then in the ReadMe, under the 'Translation' heading, we just link off to the handbook. @siwhitehouse - does that make sense?

I think there should be a section in the ReadMe about the automated testing in the repo. (I know we're set to review this, but still worth a bit of documentation for now.) FWIW, we could say this:

**Testing in the repository**
Travis and pytest are used to run example and test BODS JSON files against the BODS schema. Files subject to testing are listed in tests/test_data.py. All changes to the repo are submitted for testing and cannot be merged without the tests passing.

To run the tests locally on an instance of the repo:

- On the command line, set up a python virtual environment, eg. on Ubuntu 16.04:
`virtualenv -p python3 .ve'
- Activate it, eg. on Ubuntu 16.04:
`source .ve/bin/activate`
- Install general requirements:
`pip install -r requirements.txt`
- Install testing requirements
`pip install -r requirements_test.txt`
- cd into the /tests directory and run
`pytest`

pytest will pick up and run the test_data.py script and output the results.

**Comment by kathryn-ods** [comment]
I think the dev handbook now covers the first 2 bullets. We've recently updated the governance page on the docs - not sure what 'OC' stands for

**Comment by kd-ods** [comment]
Steering group members are no longer listed in the ReadMe. 

This ticket can be closed.
