### ISSUE TITLE
Modelling issue: codelist languages

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#13]
> An issues related to the [draft conceptual model](https://github.com/openownership/data-standard/issues/7)

The schema will include a number of codelists. 

Codelist codes can either be:

* **Based on English language.** For example, [‘shares’,’contract’] as valid codelist values, with a codelist which provides further labels and descriptions.
Or

* **Alphanumeric, with a lookup list**. For example [1,2] as valid codelist entries, and a codelist that provides further labels and descriptions. 

English language codelist entries can make data more intuitive to some (english speaking…) readers. However, codes without an embedded language or semantics in the code name are more internationally applicable. 

A decision on this trade-off will be needed.

**Comment by jpmckinney** [comment]
If some potential adopters would find it unacceptable to use English, then I suppose we need to retreat to numbers. Are there any other motivations for numbers?

**Comment by timgdavies** [comment]
We have kept with english language terms for now.
