### ISSUE TITLE
Docs: schema browser widget (Docson) rendering of required fields should be improved

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#144]
**Problem:**

At the moment required fields in the schema are **bolded** in the [schema browser](http://standard.openownership.org/en/v0-1/schema/schema-browser.html). It is not apparent to the user that this is the case. (See [this internal issue](http://bods.opendataservices.coop/redmine/issues/432).)

In the short term we can just add a note to the docs page flagging up that the bolded fields are required. However this is bad practice from an accessibility POV. 

**Possible solution:**

I'm not sure how customised our version of Docson (https://github.com/lbovet/docson) is. If it's no bother making custom changes, then I'd suggest retaining the boldness and appending an asterisk to required fields. We could then add a final para to the header div for the widget <div class="box-title" ref="<root>">:
`<p>* Required field</p>`

**Comment by kd-ods** [comment]
Ben, Amy, James - This is a UI request/bug and it would be good to get it fixed before long. I had a chat to Amy about it already.

Between you, could you take a look at what a fix would require and get this issue on the non-sprint board (if that would get it seen to quicker)?

Thanks!

**Comment by rhiaro** [comment]
BODS currently uses the latest commit of [this non-master branch of our fork of docson](https://github.com/OpenDataServices/docson/tree/our_version_1). Ideally we should figure out why this didn't make it into master yet, fix it if possible, and then fix the UI issue, and make sure this doesn't damage any other docs that use our docson.

**Comment by odscjames** [comment]
I'm guessing as a code change this isn't to hard, but as Amy says it's good to make sure we're releasing code properly. I would like to discuss this with the other developers, and I will start that discussion.

However, if it's important, we could break this into two parts; we could do it in a hacky way with little effort now; but it would then be more important to make sure this is fixed at some point in the future.

**Comment by odscjames** [comment]
![Screen Shot 2019-06-27 at 14 01 57](https://user-images.githubusercontent.com/37832009/60268372-28717380-98e4-11e9-8d46-5d19bcc2e92e.png)

How does this look? One problem at the moment, the "* Required field" string won't be translated. Can that be looked at later or does it have to be now?

**Comment by kd-ods** [comment]
> the "* Required field" string won't be translated. Can that be looked at later or does it have to be now?

Hmmm - I don't think it's the end of the world if this isn't translated immediately. It's not strictly within the scope of the 0.2 release. Is the string part of the theme repo? Will it be pulled out for translation 'next time around'?

**Comment by odscjames** [comment]
Thought I replied to this yesterday but can't see it so excuse if duplicate -  

> Will it be pulled out for translation 'next time around'?

No, it's actually in the JavaScript widget. It won't be translated without further work. Is that an issue, should we still put this in?

**Comment by kd-ods** [comment]
I don't think we should let i18n block roll-out of this usability fix. So, if it's a considerable amount of work to get this string (or whole widget!) into the translation workflow, let's kick that can down the road (starting a new issue for it, to be dealt with later).

**Comment by odscjames** [comment]
This pull request https://github.com/openownership/data-standard/pull/227/files will put this into the current docs.

**Comment by kd-ods** [comment]
@odscjames - Since PR 227 has been merged into Master, I thought I would be able to see this issue fixed at http://standard.openownership.org/en/master/schema/schema-browser.html#entity-statement, but no joy. What am I missing?

**Comment by Bjwebb** [comment]
@kd-ods Is this fixed now?

**Comment by kd-ods** [comment]
Yes, fixed. Closing.
