### ISSUE TITLE
Contradictory definitions of motivation

### ISSUE THREAD

**Issue by Bjwebb** [openownership/data-standard#148]
Definitions of `motivation`:

Inside `properties` (defined as an open codelist):
https://github.com/openownership/data-standard/blob/4f57061751e3c28319430edc7dfdaf7a38d732bf/schema/components.json#L361-L374

Inside `anyOf` (defined as an enum, therefore closed codelist):
https://github.com/openownership/data-standard/blob/4f57061751e3c28319430edc7dfdaf7a38d732bf/schema/components.json#L392-L424

Looks like the python jsonschema library uses the latter of these.

Also, the anyOf as currently written seems to be unecessary - one of the subschemas is a subset of the other.

**Comment by kd-ods** [comment]
I just want to check what our validation requirement is here. It looks to me like we want to:

Require that:

- An annotation must have a motivation
- if the motivation is "commenting", "correcting", "identifying", "linking",  or "transformation" then there has to be a "statementPointerTarget".
- if the motivation is not one of those values then we don't require a "statementPointerTarget"

Is that right, @ScatteredInk? If that's correct then I think this is the fix that we need to make:

   "oneOf": [ 
     { 
       "properties": { 
         "motivation": { 
           "enum": [ 
             "linking", 
             "identifying", 
             "commenting", 
             "correcting", 
             "transformation" 
           ] 
         } 
       }, 
       "required": [ 
         "statementPointerTarget", 
         "motivation" 
       ] 
     },
     { 
       "properties": { 
         "motivation": { 
          "not": {  
            "enum": [ 
              "linking", 
              "identifying", 
              "commenting", 
              "correcting", 
              "transformation" 
            ] 
          } 
         }
       }, 
       "required": [ 
         "motivation" 
       ] 
     } 
   ]

**Comment by ScatteredInk** [comment]
So I think the intention here was simply to require a url if the motivation was linking and not in all other cases. I don't think an open codelist is needed. I've had a go at fixing this and added a test but could do with another pair of eyes on this.

**Comment by ScatteredInk** [comment]
Fixed in #197
