### ISSUE TITLE
Docs: update technical guidance on identifiers to include schemeName

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#159]
schemeName isn't mentioned here: http://standard.openownership.org/en/v0-1/schema/guidance/identifiers.html

**Comment by kd-ods** [comment]
I'm going to edit that identifiers page in the docs, but I also want to update the descriptions for 'scheme' and 'schemeName' in the [schema](https://github.com/openownership/data-standard/blob/0.2-dev/schema/components.json#L100).

@ScatteredInk, I want to add this sentence to the end of both descriptions:

"scheme or schemeName (or both) MUST be included in an identifier object."

If that's OK I'll got ahead and make these edits. What do you think?

**Comment by ScatteredInk** [comment]
@kd-ods  - yes, agreed.
