### ISSUE TITLE
Be more explicit in schema docs about the format of statementDate

### ISSUE THREAD

**Issue by stevenday** [openownership/data-standard#163]
The example data looks like we're intending this to be ISO8601 like YYYY-MM-DD, but given that we have other dates which allow approximations (see #162) it feels like these should be more explicit.

**Comment by timgdavies** [comment]
Linked to #12 this might require some documentation about handling fuzzy dates (from both data producer and user) perspective *if* this appears to be a relevant issue to address right now.

**Comment by kd-ods** [comment]
#387 Looks at issues like this across the schema.

**Comment by kd-ods** [comment]
Closing in favour of #162 and related work.
