### ISSUE TITLE
Review guidance in including exact share % in minimum/maximum also

### ISSUE THREAD

**Issue by stevenday** [openownership/data-standard#164]
The docs say: 

> Where an exact percentage is available, this should be given, and maximum and minimum values set to the same as the exact percentage.

However [the example data ](https://github.com/openownership/data-standard/blob/da1f653e7f6ecd2af659fb63f2f082852be7597d/examples/1-single-direct.json#L64-L66) does not do this.

**Comment by kd-ods** [comment]
Should we also force publishers to adopt this approach by:

- Amending the description to say 'Where an exact percentage is available, this should be given, and maximum and minimum values **must be** set to the same as the exact percentage.
- Adding a related CoVE check.

**Comment by ScatteredInk** [comment]
The original example has been fixed but there is at least one more of these in 0.2 release: [joint ownership](https://github.com/openownership/data-standard/blob/29f3575c480570f97c9a14402ca85583c5789fea/examples/3-joint-ownership.json).

**Comment by timgdavies** [comment]
Updated issue title to suggest that we should review this guidance as part of 0.3. 

The original guidance was designed to put the onus onto publishers to make data more re-usable (by allowing users to just look at min/max percentage section if dealing with data from multiple publishers, some of whom have absolute, and some of whom have ranges of ownership %age).

However, I think we are learning in implementation that intermediary tools may be needed that can prepare data from different publishers for use, and so this requirement could be removed from publishers, and placed as guidance for users / the consideration built into intermediary tooling.

**Comment by kathryn-ods** [comment]
This guidance has now been removed

> "The proportion of this type of interest held by the interested party, where an interest is countable. Provide the `exact` percentage if known. Otherwise, `minimum` (or `exclusiveMinimum`) and `maximum` (or `exclusiveMaximum`) can be used to record the range into which the proportion falls. (The `minimum` and `maximum` values are inclusive.)"
