### ISSUE TITLE
Give more guidance about exclusiveMin and exclusiveMax in Shares

### ISSUE THREAD

**Issue by stevenday** [openownership/data-standard#165]
It took me quite a while to figure out that these are useful in the situation where a publisher has captured share ranges in a way that differ from our defaults. As far as I can see, that's the only case where they're needed, but then they're essential to making sure we can make sense of the range given. It might be worth more guidance *somewhere* about this, to make it clear it's an advanced option for specific situations?

**Comment by ScatteredInk** [comment]
Thanks @stevenday - we'll add some docs to clarify publication patterns here.

**Comment by kd-ods** [comment]
For reference, this is the relevant part of the schema in 0.1:

        "share": {
          "title": "Percentage share",
          "description": "Where an exact percentage is available, this should be given, and maximum and minimum values set to the same as the exact percentage. Otherwise, maximum and minimum can be used to record the range into which the share of this kind of interest falls.",
          "type": "object",
          "properties": {
            "exact": {
              "title": "Exact share",
              "description": "The exact share of this interest held (where available).",
              "type": "number",
              "maximum": 100,
              "minimum": 0
            },
            "maximum": {
              "title": "Maximum share",
              "description": "The upper bound of the share of this interest known to be held.",
              "type": "number",
              "maximum": 100,
              "minimum": 0
            },
            "minimum": {
              "title": "Minimum share",
              "description": "The lower bound of the share of this interest known to be held.",
              "type": "number",
              "maximum": 100,
              "minimum": 0
            },
            "exclusiveMinimum": {
              "title": "Exclusive minimum",
              "description": "If exclusiveMinimum is true, then the share is at least greater than the minimum value given. E.g. if minimum is 25, the share is at least 25.1, and not simply 25.",
              "type": "boolean",
              "default": false
            },
            "exclusiveMaximum": {
              "title": "Exclusive maximum",
              "description": "If exclusiveMaximum is true, then the share is at least less than the maximum value given. E.g. if maximum is 50, the share is less than 49.999, and not simply 50.",
              "type": "boolean",
              "default": true
            }
          }
        }

Because of the presence of defaults for 'exclusiveMinimum' and 'exclusiveMaximum', I think we need to edit the share description and add the following:

          "title": "Percentage share",
          "description": "Where an exact percentage is available, this should be given, and maximum and minimum values set to the same as the exact percentage. Otherwise, maximum and minimum can be used to record the range into which the share of this kind of interest falls. **By default the minimum is inclusive and the maximum exclusive (minimum-value ≤ share < maximum-value ). If you wish to change these defaults, use the exclusiveMinimum and exclusiveMaximum properties.**"

@ScatteredInk - can you sanity-check that for me, please.

**Comment by ScatteredInk** [comment]
Thanks @kd-ods  - I agree with this change, which makes things much more comprehensible.

**Comment by ScatteredInk** [comment]
This is fixed in the schema. We may want some more comprehensive examples in our documentation overhaul for 0.3, and it makes sense to have at least one example disclosure regime that doesn't use the defaults.
