### ISSUE TITLE
Convert remaining docs pages to RST

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#169]
Noting that:

- We agreed we'd move to RST from markdown to address to address a problem with ALT image text (#87)
- @odscjames did that using pandoc for the most part (PR #100)
- I assume we want to RST for all docs pages not just those with images.

In the 0.2-dev branch as of the 10th May 2019, these are the remaining .md files in the docs:

docs/usecases.md
docs/about/index.md
docs/primer/index.md
docs/about/credits.md
docs/toolbox/index.md
docs/privacy-notice.md
docs/userguides/index.md
docs/userguides/licensing.md
docs/userguides/updating-data.md
docs/userguides/bulk-data-and-api.md
docs/userguides/links-other-standards.md
docs/userguides/using-ben-ownership-data.md
docs/userguides/validating-and-verifying.md
docs/userguides/publishing-ben-ownership-data.md

There are other md files in the repo, but they're not docs files as such. I assume we can leave them as markdown?

- README.md
- CONTRIBUTING.md
- schema/tools/README.md

Unless the conversion to RST is blocking work elsewhere (@rhiaro - translation workflow?), I think we leave the full conversion until the 0.3 release. (Maybe converting individual files to rst for this 0.2 release if we happen to be working on them anyway).

Assigning to @rhiaro to check how this relates to translation workflow.

**Comment by rhiaro** [comment]
I'm sorry for the late realisation. We need to add extra code into the translation workflow in order to translate markdown files. If they're going to eventually be RST anyway, it makes sense to do that conversion now, rather than do the work to translate markdown now. I realise this is terrible timing.

**Comment by rhiaro** [comment]
Work started on this on https://github.com/openownership/data-standard/find/0.2-dev-mdtorst branch.

Files with substantial contents including lists and links are:

docs/usecases.md
docs/about/index.md
docs/about/privacy-notice.md
docs/userguides/validating-and-verifying.md

Probably easiest to run these through a converter like https://cloudconvert.com/md-to-rst and then verify output by eye.

Files with very short contents or only a title and `eval rst` block are:

docs/primer/index.md
docs/toolbox/index.md
docs/userguides/index.md
docs/userguides/licensing.md
docs/userguides/updating-data.md
docs/userguides/bulk-data-and-api.md
docs/userguides/links-other-standards.md
docs/userguides/using-ben-ownership-data.md
docs/userguides/publishing-ben-ownership-data.md

Probably least hassle to do these by hand; headers need to be changed from `#` to `====` syntax and the `eval_rst` wrapper syntax just needs to be removed (with the rst block left intact).

If links to `.md` files are spotted, can change these to `.rst`, but it won't break if any are missed.

Once the changes are made, extract strings with `make gettext`, and push to transifex. (No need to update tx/config.) The ones with *only* headings and rst blocks, or contents with zero inline markup (links or lists) should *not* need any additional work on transifex (but do check they have been autofilled).

**Comment by siwhitehouse** [comment]
Amy, we haven't been able to complete the editing of the rst files. Kadie is still working locally on the mdtorst branch to make sure that all of the links are non-broken.

If you get the chance, can you briefly document the workflow that you were intending to do, please?

**Comment by rhiaro** [comment]
* Make a PR against the 0.2-dev-ru-translation branch to pull in the updated RST files from -mdtorst. 
* Then on the updated 0.2-dev-ru-translation, extract the strings (`make gettext`) 
* and push to transifex. 
* Give it five minutes, then pull from transifex - this will keep things updated with as many of the translated strings that transifex knows are the same, but will drop the ones with syntax differences (which is what we want for now)
* Commit the po files that have changed and push.
* Now you can do a readthedocs build for the RU project with the 0.2-dev-ru-translation branch. Some translations will be missing but FINGERS CROSSED the build won't fail.

**Comment by siwhitehouse** [comment]
Thanks rhiaro, that's really appreciated.

**Comment by kd-ods** [comment]
> Make a PR against the 0.2-dev-ru-translation branch to pull in the updated RST files from -mdtors

Done with PR #221. Over to you to review, @siwhitehouse.

**Comment by kd-ods** [comment]
All the md files have now been converted to rst. 

(And as a bonus, the RTD ru dev build now works: http://standard.openownership.org/ru/0.2-dev-ru-translation/ . Woop!)
