### ISSUE TITLE
Canonical examples: ownership structures

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#174]
Draft list of ownership structures to be used in examples and documentation using the framework described in #173 . 

Comments welcome on the doc. Please note suggestions for additions in this issue.

https://docs.google.com/spreadsheets/d/1Ui0PnPzEvLeQxgnDq2T9vQeQaR3lWeUiIFFOrFtN4Mc/edit#gid=0

**Comment by stevenday** [comment]
Are there more types of missing data that we should include than 'Listed entity with no recorded beneficial owners'? Good examples of (legitimate) use of missing info reasons, etc seem like they'd be very useful to implementers and end data users.

**Comment by timgdavies** [comment]
This has been continued through internal OpenOwnership work which should be surfaced as part of next upgrade process. I don't think we need to track this further here right now.
