### ISSUE TITLE
Canonical examples: disclosure regimes

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#176]
Draft list of disclosure regimes to be used in examples and documentation using the framework described in #173 .

Comments welcome on the doc. Please note suggestions for additions in this issue.

https://docs.google.com/spreadsheets/d/1Ui0PnPzEvLeQxgnDq2T9vQeQaR3lWeUiIFFOrFtN4Mc/edit#gid=879376168

**Comment by timgdavies** [comment]
This has been progress through internal OpenOwnership work and will surface in the next upgrade. I don't think we need to track further here right now.
