### ISSUE TITLE
Schema & Docs: item descriptions need to be added for AddressType

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#177]
This is a child issue of #160 
Currently, there are no descriptions in the AddressType codelist. 

code | title | description | technical note
-- | -- | -- | --
placeOfBirth | Place of birth |   |  
home | Home address |   |  
residence | Residential address |   |  
registered | Registered address |   |  
service | Service address |   |  
alternative | Alternative address |   |  

Below are my first attempts at providing descriptions

code | title | description | technical note
-- | -- | -- | --
placeOfBirth | Place of birth | The place where a person was born. This must only be used to describe natural persons. Only a town and country are required. |  
home | Home address |   |  
residence | Residential address |   |  
registered | Registered address | An official address for delivering statutory mail and legal notices, which must be provided to company registers in the UK and other jurisdictions. This must only be used to describe entities. |  
service | Service address | An address which can be used as an alternative to a residential address for the purpose of receiving post. This must only be used for natural persons |  
alternative | Alternative address | An address provided in addition to the primary address for this entity or person that is neither a service nor a registered address. |  

I've left home and residence blank. This is because I think of them as being synonymous. I can't see any discussion within the repo's issues about this. I think we either need to be able to distinguish between them or choose one and remove the other from the codelist.

**Comment by kd-ods** [comment]
Those descriptions look good to me.

**Comment by siwhitehouse** [comment]
I'm going round in circles trying to differentiate between 'home' and 'residence'. We should either be able to clearly state their different uses, or we should merge them.

**Comment by kd-ods** [comment]
(Is there a case for added a 'businessAddress' field? At the moment, such addresses would have to be given the type 'alternative'.)

**Comment by siwhitehouse** [comment]
@kd-ods I think there is a case for adding a 'business' field, yes. 

At the moment we have 'registered' address which is for entities only. Entities can also use 'alternative', along with natural persons.

I'm assuming that 'business' would be for use by entities only and that it will be used to describe one or more additional addresses where an entity conducts its business.

So, an entity could declare its registered address along with one or more business addresses, with 'alternative' there to catch any scenarios that we haven't thought of.

Does that sound right to you?

This does raise another consistency issue. Whereas some codelists include their codelist type within their codes, others do not.

So, we have the situation where the EntityType codelist includes an 'unknownEntity' code whereas the InterestLevel codelist includes an 'unknown' code.

**Comment by siwhitehouse** [comment]
The only way I can think of differentiating the home and residential addresses is as follows.

code | title | description | technical note
-- | -- | -- | --
home | Home address | The address of the house or apartment which is the main place of residence. This must only be used for natural persons |  |
residence | Residential address | An address of a house or apartment where someone lives that is not their main place of residence |  |

Is this correct? Does it make sense to make this kind of differentiation in the schema?

**Comment by siwhitehouse** [comment]
[All codelists have been edited](https://github.com/openownership/data-standard/tree/0.2-dev-codelists-160/schema/codelists) with this one changed as per the discussion in this issue.

**Comment by ScatteredInk** [comment]
I would be inclined to merge home and residential and, as suggested, add the distinction between registered and business. This keeps us in line with the CRS, which uses:

• OECD301= residentialOrBusiness
• OECD302= residential
• OECD303= business
• OECD304= registeredOffice
• OECD305= unspecified

We might want to add `residentialOrBusiness` - but I don't see a pressing need for it, and can see this adding privacy concerns/disclosure loopholes if it is an option _now_.

I'd also note that `alternative` is doing a lot of work here that we might want to document further at a later date. It would cover, for example, the CRS case of “hold mail” instruction or “in-care-of” address - oddly this doesn't have a code in the CRS itself.

**Comment by siwhitehouse** [comment]
`alternative`  is basically "anything we didn't think of in the rest of the list" at the moment, so yes I agree we should look at it in more detail at a later date.

**Comment by ScatteredInk** [comment]
Done in #194
