### ISSUE TITLE
Schema & Docs: item descriptions need to be added for NameType

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#179]
This is a child issue of #160
Currently, there are no descriptions in the NameType codelist.

code | title | description | technical note
-- | -- | -- | --
individual | Given name |   |  
translation | Translation of name |   |  
former | Former name |   |  
alias | Alias |   |  
aka | Also Known As |   |  
nick | Nickname |   |  
birth | Birth name |   |  

Descriptions to follow. I have a question as to how we distinguish between alias, aka and nick

**Comment by ScatteredInk** [comment]
> I have a question as to how we distinguish between alias, aka and nick

@siwhitehouse You and me both. These were taken from the Common Reporting Standard as we were aiming for compatibility. I think we could perhaps compress these three down to one, and suggest that any data from CRS-compatible sources does the same.

**Comment by siwhitehouse** [comment]
'individual' has the title of 'Given name'. Someone's given name can be described as their first name or their Christian name, amongst other things. It is not a full name. If asked to provide my "Given name" I would say "Simon", for example.

This codelist exists within the Name object, which is used to describe all of the components of somebody's name. In fact, it includes 'givenName' as a property of the Name object. 

In the example data we have

```json
"names": [
      {
        "type": "individual",
        "fullName": "Christopher Taggart",
        "givenName": "Christopher",
        "familyName": "Taggart"
      },
      {
        "type": "aka",
        "fullName": "Chris Taggart"
      }
    ],
```

So, I am going to suggest that we change the title for 'individual' to something else. Would 'legal name' be a reasonable replacement?

**Comment by siwhitehouse** [comment]
code | title | description | technical note
-- | -- | -- | --
individual | Legal name | A name that identifies the person for legal, administrative and other official purposes. A person's legal name will usually be the one that is found on official government documents. 
translation | Translation of name | A translation of the person's individual name in a different language |  
former | Former name | A name that the person has used in the past. |  
alternative | Alternative name | Another name that the person is known by. This might be an alias, a nickname or a name that the person is also known as (aka) | 
birth | Birth name | The legal name of the person at birth. |  

Note that there is no way of indicating what a translated name is a translation of.

**Comment by kd-ods** [comment]
These look good to me. We'll need to note in the changelog that alias, aka, and nick have been replaced by 'alternative.

**Comment by siwhitehouse** [comment]
This needs more eyes on it. @ScatteredInk could you look at this on your return, please?

Also, we should standardise the use of code and title when using 'alternate'/'alternative'. See addressType and entityStatement/alternateNames

**Comment by siwhitehouse** [comment]
Also note that the description for 'translation' specifies that this is a translation of the 'individual' name. By having translation in the codelist we are not able to explicitly state which name is being translated, nor which languages are being translated from and to.

**Comment by siwhitehouse** [comment]
[All codelists have been edited](https://github.com/openownership/data-standard/tree/0.2-dev-codelists-160/schema/codelists) with this one changed as per the discussion in this issue.

**Comment by ScatteredInk** [comment]
Agree on both replacing given name and compressing aka etc into alternative.

For 'translation' - this is a very good point. And, do people 'translate' names or do they 'transliterate' them - or both? For verified data, the transliterated option seems essential and then we do need the metadata on X to Y. This is something to look at in 0.3 but do we want to add 'transliterated' as well as/instead of 'translated' here?

**Comment by siwhitehouse** [comment]
I hadn't considered 'transliteration' and I agree that we might want to add it.

At the moment we have Name/type as a string and so data producers might find them in the situation where they have to choose one over the other.

For example, because I'm not sure how clear I am being, in Russian a person might have the first name 'Андрей' which transliterates as 'Andrey', but also might be additionally translated to 'Andrew'. There is no way in BODS at the moment, afaics, of expressing that the name type is both a 'transliteration' and a 'translation'.

I suspect that in the future I'll be arguing for an object/series of properties in the schema for translations and transliterations.

This is a long way round of saying that I agree we add 'transliteration' for 0.2 but make a note that this is a section we want to pay attention to for 0.3.

**Comment by ScatteredInk** [comment]
Good point - I think that having both options is the way to go here.

For 0.3, I think that we will want a solution that can be generalised across all of our fields (or at least the relevant ones), to catch use cases like company names that are declared in multiple languages etc. At the moment we are using annotations for that and I don't think it works particularly well in cases when we can apply structure.

**Comment by siwhitehouse** [comment]
Without diving into the detail, I agree with investigating a generalised approach. Once we have closed this issue for the codelist I'll raise another one for the 0.3 task.

For now, I'm going to suggest the following be added to the codelist:

code | title | description | technical note
-- | -- | -- | --
transliteration | Transliteration of name | A transliteration of the person's individual name in a different script |

**Comment by ScatteredInk** [comment]
Done in #194
