### ISSUE TITLE
Field representation: Address information

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#18]
We will need to collect address information in a number of places.

There are two broad options here:

* (1) Require structured addresses
* (2) Allow semi-structured addresses, and require users to parse them for matching

## Structured Addresses

This would represent addresses using a collection of fields. For [PostalAddress](https://schema.org/PostalAddress) Schema.org uses:

* postOfficeBoxNumber - The post office box number for PO box addresses.
* streetAddress - The street address. For example, 1600 Amphitheatre Pkwy.
* addressLocality - The locality. For example, Mountain View.
* addressRegion - The region. For example, CA.
* postalCode	- The postal code. For example, 94043.
* addressCountry - The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code.

The challenge here is that source systems may:

* (a) have a different set of source fields;
* (b) only have unstructured address information; and/or 
* (c) assign address portions to different fields anyway

For example, three source systems could have the address of Chrinon Ltd as:

> (1) Address: [ Aston House, Cornwall Avenue, London, N3 1LF ]

> (2) Line 1: [ Aston House ]; Line 2: [ Cornwall Ave ]; Town: [ London ]; County: [     ]; Zipcode: [ N3 1LF ]; 

> (3) Street Address: [ Aston House, Cornwall Ave ]; Town: [   ]; County: [ London ]; Postal Code: [ n3 1lf ]; Country: [ England ] 

Any system trying to match these will need to do quite a lot of processing to normalise them.

## Semi-structured addresses

A semi-structured address approach would include three fields:

* Address - The address, with each line of the address separated by a line-break or comma. This can also include the postalcode. 
* Postcode - The postal code on it's own.
* Country - The ISO Country code for the country

Users would then need to use a library such as [libpostal](https://github.com/openvenues/libpostal) to parse out structured address data when full addresses are needed. 

## Discussion

My initial sense is that, as users are going to need to do a lot of work to match addresses anyway, we should:

* Provide implementation guidance for data-input systems to capture structured addresses;
* Use the semi-structured address model in the schema itself - having just three fields there for address;

**Comment by jpmckinney** [comment]
Also noting that many EU countries have adopted INSPIRE, whose fields are different from the vCard fields reused by Schema.org.

My sense is the same as in the issue description.

**Comment by timgdavies** [comment]
Our [address model is found here](http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#address)

**Comment by timgdavies** [comment]
The [OCED Common Reporting Standard has the following address types](http://www.oecd.org/tax/automatic-exchange/common-reporting-standard/schema-and-user-guide/#d.en.345315):

```xml
	<xsd:simpleType name="OECDLegalAddressType_EnumType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">This is a datatype for an attribute to an address. It serves to indicate the legal character of that address (residential, business etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="OECD301">
				<xsd:annotation>
					<xsd:documentation>residentialOrBusiness</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="OECD302">
				<xsd:annotation>
					<xsd:documentation>residential</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="OECD303">
				<xsd:annotation>
					<xsd:documentation>business</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="OECD304">
				<xsd:annotation>
					<xsd:documentation>registeredOffice</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="OECD305">
				<xsd:annotation>
					<xsd:documentation>unspecified</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
```
