### ISSUE TITLE
Schema & Docs: item descriptions need to be added for StatementType

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#180]
This is a child issue of #160
Currently, there are no descriptions in the StatementType codelist.

code | title | description | technical note
-- | -- | -- | --
personStatement | Person Statement |   | The parent object should be validated using the person-statement schema.
entityStatement | Entity Statement |   | The parent object should be validated using the entity-statement schema
ownershipOrControlStatement | Ownership or Control Statement |   | The parent object should be validated using the ownership-or-control-statement schema.

Descriptions to follow.

**Comment by siwhitehouse** [comment]
We do have descriptions of these statements that we can rewrite from the [data standard website](http://standard.openownership.org/en/v0-1/schema/reference.html#schema-person-statement)


code | title | description | technical note
-- | -- | -- | --
personStatement | Person Statement | The information known about a natural person at a particular point in time, or from a given submission of information | The parent object should be validated using the person-statement schema.
entityStatement | Entity Statement | The information that identifies and describes the entity that is the subject of the ownership or control described in an ownership or control statement.  | The parent object should be validated using the entity-statement schema
ownershipOrControlStatement | Ownership or Control Statement | The information that identifies an entity, an interested party (a reference to an entity, natural person, arrangement or trust), details of the interest that the interested party holds in the entity and provenance information for the statement. | The parent object should be validated using the ownership-or-control-statement schema.

If we want to re-write any of the above descriptions we should also review their descriptions on the standard's website.

**Comment by kd-ods** [comment]
Suggested edits:

personStatement description:
The statement contains information known about a natural person at a particular point in time, or from a given submission of information.

entityStatement description:
The statement contains information that identifies and describes an entity (company, legal entity, institution etc.) at a particular point in time, or from a given submission of information.

wnershipOrControlStatement title:
Ownership-or-control Statement

ownershipOrControlStatement description:
The statement contains details of the ownership and/or controlling interests held by an interested party in an entity at a particular point in time, or from a given submission of information

**Comment by siwhitehouse** [comment]
I'm happy with the rephrasing to "The statement contains ....."

I'm not sure why you have added a sub-definition for 'entity' in the entityStatement description, but removed the one I'd included from "interested party" in the ownershipOrControlStatement description. 

I'd be inclined to remove both of them, as they are defined elsewhere in the glossary (or they will be).

**Comment by siwhitehouse** [comment]
The statement contains details of the ownership and/or interests held by an interested party in an entity at a particular point in time.

**Comment by kd-ods** [comment]
Technical notes in line with the style guidance suggestion:

The parent object should be validated using the Person Statement schema.

The parent object should be validated using the Entity Statement schema.

The parent object should be validated using the Ownership-or-control Statement schema.

**Comment by siwhitehouse** [comment]
[All codelists have been edited](https://github.com/openownership/data-standard/tree/0.2-dev-codelists-160/schema/codelists) with this one changed as per the discussion in this issue.

**Comment by ScatteredInk** [comment]
Done in #194
