### ISSUE TITLE
Update Changelog, About page & version mentions for 0.2 release

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#182]

**Comment by kd-ods** [comment]
This is in progress. You can see changes so far on [this branch](https://github.com/openownership/data-standard/blob/0.2-dev-changelog-182/docs/schema/changelog.rst).

**Comment by kd-ods** [comment]
Have updated this issue, since I'm going to work on the Changelog, About page and general version mentions on a single branch.

For reference, version info is mentioned on the following pages:

./index.rst
./schema/conformance.rst
./schema/schema-browser.rst
./schema/changelog.rst
./schema/guidance/index.rst
./schema/index.rst
./schema/reference.rst
./schema/concepts.rst
./about/credits.md
./about/index.md

**Comment by ScatteredInk** [comment]
Not obvious as it's part of the missing info work but: 

`personType` is now a required field in `personStatement`, bringing it into line with `entityType` in `entityStatement`
