### ISSUE TITLE
Updates to the entityType codelist / EntityStatement model

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#186]
For 0.3, think about how/why we categorise entities the way that we do.

Drivers are:

- what other kinds of data we expect to find in the statement (identifiers, explanations for missing data)
- what kinds of ownership-or-control we expect that entity to be involved in.

We might want a smaller set of categories and a set of boolean flags: `hasLegalPersonality`, `isRegistered` etc.

**Comment by ScatteredInk** [comment]
Noting from #185 that our treatment of arrangements is very broad:

> It would be useful to differentiate between arrangement types, e.g. trusts, joint shareholdings, contracts, nominee arrangements.
> This could be a codelist if entityType is arrangement.
> I suggest we do this in 0.3. There is some thinking on this in #92.

**Comment by timgdavies** [comment]
There is support from alca.ai for the idea of a distinct Trusts `entityType` codelist value. 

They note that this would support validation of the kinds of interestType you would expect to find.

> I was wondering whether a trust being such common (unincorporated) should have its own class, on the basis that trusts have a number of common features: beneficiaries, board of trustees, protectors, which are correctly identified in InterestType.

**Comment by ScatteredInk** [comment]
From discussion on visualisation and EITI form design: listed status and SOE status are two more common entity types we might expect to see and want to distinguish in order to explain control structures.

**Comment by kd-ods** [comment]
Just a quick note on the concept of SOE status: depending on the definition of State Owned Enterprise in a given context, an entity might be an SOE due to direct or indirect state control/ownership. So there are definitely options when it comes to how SOEs should/could be rendered in BODS data that need to be explored. See #113

**Comment by timgdavies** [comment]
I understand this to primarily be an issue of values in the [`entityType` codelist](http://standard.openownership.org/en/0.2.0/schema/reference.html#entitytype) and so we should come up with a proposal for updates to that codelist. 

If there is a wider question here of how the `EntityStatement` could be used to describe other kinds of beneficially owned entities (e.g. Assets and Land) then we should consider whether:

(a) `EntityStatement` can be extended to work for both legal structures and assets

or

(b) Whether a new `AssetStatement` is required, and what this might look like.

**Comment by ScatteredInk** [comment]
> I understand this to primarily be an issue of values in the entityType codelist and so we should come up with a proposal for updates to that codelist.

I'm not sure this is quite right. At the moment `entityType` lets us pick one value. If we added, say, state-owned enterprises, listed companies and trusts then to describe a company like Saudi Aramco we would want all three of "listed company", "state-owned enterprise" and "registered company".

So this may be about an upgrade to the list and a rethink of the structure (bearing in mind that we also have anonymous and unknown types in there right now).

**Comment by kd-ods** [comment]
@ScatteredInk - do you think we can close this ticket when #336 and #339 are implemented and closed? (If so I'll remove this from the 0.3 project.)

**Comment by ScatteredInk** [comment]
Yes, I do - I've removed.

**Comment by kathryn-ods** [comment]
@kd-ods does the incorporation of entityType.subtype and entityType.details effectively answer this ticket?

**Comment by kd-ods** [comment]
Yes, I think we should close this and use #336 for remaining work on entity classification.
