### ISSUE TITLE
Update documentation from 0.2 changes

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#196]
- [ ] PEPs 
- [x] Date fields across the schema: what goes where  - see #387 
- [ ] Publishers, Entities, source.assertedBy.agent: how they overlap and interact
- [ ] How to represent missing/unknown/anonymised information
- [ ] Metadata 
- [x] Publication patterns for indirect ownership #156

**Comment by kathryn-ods** [comment]
- We still don't have information about PEPs. My expectation is that this will eventually be stripped out from the main schema and turned into an extension so don't think we need to do this. 
- Date fields guidance is done 
- I think information about publishers/sources is covered in https://standard.openownership.org/en/main/standard/modelling/record-ids.html 
- missing/unknown/anonymised. We have an anonymous example in https://standard.openownership.org/en/main/examples/index.html#a-trust-like-arrangement and an unknown example in https://standard.openownership.org/en/main/standard/modelling/repr-nominations.html and we have info about redaction/corrections

I think this ticket can be closed now as it's quite out of date

**Comment by kd-ods** [comment]
For the record - improving how to represent missing/unknown/anonymised info is still to be addressed. See [this feature ticket](https://github.com/openownership/data-standard/issues/389) and [related issues](https://github.com/openownership/data-standard/labels/feature%3A%20missing%20information).
