### ISSUE TITLE
Handling changes in statements

### ISSUE THREAD

**Issue by CountCulture** [openownership/data-standard#20]
How do we handle changes in statements, and in particular how do users know that the underlying facts that a statement refers to have changed, especially if statements are immutable.

For example, let's say there's a 'statement' that says that A controls B via share ownership. Let's say that there is a subsequent statement that says A controls B via the right to appoint the majority of directors. Should the user understand this to mean:
i) The new statement replaces the old one: A now controls B only via the right to appoint the majority of directors
ii) The new statement is in addition to the old one: A now controls B only via share ownership and the right to appoint the majority of directors

As a slight variation, imagine the scenario where A ceases to control B via share ownership. Should this be modelled as a second statement (with start and end dates), and how do the users know that this is the same relationship that had just a start date?

**Comment by timgdavies** [comment]
There are two contexts in which this kind of issue arises:

(1) When dealing with data from a single source;

(2) When dealing with data from multiple sources;

## Multiple sources
In case (2) where, for example:

* S1: On 1st January 2017 **Source A** makes a statement that A controls B via share ownership;
* S2: On 15th Feb 2017 **Source B** makes a statement that A controls B via right to appoint majority of directors; 

the question of whether S2 replaces, or complements S1 is not easily worked resolved. 

However, the two statements:

* S3: On 1st January 2017 **Source A** makes a statement that A has 50 shares in B starting from 1st January;
* S4: On 15th Feb 2017 **Source B** makes a statement that A had 50 shares in B from 1st January to 15th Feb;

might be easier to

**Comment by CountCulture** [comment]
Right, but in my example, you cannot infer that one supersedes the other, as perfectly possible for both to be true. So we either need to bake rules in, or make it explicit e.g. by saying one is an edit of/supersedes another (how do we say a statement is no longer true, by an edit with an end date), or perahps by saying that each statement or group of statements replace other ones.

**Comment by CountCulture** [comment]
FWIW I think different sources is out of scope for the moment, and the decisions of how to handle this should be for the end user

**Comment by timgdavies** [comment]
I think we need to design with the multiple sources in mind- as a key use case here is synthesis of data from different systems. 

I'm leaning towards the idea of a 'replacesStatements' property, in which an array of statement guids can be given - either at the StatementGroup level, or the individual statement level.

If we allow that ids might be [guid]-[suffix] then an implementer could, for example, choose to:

* Assign a guid to information in their system at the point they are created;
* Use that guid + a version number as the statement identifier;
* Publish the guid + last version number in a ```replacesStatements``` property;

**Comment by CountCulture** [comment]
Do we need to design the standard (as opposed to the Open Ownership Register) to handle multiple sources? Even if we do, does it need to handle anything more than aggregation at the moment (i.e. park conflict, which will need to have info on who or what resolved the conflict)?

**Comment by timgdavies** [comment]
I'm not sure I understand the question. 

This is a standard for open data. That means multiple people will be providing the data - and users will be likely to want to work with data from those multiple sources.

**Comment by CountCulture** [comment]
Right, but will the data from multiple sources be in the same file? And more to the point, will the combined data need to refer to each other?

**Comment by timgdavies** [comment]
It's possible that a service **republishing** data would have data from multiple sources (the chaining of provenance information helps here) in a single file (though we should generally avoid thinking of files too much.... better to think of applications dealing with either 'streams' or 'clouds' of data). 

I would not imagine many cases of **Source A** cross-referencing **Source B**, but both **Source A** and **Source B** might refer to the same company or individual.

**Comment by mpostelnicu** [comment]
given each statement is immutable, besides the identifier, which should remain constant, i was wondering if it could be beneficial to have a checksum field for the statement itself, something like an MD5, calculated using all the fields inside the statement, except for the checksum, of course. If the statement is part of a larger entity, it would be interesting if the MD5 of the higher entity would also depend on the MD5 of its siblings, so that any fields or checksums get changed in any siblings, the parent itself becomes invalid (so some sort of protection against post-publishing forgery, if for example someone wants to remove a piece of information, but do that without releasing a new statement).

**Comment by bensymonds** [comment]
I haven't fully thought through the "replacesStatement" thing yet, but it sounds like it's worth exploring.

I've always seen the combining of data from multiple sources as being a job for consumers, and not for the standard itself. Consumers would see two sources of information (possibly conflicting) about the relationship between A and B, and have to make up their own mind how to combine it, based on how much they trust the source, how fresh the data is, etc. Hence the importance of the provenance info. So a statement from one source would never replace a statement from another. A source can only replace its own statements.

**Comment by sebbacon** [comment]
Could it be sufficient to be able to say statement A is either (i) now known to be wrong, or (ii) no longer true?

When would it be useful to have the additional information that no longer is it no longer true but it was caused to be no longer true by the introduction of a specific new statement?

**Comment by timgdavies** [comment]
In effect, our mechanism to say that 'Statement A' is no longer true is to make an empty 'Statement B' which replaces it. 

This would be justified on a few grounds:

(1) It maintains the idea of immutable statements;

(2) It make explicit what is being 'cancelled' or nulled out. I.e. the whole statement? Or just some part of it?

(3) It fits with how most systems would work, such that there will have been a transaction at a particular time to 'cancel' the truth of Statement A, and knowing the provenance of that transaction may be important;

**Comment by timgdavies** [comment]
This is covered at http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#updating-statements but could do with further worked examples in future iterations of the documentation, and with some test implementations.

**Comment by kd-ods** [comment]
Noting here that #9 also relates to change over time.

**Comment by kathryn-ods** [comment]
BODS 0.4 resolves issues with change over time and overlapping declarations from multiple sources
