### ISSUE TITLE
Update schema descriptions from 0.2 changes

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#200]
- [ ] Bring descriptions into line with new [style guidance](https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md).
- [ ] Add info to source.assertedBy.agent about when agent should also be publisher. (See PR #193)
- [ ] Add info to entityStatement.name about when name should also be publisher.

**Comment by kd-ods** [comment]
Before doing the above, update the style guidance around field/code descriptions. Something along the lines of [OCDS guidance](https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#field-and-code-descriptions).

**Comment by kathryn-ods** [comment]
Style guide and schema descriptions have all been reviewed while developing 0.4
