### ISSUE TITLE
Docs dev: unicode character not rendering

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#219]
In the schema components.json file, the [description field for the Share object](https://github.com/openownership/data-standard/blob/2cea40121880820dc8c3cf08df31d1f9288ba262/schema/components.json#L277) contains a 'less than or equal' character. 

When building the docs locally the character is not displayed, instead the unicode value is given:

"By default the minimum is inclusive and the maximum exclusive (minimum-value \u2264 share < maximum-value )"

**Comment by odscjames** [comment]
AS A programmer
I DIDN'T KNOW there was a unicode sign like that
BECAUSE I've always just used <=

**Comment by odscjames** [comment]
Where are you seeing this occur?

Locally, /schema/reference.html#interest renders correctly for me.

And /schema/schema-browser.html#schema-browser-ownership-or-control seems to truncate the description so I can't see it anyway.

**Comment by kd-ods** [comment]
Problem doesn't exist in RTD: http://standard.openownership.org/en/0.2-dev/schema/reference.html#interest

So closing issue.

**Comment by kd-ods** [comment]
Reopening. I've spotted it in the main RTD build here: http://standard.openownership.org/en/0.2-dev/schema/reference.html#share

What's interesting is that it's rendered properly in the parent object elsewhere in the same build: http://standard.openownership.org/en/0.2-dev/schema/reference.html#interest

**Comment by kd-ods** [comment]
... And I'm not just reopening, I'm upping the priority on this since @siwhitehouse and I have just spotted a more problematic instance of the problem.

@siwhitehouse has just enabled the RTD build for the 0.2-dev-ru-translation branch (to check that it builds OK and to run through the workflow end-to-end). None of the schema object descriptions on the references.rst page are coping with Russian characters (not of the Anna Karenina-type, natch); like here on the [Address description](http://standard.openownership.org/ru/0.2-dev-ru-translation/schema/reference.html#address):

> \u0421\u0442\u0440\u043e\u043a\u0430 \u0430\u0434\u0440\u0435\u0441\u0430 \u0441 \u043d\u0435\u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u043c \u0442\u0435\u043a\u0441\u0442\u043e\u043c, \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u0443\u043a\u0430\u0437\u0430\u043d\u043e \u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u044b\u0445 \u0434\u0430\u043d\u043d\u044b\u0445 \u043e\u0431 \u0430\u0434\u0440\u0435\u0441\u0435 \u0438 \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u043f\u0440\u0438\u0433\u043e\u0434\u043d\u0430 \u0434\u043b\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043f\u0440\u0438 \u043f\u043e\u043c\u043e\u0449\u0438 \u0430\u043b\u0433\u043e\u0440\u0438\u0442\u043c\u043e\u0432 \u043f\u0430\u0440\u0441\u0438\u043d\u0433\u0430 \u0430\u0434\u0440\u0435\u0441\u043e\u0432. \u0412 \u043d\u0435\u043a\u043e\u0442\u043e\u0440\u044b\u0445 \u0441\u043b\u0443\u0447\u0430\u044f\u0445 (\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, \u041c\u0435\u0441\u0442\u043e \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f) \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0433\u043e\u0440\u043e\u0434 \u0438 \u0441\u0442\u0440\u0430\u043d\u0430.

(Where it looks like Russian text _is_ being properly handled - e.g. [Annotation](http://standard.openownership.org/ru/0.2-dev-ru-translation/schema/reference.html#annotation) - actually the translated text is not being pulled from the schema but is part of the [rst file](https://github.com/openownership/data-standard/blob/0.2-dev-ru-translation/docs/schema/reference.rst).)

**Comment by odscjames** [comment]
Replicated and fix suggested.

The fix is to the JSONValue class which was copied and pasted into docs/conf.py a year ago. As such, i have no idea where it came from, what it's original purposes was, why it was trying to do this. This is obviously not ideal.

I have tested in English only; but I think this fix should work for Russian too.

json-value is often used like:

    .. json-value:: ../_build_schema/components.json
       :pointer: /definitions/Interest/properties/share/description

Where the pointer is a pointer to a string only. If this pointer is ever a pointer to an object. this will need to be checked - and if so, can you let we knew where, because I'm really curious about the use case.

Can you test this?

**Comment by kd-ods** [comment]
We use the json-value directive extensively in [docs/schema/reference.rst](https://github.com/openownership/data-standard/blob/0.2-dev-ru-translation/docs/schema/reference.rst) to pull out and display object descriptions from the schema, e.g.:

```
PepStatusDetails
----------------

.. json-value:: ../_build_schema/components.json
   :pointer: /definitions/PepStatusDetails/description
```

As far as I can see, the pointer only ever references a description, not an object.

I'm off to test the fix.

**Comment by kd-ods** [comment]
James - I tested this locally by merging 219-unicode-error into 0.2-dev-ru-translation then rebuilding the docs. It worked in that the 'greater-than-or-equal-to' character rendered properly on the equivalent page locally of http://standard.openownership.org/en/0.2-dev/schema/reference.html#share.

I don't think I can easily build the ru docs locally. So I think we need to merge your fix into the 0.2-dev-ru-translation branch. We're building RTD from that branch and will be able to test the fix there. That OK? @siwhitehouse - can you help with that stage of testing?

**Comment by siwhitehouse** [comment]
@kd-ods Yes. I can test this. I'll speak with @odscjames this afternoon.

**Comment by odscjames** [comment]
I think I heard this does fix the issue; @siwhitehouse where are we with merging that commit to an applicable branch, do you want my help with that?

**Comment by kd-ods** [comment]
Yes - this fix has worked. The Russian docs build is rendering the characters as expected:
http://standard.openownership.org/ru/0.2-dev-ru-translation/schema/reference.html#annotation

Will leave @siwhitehouse to answer branches question.

**Comment by odscjames** [comment]
This commit is on the master branch - https://github.com/openownership/data-standard/commit/4052e41266697bc5ce1e881f40627b0745c58a13

And thus I think this issue can now be closed?

**Comment by odscjames** [comment]
Whoops, was going to let one of you sign off and close this if done.

**Comment by kd-ods** [comment]
Yes - fix is visible in http://standard.openownership.org/ru/latest/schema/reference.html. Closing.
