### ISSUE TITLE
Internationalisation: some strings not translated/translatable on front page

### ISSUE THREAD

**Issue by odscjames** [openownership/data-standard#223]
From https://github.com/openownership/data-standard/issues/222#issuecomment-509120944

> See http://standard.openownership.org/ru/0.2-dev-ru-translation/index.html where the headings "For Newcomers" and "For Developers" have not been translated.
>
> Checking in https://www.transifex.com/OpenDataServices/bods-v02/translate/#ru/about--index/174975439 shows that this did not get pushed up to Transifex (assuming that is the correct file).
>
> Checking locally in the docs/locale/ru/LC_MESSAGES/index.po file I don't see either of these headings.

**Comment by odscjames** [comment]
It's because they are in as raw blocks, so the H2 comes in properly.

     .. raw:: html

      <h2>For Developers</h2>

Hmmm

**Comment by odscjames** [comment]
I think this can be fixed by changing these to

       .. cssclass:: h2
  
          For Newcomers

I haven't been able to confirm this makes them translatable tho.

One issue; this removes a bit of spacing (margin 10px above the header). If that's a problem, we can put it back in the CSS in the https://github.com/openownership/data-standard-sphinx-theme repo

**Comment by siwhitehouse** [comment]
I've made the changes suggested by @odscjames in a separate branch locally. Running `make gettext` results in an index.pot file that includes the two subheadings that weren't originally in Transifex.

I've pushed this extract up to [a test project in Transifex](https://www.transifex.com/OpenDataServices/bods-test/dashboard/) and the strings for the two separate headings show there too.

I'm going to push my local 0.2-dev-ru-translation-css branch up, which implements James' fix, and make a pull request to merge it with 0.2-dev-ru-translation.

**Comment by odscjames** [comment]
This is now merged into 0.2-dev-ru-translation and I think this can be closed.

**Comment by odscjames** [comment]
Pushed another commit to fix formatting

**Comment by rhiaro** [comment]
For future reference, the fix for this issue that keeps the semantic/accessible html headers while keeping the text extractable for translation is to change

```
.. raw:: html

  <h2>For Developers</h2>
```

to

```
.. raw:: html

   <h2>

For Developers

.. raw:: html

   </h2>
```
