### ISSUE TITLE
Remove recommonmark dependency from docs

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#226]
Since all of the documentation pages are now RST we no longer need a markdown parser in sphinx.

TODO: Triple check for any stray markdown, eg. there are still some markdown links in schema descriptions at the time of writing. Not sure if these are rendered to HTML by Sphinx or docson/jsonschema though.

**Comment by timgdavies** [comment]
Related to #264

**Comment by odscjames** [comment]
I don't think this is related to #264 - see https://github.com/openownership/data-standard/issues/264#issuecomment-617784175

**Comment by odscjames** [comment]
We can remove this from our explicit requirements but to fully remove this we need to also upgrade:
* sphinxcontrib-jsonschema / sphinxcontrib-opendataservices-jsonschema to 0.2 or above and this is not simple, it depends on #318
* sphinxcontrib-opendataservices to 0.2 - this actually depends on sphinxcontrib-opendataservices-jsonschema so again #318 is a dependency
