### ISSUE TITLE
Check data model against UK Standard Selection Questionnaire

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#23]
UK government agencies are now being guided (required?) to use a new Standard Selection Questionnaire which contains a section to collect BO data from anyone tendering for, or awarded, public contracts. 

In particular:

§ 1.1(n) asks for 'Details of Persons of Significant Control (PSC), where appropriate:'    

- Name; 
- Date of birth; 
- Nationality; 
- Country, state or part of the UK where the PSC usually lives; 
- Service address; 
- The date he or she became a PSC in relation to the company (for existing companies the 6 April 2016 should be used); 
- Which conditions for being a PSC are met; 
 	- Over 25% up to (and including) 50%, 
	- More than 50% and less than 75%, 
	- 75% or more.  

(Please enter N/A if not applicable)

§ 1.1(o) asks for 'Details of immediate parent company:'
 
- Full name of the immediate parent company
- Registered office address (if applicable)
- Registration number (if applicable)
- Head office DUNS number (if applicable)
- Head office VAT number (if applicable)

(Please enter N/A if not applicable)

§1.1(p) asks for 'Details of immediate parent company:'
 
- Full name of the immediate parent company
- Registered office address (if applicable)
- Registration number (if applicable)
- Head office DUNS number (if applicable)
- Head office VAT number (if applicable)

(Please enter N/A if not applicable)

The fact these are in a single cell of a word table, and have  'Enter N/A if not applicable') suggests that the SSQ has not provided any guidance on capturing this information as **structured data** to implementers - so:

(1) There is an opportunity for simple template versions of the BODS here

(2) We should think about how the statement-centric model of BODS could be easily communicated to someone planning to implement data collection as required by the SSQ, and what they could be reasonably expected to capture.

**Comment by CountCulture** [comment]
Tim, where's this from?

-------------------------------------------------------
OpenCorporates :: The Open Database of the Corporate World
http://opencorporates.com
Blog: http://blog.opencorporates.com
Twitter: http://twitter.com/OpenCorporates

OpenCorporates is published by Chrinon Ltd, a company dedicated to
improving and publishing public data under an open licence that allows and
encourages reuse, including commercially. Registered in England, number
07444723.

**Comment by timgdavies** [comment]
This is in the templates attached to https://www.gov.uk/government/publications/procurement-policy-note-816-standard-selection-questionnaire-sq-template

**Comment by timgdavies** [comment]
Work on this can be carried forward as part of OpenOwnership work on Beneficial Ownership & Procurement.
