### ISSUE TITLE
Docs: Address the difference between a data standard and a governance/policy standard

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#232]
See http://bods.opendataservices.coop/redmine/issues/479 for the kind of confusion we should help people avoid.

**Comment by timgdavies** [comment]
Keeping this open for us to carry out a review of draft 0.3 documentation to ensure we are making this distinction clear.

**Comment by kd-ods** [comment]
Closing as this will be dealt with by OpenOwnership's work on communicating about effective disclosure frameworks.
