### ISSUE TITLE
Review (and suggest improvements to) the testing framework in the repo

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#235]
For the standard itself, JM has suggested following the OCDS way: https://github.com/openownership/data-standard/issues/171

It would also be good to think about an approach to tests on the example data in the repository. At the moment:

- everything has to be added by hand to the test file so there is a danger of forgetting;
- the additional properties false check doesn't work with nested additional properties. (Testing with libcovebods works.) See #201

This issue can be closed once:

- The requirements of a fitting test framework have been established
- The current approach to adding and testing example files has been reviewed against our testing requirements.
- Changes to the testing framework (to meet the requirements) have been agreed.

**Comment by kd-ods** [comment]
@ScatteredInk - This is my attempt at pulling the CRM issue into the repo and adding some 'acceptance tests' so that Ben could work on this. Can you please review asap? And assign over to Ben if it's sthg to work on over the next month.

**Comment by ScatteredInk** [comment]
Thanks @kd-ods, this looks good.

The other thing that I've been thinking about is that we now have a lot of test and example data and when we make a substantial change (which might get changed back), work on developing the schema is slowed down by needing to change a lot of test data to make a build pass.

It would be good to think about what the best strategy is here:

- Live with failing builds (but make sure that you know which tests are failing and why) until a change is permanent - feels error-prone to me;
- Run the tests by schema version (OK, but then we need a mechanism to make sure that we actually update our test files);
- Have fewer tests!
- Something else.

**Comment by Bjwebb** [comment]
For tests of the structure of schema and codelists, JM's suggestion looks good. I've written more about that on the issue https://github.com/openownership/data-standard/issues/171#issuecomment-521733258

For testing validation of files against the schema, I think our current code does most of what we want:
* We validate both individual statements and package files
* We validate using both:
  * Our custom code that validates each statement individually, and does extra checks (e.g. that IDs match)
  * Using our package JSON schema file, to check that works correctly
* When validation fails, we check that the error messages are what we expect

As written above, our current code doesn't:
1. Test that sample data doesn't have unexpected extra fields (except for the root object)
2. Check that all data JSON files are tested
3. Make it easy to ignore failing tests, but not lose track that the tests are failing completely

But, I think we can deal with these by making changes to our existing setup.

1. Use compile-to-jsonschema to create a custom schema that we use for testing (with additionalProperties false at every level) https://github.com/openownership/data-standard/issues/201#issuecomment-519998506
2. Write a test function that lists all JSON files in the relevant directories, and check whether they're included in the other tests.
3. I think we can do something here with pytest's [xfail](http://doc.pytest.org/en/latest/skipping.html#xfail-mark-test-functions-as-expected-to-fail) to mark tests we expect to fail, and possibly a Travis test to prevent merging onto master until those are fixed.

**Comment by odscjames** [comment]
> The other thing that I've been thinking about is that we now have a lot of test and example data and when we make a substantial change (which might get changed back), work on developing the schema is slowed down by needing to change a lot of test data to make a build pass.
> Live with failing builds (but make sure that you know which tests are failing and why) until a change is permanent - feels error-prone to me;
> I think we can do something here with pytest's xfail to mark tests we expect to fail, and possibly a Travis test to prevent merging onto master until those are fixed.

It's unclear with this requirement what we want to happen with regards to merging to master.

What do you want?

A) Not to be able to merge to master till everything is good, but to be able to work on a branch for a while.

..... this already happens, and is how branches are meant to work. There is no requirement that a Work In Process branch has to pass all Travis tests all the time :-) It only has to pass tests when it's about to be merged to master. Just keep working on your branch; Travis will tell you "still failing" and stop you merging; at end fix problems; merge to master. I see @ScatteredInk's comment "feels error-prone to me" - could we discuss this?

B) To be able to merge to master with failing Travis tests because your still working on them.

..... we could use xFail here? Mark a test as xFail before merging to master but have a process that we have to fix all xFails before making a release?

Which is it, A or B?

I think I would recommend A, unless the amount of sample data turns really large. I think with B, the risk is they would be forgotten. you'd be ready to make a new release, suddenly find 37 xFails, not be able to work out the original reasons behind the change and have a hard time sorting them all out.

**Comment by odscjames** [comment]
> everything has to be added by hand to the test file so there is a danger of forgetting;
> Write a test function that lists all JSON files in the relevant directories, and check whether they're included in the other tests.

Is this a concern for:
A) Just the samples in the "examples" dir - they appear in the docs, so they must be correct?
B) "examples" but also the test data in "tests/data".

I'm not sure if B is less important, if someone adds test data but not a test the test data just won't do anything. 


(noting https://stackoverflow.com/questions/49117806/what-is-the-best-way-to-parameterize-a-pytest-function-using-a-fixture-that-retu )

**Comment by kd-ods** [comment]
> Is this a concern for:
> A) Just the samples in the "examples" dir - they appear in the docs, so they must be correct?
> B) "examples" but also the test data in "tests/data".

I think it's a concern for both, possibly more for (B), depending on the answer to....

A prior question: are we clear how and why we're using the test data? I'm not sure we've documented or talked about how it fits into the development process for the schema, how extensive the fixtures should be and so on. I realise that's a bit of an open-ended question, apols.

**Comment by odscjames** [comment]
> A prior question: are we clear how and why we're using the test data? I'm not sure we've documented or talked about how it fits into the development process for the schema, how extensive the fixtures should be and so on. I realise that's a bit of an open-ended question, apols.

That is a good question, and also opens up another question. Currently, the automatic checks in the standard repo only do JSON Schema checks. Should they do the full range of checks from https://github.com/openownership/lib-cove-bods ? That would include additional checks we have added there.

**Comment by odscjames** [comment]
> Is this a concern for:
> A) Just the samples in the "examples" dir - they appear in the docs, so they must be correct?
> B) "examples" but also the test data in "tests/data".

Note this is no longer relevant, I worked out a simple way to do both.

**Comment by odscjames** [comment]
Discussed Master/Tests/XFail with @ScatteredInk . We are going to leave for now and see how it goes with new branching stuff. I'll talk to others regularly about what a good size branch is, which should help with this.

**Comment by ScatteredInk** [comment]
We are happy with this for now.
