### ISSUE TITLE
Reviewing qualification statements

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#25]
In our original scoping (#7) we introduced the idea of a "qualification statement" described as follows:

> A beneficial ownership statement may also link to a **qualification statement** that expresses some additional information about the relationship described, such as qualifying that control rights can only be exercised under certain conditions. 

In the [draft model](http://beneficial-ownership-data-standard.readthedocs.io/en/latest/schema.html#qualificationstatement) each beneficial ownership statement can have an array of qualification statements, described as follows:

> A qualification statement can be used to record any additional information about this Beneficial Ownership Statement, including information about any reasons non-disclosure of information.

We currently allow these statements to have:

* **A type** - from a codelist of [ ‘non-disclosure’, ‘redaction’, ‘restrictions-on-control’ ]

and

* **A description** - into which free text, or semi-structured text from source systems, can be placed to describe the nature of the qualification.

As I work with this I'm left with a number of questions:

(1) Terminology: is qualification the right term?

(2) Modelling: should reasons for non-publication, and restrictions on the nature of ownership, be represented together in this same object?

(3) Cardinality: If we split out the concepts of non-publication from the concept of a qualification on an interest, do we need an array, or a separate object at all? Would ```qualification``` just become a property of [interest](http://beneficial-ownership-data-standard.readthedocs.io/en/latest/schema.html#interest), and non-disclosure a set of fields directly attached to the beneficial ownership statement? 

Feedback welcome.

**Comment by ScatteredInk** [comment]
My sense is that control limitations and reasons for non-disclosure are two separate domains and would be better off in different code lists/objects. If the schema were to expand in scope, then modelling restrictions on control in more depth would be one potential direction to go in. I'm in favour of more separation at this stage, so that we're not restricted later on.

On cardinality, I think an array is probably needed if qualification is a property of `interest`, to cover overlapping qualifications (and as a nudge to encourage separation of data on them).

**Comment by sebbacon** [comment]
As @ScatteredInk says, you might imagine restrictions on control might one day be modelled in more detail.

If the purpose at the moment is a bag to throw stuff that we're not yet sure we need but don't want to necessarily lose, is a more generic `annotation` *without* at type a more appropriate solution?

I fear we might bake in a vocabulary too early. If we think restrictions on control (for example) are really important, perhaps we should put more time into modelling them more accurately; if we just want a place to stick extra information, perhaps we should ditch the structure and just provide a free text field.  The model as discussed in the top of the issue smells a little like an unhappy compromise.

**Comment by timgdavies** [comment]
View from Gert on e-mail:

> Keep qualification statements in the model -  allows way to capture and utilize best information available that may not be 100% fact based.  Becomes critical when dealing with persons and entities in areas/countries where data is limited and/or not necessarily populated.  Also, helps with identifying “alias” establishment (through indirect means).  Can explain on the call.

**Comment by timgdavies** [comment]
I've been reviewing our initial conceptual model, which talked about having either 'BO statement' or 'Null statement' about interests. 

Based on this, I'm exploring a move to allow that the ```interestedParty``` in an entity could be identified by:

* A ```PersonStatement```
* An ```EntityStatement```
* or a ```NullParty``` (which forms part of the ```BeneficialOwnershipStatement```, and so is kept as a minimal object with just a type and description, sharing it's provenance information with the BO statement)

This removes the role of qualificationStatement in providing "any reasons non-disclosure of information."

Based on @sebbacon's comment above, I'm also exploring attaching an array of ```annotations``` to interest, so qualifications can be specified at the interest level (again, with their provenance information inherited from the BO statement they are contained within). 

This allows the separate qualificationStatement object to be removed, and gives us a conceptual model as below:

![image](https://cloud.githubusercontent.com/assets/342624/24324778/3b714986-1184-11e7-9c24-c0b5a7dcdd8e.png)

(although the diagram doesn't fully capture the fact that NullParty is not an independent type of statement, but rather a set of properties of BO statement...).

I'll post a branch of the docs that reflects this shortly.

**Comment by timgdavies** [comment]
Based on discussions in our working group call, qualification statements have now been replaced by [annotations on interests](http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#annotation) and [null parties](http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#nullparty)
