### ISSUE TITLE
Remove Markup from schema descriptions

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#264]
Inline markup like hyperlinks is currently included in some `description` fields in the schema. So far, markdown has been used. There's no guarantee or expectation that the schema JSON will be rendered by something that can parse markdown, and indeed on our own docs markdown is only (at the time of writing) displayed correctly in the tables that are rendered by the `jsonschema` widget, and not by Sphinx directly, resulting in bugs like:

![Screenshot at 2019-09-19 16-15-37](https://user-images.githubusercontent.com/466229/65252271-f47ba800-daf8-11e9-8d8d-6a23a426ba87.png)

The JSON descriptions should really be plaintext strings, as they don't have a media-type indicator of any kind to say how they should be treated otherwise.

I propose we remove all kinds of inline markup from the schema descriptions. If hyperlinks are needed, they can simply be written out, eg. "..based on the EC ISA Core Person Vocabulary (https://joinup.ec.europa.eu/solution/e-government-core-vocabularies) definitions."

If in agreement, the [style guide](https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md) should also be updated to note this.

Related: https://github.com/openownership/data-standard/issues/200

**Comment by timgdavies** [comment]
I lean towards allowing markdown links in plaintext where there is a reasonable chance the text will be rendered by a markdown parser (and would instead suggest we look at whether we can get docson support for markdown working here). 

My reasoning is that: 

* Markdown links are specifically designed to be human readable. The only different from how text would otherwise be written is the square brackets;
* If makes for more user friendly documentation if prose is not interrupted by long URLs;

However, happy for discussion on this.

**Comment by odscjames** [comment]
There is other issues on this and a different approach was taken before. I'll try to find links. Basically we had a problem where the schema markdown was shown in 2 widgets. One could handle the MarkDown and one could not. We decided the correct path here is to not have MarkDown in the schema and instead where we need to do nice display things, we do special things in the widget.

> where there is a reasonable chance the text will be rendered by a markdown parser 

Our feeling at the time was that we can't say there is a "reasonable chance the text will be rendered by a markdown parser ". A schema may be taken out of the standard and re-used in any number of tools, and the standard designers could easily have no knowledge of that. Therefore the schema files have to be a reusable as possible.


(Also I don't think this is related to #226, these are using Markdown in 2 different things and having recommonmark installed or not does not effect these display widgets.)

**Comment by timgdavies** [comment]
Ok. I've been convinced. I drop my preference for markdown in schema descriptions - and from call we've just had I think there is consensus we can remove markdown from the schema descriptions in a future update. 

Will update issue title accordingly.

**Comment by Blueskies00** [comment]
Implemented in BODS 0.3.
