### ISSUE TITLE
Audit scripts to see if they can be moved to bodskit

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#267]
There are some python scripts in the data-standard repo. We should check what these are, and if any are duplicated in bodskit consider removing them from data-standard, or if any should be moved to bodskit.

**Comment by siwhitehouse** [comment]
This has been transferred from the (internal) Open Data Services issue http://bods.opendataservices.coop/redmine/issues/507 that was reported by @rhiaro

**Comment by siwhitehouse** [comment]
I raised this at a round table meeting at Transparency International.

We discussed the process of entering data on the Companies House register. As I understood it this can either be done by a 'subscriber', who is someone directly attached to the business or it can be done on their behalf by a 'producer'. This means that up to three agents are recorded as having updated a record:

1. The 'subscriber', who is the person directly attached the business (a beneficial owner, company secretary etc.)
2. The 'producer', who is the person updating Companies House on their behalf
3. The "producer software" which is the platform or application that is used by the 'producer'
At the moment anyone can be a 'producer' - this is not limited by their location/nationality etc.. The example that was given was of someone in Moscow applying and being sent a 'producer' id/login. Turnaround by post being about one week. This may change and Richard is keen to see 'producers' becoming a regulated profession.

This gives us some additional agent roles that we might want to be able to record. 

There was a general response of "it's good to have fine-grained source data". From a regulatory/legal point of view this is required within banking (in general, not just wrt BODS). Companies House will have a record of who has updated specific data points within company records.

**Comment by ScatteredInk** [comment]
I wrote the scripts in /schema/tools/. To my knowledge they have never been used and I strongly suspect that it would be easier to just start again if we need fake data generated because:

- data-faker had a bug that stopped it handling nested schemas properly so I spent most of my time writing around that;
- the structure of BODS is now very different now;
- I had very little idea what I was doing.
