### ISSUE TITLE
Improved description and example of AnonymousEntity

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#269]
The [EntityType](http://standard.openownership.org/en/v0-2-0/schema/reference.html#entitytype) codelist contains `anonymousEntity` defined as:

> An entity that has been identified, but for which no identifying information is being published.

This is alongside `unknownEntity` which is defined as:

> An entity that has not been identified.

These are not a terribly clear descriptions. One user has asked:

> For example, if I know that a trust exists, then do you define it as a an anonymous entity if you know the trustee is, but you do not have the trust settlement documents disclosing the beneficiaries?

In this case, when a trust is known to exist, I would assume that an `entityType` or `arrangement` should be used. However, we could do with some worked examples for each of these entity type codes.

**Comment by kd-ods** [comment]
I agree that 'unknownEntity' is not tightly defined, but that might be for the best; it allows publishers use it meaningfully in their context. So, we should perhaps require that _publishers_ should offer a precise description of the cases where this code is used.

On this example:

> For example, if I know that a trust exists, then do you define it as a an anonymous entity if you know the trustee is, but you do not have the trust settlement documents disclosing the beneficiaries?

It sounds like this trust should be modelled as an entity with EntityType 'arrangement'; the known trustee would be represented by a personStatement linked to the trust with a 'trustee-of-trust' interest. The unknown beneficiaries would be represented by personStatements with personTypes 'unknownPerson'; these would be linked to the trust's entityStatement by 'beneficiary-of-trust' interests.

**Comment by kd-ods** [comment]
I suggest that we improve the description of [AnonymousEntity](https://github.com/openownership/data-standard/blob/master/schema/codelists/entityType.csv) to bring it into line with that for [AnonymousPerson](https://github.com/openownership/data-standard/blob/master/schema/codelists/personType.csv), then consider this issue closed.  

That means editing from:

> An entity that has been identified, but for which no identifying information is being published.

To:

> An entity that has been identified, but for which identifying information is being withheld. The reason for non-disclosure should be given in the accompanying `unspecifiedEntityDetails` field.

Also, it looks like the AnonymousPerson description should be updated at the same time to refer to the `unspecifiedPersonDetails` field rather than the missingInfoReason field.

**Comment by kd-ods** [comment]
@Blueskies00 - I've assigned this issue to you. It's a small update to the codelists that can be made in parallel to the work that @rhiaro is doing.

**Comment by kd-ods** [comment]
Assigning to @kathryn-ods - this ticket can be picked up as part of #480 .
