### ISSUE TITLE
Proposed new interestType: 'unknown-interest' 

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#276]
For cases where:

- There is a known interested party;
- There is an ooc statement between an entity and an interested party;
- There is known to be an interest between the subject and the interested party but no details of the interest are known.

**Comment by kd-ods** [comment]
Just noting that there's a need for this in Latvian.

**Comment by siwhitehouse** [comment]
The change to the schema is straightforward: an addition to the `interest-type` codelist. 

I think there is a need for documentation with examples. As I understand it, from the description, `unknown-interest` should not be used for an unknown interested party. My assumption is that it should be used for an anonymous interested party. 

Documentation that includes examples for a `registeredEntity`, `anonymousEntity` and `unknownEntity` would be useful here.

**Comment by ScatteredInk** [comment]
@kd-ods Can we just infer an unknown interest from the absence of an explicitly declared interest or do you think it is better to add this and have guidance that it is better to be explicit about the lack of information on the interest?

**Comment by kd-ods** [comment]
@ScatteredInk - So, practically, this is the difference between an ownership-or-control statement like:

```
{
  "statementType": "ownershipOrControlStatement"
  "interests": []
}
```

And:

```
{
  "statementType": "ownershipOrControlStatement"
  "interests": [
    {
    "type": "unknown-interest"
    }
  ]
}
```

I think we need to push for the latter, and provide guidance as you suggest. (In terms of why info is missing, an empty array is unhelpful whereas the latter option communicates 'the publisher has collected information here: no information is known about the interest''.)

I also think there are likely to be cases where - eg - the start date of an interest is known, but not its actual type. In which case we do need this 'unknown-interest' option.

**Comment by kd-ods** [comment]
Thinking through the types of unknown and missing information, we also need a 'redacted' interest type. This is where the publisher knows the type of an interest but will not publish that information. (It is comparable, in informational terms, to anonymous entities and individuals.)

**Comment by kd-ods** [comment]
@siwhitehouse - So my implementation proposal is that we add to the interest type codelist:

**unknownInterest**
The interestedParty is known to have an interest in the subject of this Ownership-or-control Statement, but the nature of the interest is unknown.

**redactedInterest**
The nature of this interest is known but cannot be published.

**Comment by siwhitehouse** [comment]
@kd-ods **unknownInterest** looks good to me. I think that we should use **unpublishedInterest** instead of redacted, as redacted indicates that something has been edited.

The changes that I'll make to the interestType codelist will be


| code | title | description |
|----|-----|------|
|unknownInterest|Unknown interest | The interestedParty is known to have an interest in the subject of this Ownership-or-control Statement, but the nature of the interest is unknown. |
| unpublishedInterest | Unpublished interest | The nature of this interest is known but is not published. |

**Comment by siwhitehouse** [comment]
[Merged](https://github.com/openownership/data-standard/pull/413/files)
