### ISSUE TITLE
Extension: entity.registrationStatus and details

### ISSUE THREAD

**Issue by myroslav** [openownership/data-standard#28]
We have the need to represent Organization registration status, and the current codelist of available statuses is (status description in Ukrainian):

 - _cancelled_: скасовано
 - _registered_: зареєстровано
 - _beingTerminated_: в стані припинення
 - _terminated_: припинено
 - _banckruptcyFiled_: порушено справу про банкрутство
 - _banckruptcyReorganization_: порушено справу про банкрутство (санація)
 - _invalidRegistraton_: зареєстровано, свідоцтво про державну реєстрацію недійсне

Is there dedicated field for Organization registration status in BODS already? Is codelist like the one above being discussed, and where? Are English language codes valid for Organization State, or you'd have different code in specific states (we attempted to provide the code as closely matching the description as possible)?

**EDIT**: Per discussion below, the proposed extension properties are:
 * `entity.registrationStatus` for the Organization registration status as free-text codelist, to be developed for/by every registry individually (one of such codelists is outlined above) and
 * `entity.registrationStatusDetails` for free-text verbose human-readable description of the Organization registration status (examples of such descriptions are outlined above)

**Comment by CountCulture** [comment]
I don't think it's possible to represent the organisation status as a code list -- our experience with OpenCorporates is that there is currently no code list which is universal, and some jurisdictions have 30-50 such statuses (others record as free text). In addition, by storing the status of the entity in beneficial ownership data, we're potentially denormalising it, with all the latency/synchronicity problems that brings. I would tend to think it is better to get the status from the canonical source, e.g. the company register

**Comment by myroslav** [comment]
At the moment company register is providing these statuses in numerical status id equivalent, that makes no sense, and verbose description as provided above.

My question was if there is more or less common statuses that we can utilize as replacement for numerical IDs. Our proposed statuses are above.

**Comment by timgdavies** [comment]
So - I take it from @CountCulture's response that on the question of whether there is a common codelist, the answer is probably no - so we would, at least in the short-term, be talking about a field without a set codelist. 

The separate question is whether we should specify an ```entity.status``` field in BODS at all.

Whilst it is currently possible to infer from ```entity.createdDate``` and ```entity.endDate``` whether an entity is fully active, that does not capture the nuance of status types you have enumerated. 

A couple of different options I can see:

* We add ```entity.description``` as a free-text field where individual implementations could put information such as company status.
* We allow ```entity.status``` as a free-text list;
* We just allow this as an extension such as ```entity.x_status``` and it is outside standard and it's documentation;
* This sort of information lives in qualification statements;

Views welcome...

**Comment by myroslav** [comment]
@timgdavies we're offering to have both:
 * `entity.status` as a free-text list (in our implementation the list has fixed set of possibilities mentioned in initial issue post).
 * `entity.statusDescription` (instead of `entity.description` mentioned above) with free-text field and values mentioned in initial issue post (in Ukrainian).

**Comment by jljordan42** [comment]
I'm new to the discussion, however I think the principle of not duplicating information in registries is a good one as per @CountCulture points above. Ideally entities will have permanent resolvable identifiers where attributes describing the entity status and other legal jurisdictionally contextual information is retrievable by human and machine. 

We are beginning work on a Canadian standard that will advocate for this approach as a way to use the distributed nature of the Internet protocol to effectively federate disparate data stores with legal entity data since we will never have a single registry for Canada given our constitutional structure.

**Comment by myroslav** [comment]
Regarding the deduplication/denormalization. There are following points:
 * often registry has no interface to retrieve historical data, thus ability to have multiple historical records from multiple dates representing entity status at these specific dates would be a plus for someone researching events that had happened with the entity.
 * Additionally in our case registry is not public (i.e. not accessible for retrieval on demand) thus we need to record information in "export" and note about date/time when the "export" happened from registry.

**Comment by timgdavies** [comment]
Based on the discussions above, and the proposal re: conformance in #29 I'm going to suggest that we don't add this to core. However, based on #29 we can document here in the tracker these extended properties.

I would suggest for clarity you use:

```entity.registrationStatus```

and

```entity.registrationStatusDetails```

If that works for you, then I'd suggest editing the initial post in this thread to describe how those properties are used, and renaming the issue to 'Extension: entity.registrationStatus and details'

**Comment by myroslav** [comment]
@timgdavies, thank you for detailed analysis. It is just the answer, I'd come for.

I'd corrected issue, and the title per suggestion. Feel free to update it further to become "ideal extension description" :)

**Comment by timgdavies** [comment]
That description looks great :) Thanks 👍

**Comment by timgdavies** [comment]
This extension proposal remains active even though the issue is now closed. If you make use of this extension, please post a note here so that the BODS team can consider future inclusion of this extension into the core standard.
