### ISSUE TITLE
Spanish translation: about/credits not showing translated text

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#286]
Linked to #237 

We previously had this issue with the Russian translation and I'm going to look back over that to replicate that fix. As I recall, we had to edit the markup in the translated file. Pinging @kd-ods in case she remembers this.

**Comment by kd-ods** [comment]
Simon - looking at the [about/credits.rst](https://github.com/openownership/data-standard/blob/spanish-translation/docs/about/credits.rst, I can't see any problems there.

(And looking at the [pull request](https://github.com/openownership/data-standard/pull/238/files) that fixed the issue way back when, the rst fix we made still holds.)

So I'm not sure what's going on.

**Comment by siwhitehouse** [comment]
Hi Kadie

So it looks as though adding an additional trailing underscore at the end of the links is the fix. It looks as though the credits.rst file has not been edited. Instead I must have edited the Russian translation directly in Transifex.

At this point I think we should definitely edit credits.rst. I'm not sure if it is worth us pushing all the strings up to the v0.2 project in Transifex (in case it overwrites resources).
