### ISSUE TITLE
Translation framework: duplication of translation of codelists text

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#299]
Reviewing a [PR on the Spanish translation](https://github.com/openownership/data-standard/pull/295) it became clear that there's an inefficiency in the way the strings are pulled out and represented as resources in Transifex (pot files?). Codelists are being translated twice. 

The schema-reference.po contains the all the codelist strings, as well as the codelist strings being represented in the codelists.po file.

The translation pipeline needs to be rationalised.

**Comment by jpmckinney** [comment]
The `csv-table` directive will yield the strings in the CSV for translation.

To get around this, OCDS uses at times the `csv-table-no-translate` directive from sphinxcontrib-opendataservices or the `codelisttable` directive from https://github.com/open-contracting/sphinxcontrib-opencontracting (the latter renders Markdown in codelist descriptions).

For those directives to work, OCDS needs to translate the codelist files that are referenced from its `codelists.md` page. It does that here: https://github.com/open-contracting/standard/blob/1.1-dev/docs/conf.py#L138
