### ISSUE TITLE
Precedents, components and learning from existing standards

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#3]
To inform the development of the Beneficial Ownership Data Standard, the OpenOwnership project commissioned [Jack Lord of Kraken Research](http://krakenresearch.com/) to conduct a rapid review of existing standards that might provide a direct basis, or relevant learning, for standard development.

A list of [32 different standards explored can be found here](https://airtable.com/shrNFcqITOf3hXHJ5) and the **[draft report for working group feedback is here](https://docs.google.com/document/d/1wCGSJdYTrFSxP3B8rM43qRtL9D6iyC3ghP5G6jzYeeE/edit)**. 

Feedback is invited on:

* Additional standards that should be considered as providing precedents or useful inputs for a beneficial ownership data standard;
* The overall findings of the paper.

**[Read and review the paper here](https://docs.google.com/document/d/1wCGSJdYTrFSxP3B8rM43qRtL9D6iyC3ghP5G6jzYeeE/edit)**.

**Comment by jpmckinney** [comment]
Great work! My feedback on overall findings:

* In my experience, "don't overwrite" is often a good principle for data standards to support. For instance, if a person changes name, the prior name shouldn't be overwritten and lost. Some standards support this by versioning an entire object (person), but that often makes using the data more difficult. Others take a more targeted, semantic approach (e.g. this person was known to have this address from this date to that date). It may be worthwhile to evaluate the standards against this principle.
* At some point, it may be helpful to create a crosswalk of classes/properties between the standards, to get a sense of detailed differences. At this point though, it may not be relevant as we are still focusing on broader differences.

**Comment by sebbacon** [comment]
Yes, great work!

The area which I feel is still quite loose is around the ontology of control.

I did [some work](https://medium.com/@opencorporates/understanding-corporate-networks-28c9a6f88c12#.1j2cs0wrs) on this a while ago; I didn't find any comprehensive such ontology. The best list I could come up with was (from the most specific, to the most vague):

> ..a [person]  can be said to control a subsidiary when:
> 
> - it holds majority voting shares (with a threshold of 50%)
> - it holds minority voting shares with a threshold of 20%
> - it holds minority voting shares which are in a larger block than any other shares
> - its directors and their family members together hold a majority of voting shares
> - it has had voting rights contractually signed over to it from other shareholders
> - it can control the membership of the board
> - it can direct activities in the subsidiary to its own benefit
> - it derives rights and obligations with respect of revenue and debt from the subsidiary
> - it has the potential to manipulate the subsidiary

There is tension between the desirability of capturing this kind of information, and the cognitive load required to record it.

**Comment by timgdavies** [comment]
Closing this issue as no further action is required on it (although it remains linked from a few places for useful background information).
