### ISSUE TITLE
jscc: Update test_json to use refactored jscc lib

### ISSUE THREAD

**Issue by Bjwebb** [openownership/data-standard#307]
Note: there's docs of the refactored code at https://jscc.readthedocs.io/en/latest/api/testing/checks.html

**Comment by Bjwebb** [comment]
After this is done, we should see what checks we're not running, and whether we should work on adding those.

**Comment by kd-ods** [comment]
@rhiaro - is this work still in progress?

**Comment by rhiaro** [comment]
Yes, we already use jscc lib where possible, and it doesn't look like there are any tests we're missing applicable to BODS, but I do want to take some more time to go over again and double check I didn't miss something.

**Comment by rhiaro** [comment]
As far as I can tell we're running all tests using jscc that we can.

**Comment by kd-ods** [comment]
Thanks, @rhiaro. Closing now.
