### ISSUE TITLE
jscc: Run codelist checks

### ISSUE THREAD

**Issue by Bjwebb** [openownership/data-standard#308]
We should refactor to use the new jscc first: https://github.com/openownership/data-standard/issues/306

Currently we run jscc checks that CSVs are correct CSVs, but we don't check that codelists CSVs correct codelists. This is because these tests fail at the moment. I think we should adopt these tests, and make the necessary changes to our codelists, rather than the tests.

**Comment by kd-ods** [comment]
@rhiaro - another part of the codelist puzzle to deal with as you tackle #341.

**Comment by kd-ods** [comment]
@kindly - did your work, adding tests_csv.py in PR #342 resolve this issue and #306 by any chance?

**Comment by rhiaro** [comment]
I think this is covered by #352 and #349 but let me know if I missed something?

**Comment by kd-ods** [comment]
@rhiaro - can you please close this if you and @Bjwebb are now happy with the codelist checks in the repo and with the supporting [documentation](https://github.com/openownership/bods-dev-handbook/blob/master/compiling_schema.md#codelists)? Thanks.
