### ISSUE TITLE
Finish tidying up branch renaming

### ISSUE THREAD

**Issue by odscjames** [openownership/data-standard#312]
We currently have both:
* v0-2-0
* 0.2.0

0.2.0 is what RTD serves but v0-2-0 is locked to protect it. 

Worse, the branches are not equal - 0.2.0 has 2 commits on them from Simon that are not on v0-2-0

And we have similar situations for other versions.

https://openownership.github.io/bods-dev-handbook/standard_releases.html says it should be v0-2-0

I understand we are now moving to no "v" and "." - that's fine, but we need to finish tidying this up:
* There should only be one branch for each version, otherwise people might get confused which one to work on. Delete the old one.
* That branch should both be served from RTD and protected in GitHub to prevent accidental writes, and require review for any changes.
* Update https://openownership.github.io/bods-dev-handbook/standard_releases.html as appropriate

**Comment by odscjames** [comment]
Assigning to @stevenday in first instance to check he agrees, and as admin to change the GitHub branch protection options.

**Comment by stevenday** [comment]
@odscjames - yes, thanks for the reminder. I was purposely leaving this change for some time, in case there were any issues with the renaming/moving that didn't immediately come to light, but I think we're able to do it now.

I'll take a look this afternoon. 

CC @siwhitehouse just to bring the rename to mind again - I'll move over the two commits @odscjames mentions in this instance.

**Comment by stevenday** [comment]
Ah, just re-reading, no commits need moving over - 0.2.0 is where new changes should be - thanks @siwhitehouse :)

**Comment by stevenday** [comment]
@odscjames - I've deleted the old branches, merged my open PR on the dev handbook so that it uses the new format (https://openownership.github.io/bods-dev-handbook/standard_releases.html) and I believe ReadTheDocs is already correctly serving from the new branches, so I think this can be closed.
