### ISSUE TITLE
Publishing information about market listings for PLCs

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#326]
BO registers need to publish a minimum set of information about each publicly listed company (PLC) in scope for declaration or disclosure. That includes standard company info plus the stock markets on which it is listed and the financial instruments listed there. This is how I suggest that that information is published in BODS.

Under entityStatement:

```
"publicListing": {
    "companyFilingsURLs": ["https://www.londonstockexchange.com/stock/AZN/astrazeneca-plc/analysis", "https://www.astrazeneca.com/investor-relations/stock-exchange-announcements.html"],
    "securitiesListings": [{
        "stockExchangeName": "London Stock Exchange",
        "stockExchangeJurisdiction": "GB",
        "marketIdentifierCode": "XLON",
        "securitiesListed": [{
            "ticker": "AZN",
            "isin": "GB0009895292"
        }]
    },
    {
        "stockExchangeName": "London Stock Exchange - MTF",
        "stockExchangeJurisdiction": "GB",
        "marketIdentifierCode": "XLOM",
        "securitiesListed": [{
            "ticker": "0A4J",
            "isin": "US0463531089"
        }]
    }]
}
```

Notes
-----

1. 'companyFilingsURLs' - URL or URLs where regulatory filings related to major holdings can be retrieved. URLs may point to pages maintained by regulatory bodies, stock exchanges or by the company itself.

2. 'securitiesListings' - A complete list of equity securities and the exchanges on which they are traded.

3. 'stockExchangeName' - The stock exchange or stock exchange segment where the company has listed securities.

4. I was tempted to include a url property within each securities listing (i.e. for each stock exchange). But (a) I'm not sure how useful it is to maintain the association between a filings url and the exchange, rather than putting it in the more general 'companyFilingsURLs' array and (b) with a segmented exchange like LSE there's only one page for a company, even if it has securities listed on different segments, so the url might be repeated.

5. There's also the issue of publishing some kind of flag on the entityStatement to indicate whether the entity has been exempted from standard BO disclosure on the basis that they are listed on a well-regulated exchange. I've not covered that here, since I doubt we want to plan it in isolation. There may be a whole set of 'entity features' under which 'elible-for-bo-disclosure-exemption' would be just one (boolean) property.

6. The ultimate question is probably: in general, is the scope and structure of the data above adequate to reach relevant information about a company's major holdings (with an automated process if possible)?

Hearing from those who are working with PLC data would be really useful.

**Comment by siwhitehouse** [comment]
This makes sense to me, but I come to it with no pre-existing understanding of PLC data.

I have a couple of comments.

Personally, I would rather see 'marketIdentifierCode' than 'MIC'.

With respect to 'companyFilingsURLs', in the example above I think that https://www.londonstockexchange.com/market-stock/0A4J/astrazeneca-plc/overview is the XLOM equivalent to the XLON https://www.londonstockexchange.com/stock/AZN/astrazeneca-plc/analysis. 

Considering that, I think we could convey more useful information to users by putting 'companyFilingsURLs' within "securitiesListings" and that the potential redundancy of publishing the same urls for multiple listings on a single exchange occurs are worth bearing. Possibly. It would be good to know how much it is likely to occur.

Can I clarify with you that in "securitiesListed" that "ticker" is used to identify the company on the exchange and then the "isin" is used to locate the particular security? So having both helps the user to distinguish the security - which might be listed on multiple exchanges worldwide - on the exchange.

**Comment by kd-ods** [comment]
> Personally, I would rather see 'marketIdentifierCode' than 'MIC'.

Yes. Let's not perpetuate protectionist initialisms. I agree. We can mention MIC in the property description.

> Considering that, I think we could convey more useful information to users by putting 'companyFilingsURLs' within "securitiesListings"

The thing is that the London Stock Exchange isn't representative of all exchanges and different regulatory frameworks require filing in different ways. Companies sometimes provide all their filings on their own website. Also, afaik, filings are sometimes published by the regulating bodies rather than the exchanges. (Plus, I'm not sure that the notion of a filing maps cleanly to a single type of security.) All in all, I'm not sure that practice in standardised enough for us to provide standardised structure for this.

> Can I clarify with you that in "securitiesListed" that "ticker" is used to identify the company on the exchange and then the "isin" is used to locate the particular security? So having both helps the user to distinguish the security - which might be listed on multiple exchanges worldwide - on the exchange.

Yes, that's what I understand.

**Comment by kd-ods** [comment]
> Personally, I would rather see 'marketIdentifierCode' than 'MIC'.

I've amended the initial proposal in line with @siwhitehouse's suggestion.

**Comment by kd-ods** [comment]
I've done some further thinking about the shape of the data in the initial proposal. I don't think it's helpful to allow multiple securities to be listed 'per' exchange. It could encourage the grouping of securities under an operating exchange and disregard market segments, whereas we should encourage publishers to collect info about exchange segments where that is relevant. (My understanding is that where trading in a particular type of security is subject to special regulatory requirements, a market segment may be dedicated to its trading and acquire its own MIC. So where a security IS traded in a particular market segment, that information is likely to give a clue as to the type of security and therefore its particular relevance to beneficial ownership. Therefore we need to collect info about market segment if that's applicable for a particular security.)

So, my updated proposal is to publish the data in long format and have an "operatingMarketIdentifierCode" as well as "marketIdentifierCode" field:

```
"publicListing": {
    "companyFilingsURLs": ["https://www.londonstockexchange.com/stock/AZN/astrazeneca-plc/analysis", "https://www.astrazeneca.com/investor-relations/stock-exchange-announcements.html"],
    "securitiesListings": [{
        "stockExchangeName": "London Stock Exchange",
        "stockExchangeJurisdiction": "GB",
        "operatingMarketIdentifierCode": "XLON",
        "marketIdentifierCode": "XLON",
        "security": {
            "ticker": "AZN",
            "isin": "GB0009895292"
        }
    },
    {
        "stockExchangeName": "London Stock Exchange",
        "stockExchangeJurisdiction": "GB",
        "operatingMarketIdentifierCode": "XLON",
        "marketIdentifierCode": "XLOM",
        "securitiesListed": {
            "ticker": "0A4J",
            "isin": "US0463531089"
        }
    }]
}
```

**Comment by kd-ods** [comment]
Updated proposal to allow for security identification buy IDs other than isins:

```
"publicListing": {
    "companyFilingsURLs": ["https://www.londonstockexchange.com/stock/AZN/astrazeneca-plc/analysis", "https://www.astrazeneca.com/investor-relations/stock-exchange-announcements.html"],
    "securitiesListings": [{
        "stockExchangeName": "London Stock Exchange",
        "stockExchangeJurisdiction": "GB",
        "operatingMarketIdentifierCode": "XLON",
        "marketIdentifierCode": "XLON",
        "security": {
            "ticker": "AZN",
            "idScheme": "isin",
            "id": "GB0009895292"
        }
    },
    {
        "stockExchangeName": "London Stock Exchange",
        "stockExchangeJurisdiction": "GB",
        "operatingMarketIdentifierCode": "XLON",
        "marketIdentifierCode": "XLOM",
        "security": {
            "ticker": "0A4J",
            "idScheme": "isin",
            "id": "US0463531089"
        }
    }]
}
```

7. `idScheme` should be a closed codelist comprising: isin, cusip, cins, figi.

**Comment by kd-ods** [comment]
An exchange between @ScatteredInk and me:

ScatteredInk
> I think this all looks good. My only question is over whether security should be an array, i.e. whether there is potential many-to-one relationship between the security and the list of potential securities identifiers. Intuitively I would say yes because FIGI, say, are trying to assign an identifier to everything. So there is an advantage to being able to crosswalk  the data regardless of the initial identifier chosen, I think?

kd-ods
> Yeah. It crossed my mind that a security should be allowed to have an array of identifiers. I came down on the side of simplicity of structure, with the idea that: (1) as things currently stand, authorities are unlikely to be collecting such detail anyway (i.e. collecting ANY security id will be a real achievement), (2) It will be easy enough to turn this into an array if there's demand for it and (3) - and this is a general reflection on open data and cross-walking IDs - ideally the collection of IDs for (in this case) a security would be held elsewhere, not as part of published BO data; enabling of that crosswalk has value beyond BO data. So that's my fairly weak 3-point rationale. What do you reckon?

ScatteredInk
> Yes, that makes sense to me - let's go with a single ID.

**Comment by kd-ods** [comment]
We need to handle the situation where the public listing details of a PLC are unknown (all this is known about the entity is that it IS a PLC). We [considered](https://github.com/openownership/data-standard/issues/339#issuecomment-804857417) whether we should use entity classification to do this. But putting a hasPublicListing field inside the publicListing block, with appropriate validation, is the better option.
