### ISSUE TITLE
Documentation: Representing trusts in BODS

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#328]
As noted in #186 and probably elsewhere, the way to model trusts currently in BODS 0.2 isn't obvious. We do have 4 interest/type values pertaining to trusts:

- settlor-of-trust
- trustee-of-trust
- protector-of-trust
- beneficiary-of-trust

... but when it comes to the representation of the trust itself nothing obvious is offered. We should document how to represent trusts in BODS 0.2 and update for future versions.

In BODS 0.2:

![image](https://user-images.githubusercontent.com/35495305/94558001-4bad7000-0257-11eb-8b30-10915b5547b8.png)

In addition to the above we would recommend that `annotations/0/description` has some standardised text which consistently identifies trust arrangements (plus any custom text). Publishers would detail their use of this standardised text and its meaning in their publication policies.

**Comment by kd-ods** [comment]
If we update the documentation for 0.4, then we should look at adding 'express trust' to the entitySubtype codelist. See #336

**Comment by StephenAbbott** [comment]
For consideration: our [Introduction to trusts briefing](https://www.openownership.org/en/publications/an-introduction-to-trusts/what-are-trusts/) sets out that the three sub-categories of trusts are:

1. Express trusts
2. Implied trusts
3. Statutory trusts

All three could be added to entitySubtype codelist.

**Comment by kd-ods** [comment]
Thanks, @StephenAbbott.

I wonder how much value would really be added to BO data by this more refined representation of trust types, especially given the complexity of trust law in any given jurisdiction, and the differences in trust law from jurisdiction to jurisdiction. The alternative is not to have even 'Express trust' but just to have 'Trust' in the entitySubtype general category codelist. Note that in BODS entitySubtype is actually structured as follows:

```
[...]
"entitySubtype":
 {
    "generalCategory": "Trust",
    "localTerm": "Express Trust"
  }
[...]
```

So 'localTerm' can be used to hold the local term for the relevant Trust type (if that info is collected and relevant).

@tymonk @oalannao - again, this is non-urgent. Do you think we can simply add 'Trust' to the entitySubtype general category list, or do we need to have that broken down into different types of Trust?

**Comment by tymonk** [comment]
I think it's best not to provide set categories. The trust category does not change anything about it's legal status, and as you can see from the [RSA trusts policy briefing](https://www.openownership.org/en/publications/an-introduction-to-trusts-in-south-africa/classification-of-trusts/) there are lots of different ways to categorise them. So I agree with your suggestion @kd-ods.

More interesting and relevant will be to describe which powers the different parties have (if known). e.g. if the trustee has discretionary powers, what specific powers the protector/enforcer can have (e.g. removing and appointing trustees), etc. Can we also accommodate a single actor having multiple trust roles?

**Comment by StephenAbbott** [comment]
Using `localTerm` for sub-categories makes sense to give more flexible options for trust register implementers with specific terminology.

@tymonk: you can see in the diagram at the top of this ticket how to model a single actor being - for example - the beneficiary and settlor of a trust

**Comment by tymonk** [comment]
Thanks @StephenAbbott. And is there a field in the ownership/control statement to annotate specific powers?

**Comment by StephenAbbott** [comment]
@tymonk Yes. The [annotations](https://standard.openownership.org/en/0.3.0/schema/reference.html?#annotation) fields can be used for this with a `statementPointerTarget` if someone needed to refer to a particular section of the statement

**Comment by kathryn-ods** [comment]
Having read through this and the accompanying documentation I think the actions needed are:
- update EntitySubtype codelist to include arrangement-trust
- update https://standard.openownership.org/en/latest/schema/concepts.html#ownership-or-control-through-arrangements or make a new page with guidance and examples specific to trusts (similar to the SOE page) 

@kd-ods have I understood that correctly? Is there anything else that needs to be decided or actioned on this?

With regards to different types of trust in different countries I agree with not putting in specific categories at this point. In the future if there was demand for representing specific types of trusts this could potentially be solved by using extensions like in OCDS https://standard.open-contracting.org/latest/en/guidance/map/extensions/

**Comment by kathryn-ods** [comment]
@kd-ods yes that would make sense! Would it be ok having some subtypes with a prefix and some without? We could also remove the 'stateBody' prefix from other subtypes for consistency. 

If we did that would it impact on validation? E.g when you input an entity statement with an entity type 'registeredEntity' and entity subtype of 'stateBody-governmentDepartment' the validation tool registers an error because the subtype isn't matching the type. How is that test working? Does it rely on that prefix?

**Comment by kathryn-ods** [comment]
@kd-ods I have found the [relevant test code]( https://github.com/openownership/lib-cove-bods/blob/master/libcovebods/tasks/checks.py#L622)

This section looks to me like it is just checking the prefix matches the entity type. Is it worth coming up with a different test or we could keep this test and have both 'arrangement-trust' and 'legalEntity-trust' as subtypes. 

It would be a bit more work but I would be in favour of scrapping the prefix and coming up with a new test. 
 
` entitySubtypeFirstBit = entitySubtype.split("-").pop(0)`
`                if entityType != entitySubtypeFirstBit:`

**Comment by tymonk** [comment]
Just wondering if sample forms we collect [here](https://www.notion.so/openownership/Forms-guidance-for-collecting-BO-data-on-trusts-6c42cdb673d44da39eed5825bde09a39) can also help inform this work?

**Comment by kathryn-ods** [comment]
Thanks @tymonk! 

Looking at these forms only Namibia is collecting information about the types of trust. 

RSA and UK don't have fields for this in their forms. 

I think this fits with the approach of us having a general 'trust' category for now and in the future we could consider how to support implementers who need to include more detail about types (possibly through extensions).

**Comment by kd-ods** [comment]
@kathryn-ods - I'm minded to review the format of the entitySubtype values and potentially remove the prefix entirely. We'd then need to document (in the schema descriptions) which entitySubtypes were valid for which entityTypes (for users of BODS) and we'd need to encode similar information in the repo (possibly as part of the codelist csv file, [as done here for OCDS](https://github.com/open-contracting/standard/blob/1.2-dev/schema/codelists/documentType.csv)) to support programmatic validation.

(In that OCDS csv file, each code in the codelist is only valid for certain Sections.)

**Comment by kathryn-ods** [comment]
I agree with that @kd-ods 

So we would have 

Type                                   | Subtype
stateBody                          | governmentDepartment
stateBody                          | stateAgency
stateBody                          | other
legalEntity, arrangement | trust

Is this change to the schema something that would be done by a dev or by an analyst?

**Comment by kd-ods** [comment]
> Is this change to the schema something that would be done by a dev or by an analyst?

We, as anlaysts, can take care of that. Though we'd need to check that implementation plan with a developer, since it impacts on validation.

**Comment by kathryn-ods** [comment]
Great! I'm just waiting on an update to the dev env and then I will try make that change on my end and make a pull request for it to be checked by a dev?

**Comment by kathryn-ods** [comment]
Should we also have an entity subtype for 'trust like arrangement'? @kd-ods

**Comment by kathryn-ods** [comment]
> Should we also have an entity subtype for 'trust like arrangement'? @kd-ods

discussed in a call and agreed to use trust as inclusive of trust-like arrangements with option to use 'local term' for extra detail

**Comment by Blueskies00** [comment]
Small change to be picked up in the docs work - in scenario 6, the relationship statement shows the interestType as "otherInterestOrControl" - the codelist entry is actually "otherInfluenceOrControl". This is also referred to in the Overview section.

**Comment by kathryn-ods** [comment]
Thanks for spotting this @Blueskies00! I have made this change in on the diagram-edits branch

**Comment by kd-ods** [comment]
This is the diagram edits PR: https://github.com/openownership/data-standard/pull/512

**Comment by kathryn-ods** [comment]
The schema changes related to this task are in ticket #518
