### ISSUE TITLE
Representing nominees in BODS

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#329]
As noted in #186 there is no obvious way to represent nominees and beneficial ownership via nominees. This is one recommended way and should be part of the documentation:

![image](https://user-images.githubusercontent.com/35495305/94561489-fe7fcd00-025b-11eb-9893-3c14e3033a6a.png)

Note that the type of interest linking the nominee and the BO of the shares will depend specifically on the nature of the nominee arrangement, so may not be as detailed above.

**Comment by siwhitehouse** [comment]
My understanding is that we want to represent the following:

- the Beneficial Owner has a shareholding in the declaring entity
- the Beneficial Owner has an arrangement with the Nominee whereby:
-- the Nominee is named publicly as the owner of that shareholding
-- the Nominee is granted the Beneficial Owner's voting-rights in the entity
-- the Beneficial Owner retains control over those voting-rights, in that they can instruct the Nominee how to vote
-- the Nominee may be granted other forms of influence or control belonging to the Beneficial Owner
-- the Beneficial Owner may retain control of those other mechanisms in that they can instruct the Nominee how to use them
-- the Beneficial Owner retains the rights to profit or income associated with the shareholding

Does that sound about right?

My reading of the diagram is that the shareholding - and all of the rights associated with it - are held within the nominee shareholding agreement. Resulting from the agreement, the Beneficial Owner retains the rights-to-profit-or-income, while the nominee holds an other-influence-or-control interest type. 

Implicit in this is that the shareholding interest described by the ownershipOrControlStatement between the agreement and the declaring entity contains within it the rights-to-profit-or-income and other-influence-or-control that flows from agreement to the Beneficial Owner and the Nominee respectively.

[I'm not sure if the diagram here is using other-influence-or-control as the preferred means of modelling all nominee shareholdings, or if it is being used to represent a generalised case.]

I *think* that we know/expect that a lot of jurisdictions will initially require the publication of shareholdings and directorships, but not necessarily voting rights or other forms of control.

I also think that in a lot of cases the nominee shareholding agreement will be made in a different jurisdiction to where the declaring entity is registered. In the jurisdiction where the agreement exists the company register may show the nominee as the beneficial owner and only in the jurisdiction where the entity is registered will we see the details of agreement, or even its very existence.

I think this raises a number of questions for us here. 

1. When and how is it acceptable to conflate a shareholding with the other rights that come with it?
2. Should the voting-rights (for example) granted to a Nominee be explicitly modelled? 
3. How does this impact on advice we give to implementors about which interest types they include in their disclosure regimes?
4. How do we represent the fact that the Nominee may declare themselves as the owner of the shares in some jurisdictions? 

My apologies for the rather scattergun approach here. I think there may be one or more of these questions that we could break out into their own issues, depending on people's responses.

**Comment by kd-ods** [comment]
> My apologies for the rather scattergun approach here. I think there may be one or more of these questions that we could break out into their own issues, depending on people's responses.

Rather than breaking things out/down, I think the answers to most of these questions can be found by panning out and taking a wider view of how we're modelling interests and what we're trying to achieve. I've got some ideas to run test with you. Better done in conversation.

**Comment by kd-ods** [comment]
With the [revision of Recommendation 24](https://www.fatf-gafi.org/publications/fatfrecommendations/documents/r24-statement-march-2022.html) of the FATF rules, there is now a clear requirement to [disclose](https://star.worldbank.org/blog/new-fatf-rules-beneficial-ownership-and-nominee-relationships-step-right-direction) nominee arrangements where they exist.

Updates to the FATF glossary might point to how we take things forwards in BODS. For example, we might retain the structure of the modelling at the start of the thread, but introduce 'nominee' and 'nominator' under interestTypes (and have 'nominee shareholding' and 'nominee directorship' as entitySubtypes of arrangements). However, any development on this front will depend on how work on #466 caches out.

**Comment by StephenAbbott** [comment]
[UK example to bear in mind](https://www.gov.uk/government/publications/economic-crime-and-corporate-transparency-bill-2022-factsheets/factsheet-beneficial-ownership?utm_source=pocket_saves#what-is-to-stop-a-person-recording-a-nominee-or-family-member-to-circumvent-the-requirements):

> ### 6. What is to stop a person recording a nominee or family member to circumvent the requirements?
> Under paragraph 19 of Schedule 1A to the Companies Act 2006 and under paragraph 19 of Schedule 2 to the Economic Crime (Transparency and Enforcement) Act 2022, a share held by a person as a nominee for another is to be treated as though the shares are held by the true owner (and not by the nominee).
> 
> And again, condition 4 of the above definitions effectively ‘looks through’ any nominee arrangement. If the nominee shareholder is simply taking instructions from a third party, that third party may be deemed to be ‘actually’ exercising significant influence or control.
> 
> Failure to declare a registrable beneficial owner is a criminal offence and if a court were to find that a person should have been registered, then the person and their company would be at risk of prosecution.
> 
> It is also an offence to deliver false information to Companies House and anyone who delivered, or caused to be delivered, such information would be at risk of prosecution.

**Comment by StephenAbbott** [comment]
FATF's Guidance on Beneficial Ownership of Legal Persons relating to Recommendation 24 was [released](https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Guidance-Beneficial-Ownership-Legal-Persons.html) in March 2023. Section 15 of the guidance sets out MECHANISMS FOR PREVENTING AND MITIGATING RISK OF THE MISUSE OF NOMINEE ARRANGEMENTS which we should bear in mind here

**Comment by kd-ods** [comment]
Thanks, @StephenAbbott. Looking at the Transparency and Licensing mitigations, I think the [current modelling suggestion](https://github.com/openownership/data-standard/issues/329#issuecomment-1273105667) is still likely to work.

The publishing use case that we should bear in mind is where nominee licensing regulations lead to the separation of information about nominee/nominator relationships from the information collected for BO registers. That is: I can imagine the licensing regulations leading to a nominee/nominator register (potentially non-public). And then the BO register only collecting nominee info. (Obviously there would be all kinds of complications re domestic vs non-domestic nominee/nominator arrangements, but I'm not sure that would deter regulators.) I'm not sure how likely this is - maybe @tymonk or @oalannao, you have some sense of where countries are going with this?

The current modelling suggestion would be able to handle that use case, though.

**Comment by tymonk** [comment]
@kd-ods I have been trying to get a sense of this but it's not yet clear. I find the nominee bit in the recommendation quite vague. The guidance clears it up a little but not a huge amount. FATF does not require central shareholder registers nor does it require (public) BO registers, but somehow this is information that jurisdictions will need to make public. So you could have compliance where there is only basic information publicly available about companies, directors (including which are nominees, but no who the nominators is) and information about nominee shareholders (but not the size of their share or who their nominators are, or information about any other shareholders).

Countries could obviously easily satisfy this by having a central, public shareholder + BO register. Increasingly thinking that's what we should be recommending as best practice. If there is a public CSD which gives legal effect, and that's extended to BO information that would be very rich source of information. Can maybe include in the sufficient detail work.

**Comment by kd-ods** [comment]
> Countries could obviously easily satisfy this by having a central, public shareholder + BO register. Increasingly thinking that's what we should be recommending as best practice

I think similarly @tymonk. If the sufficient detail work gets us to to where we can make a firm recommendation with robust rationale - brilliant.

**Comment by kd-ods** [comment]
Breaking this work for BODS 0.4 down, I think this might be the best approach:

**Aim**: schema updates and a documentation page which support implementers to represent nominee arrangements in their data.

- [ ] Create 3 - 5 text-based scenarios (like the [SOE scenarios](https://standard.openownership.org/en/0.3.0/schema/guidance/repr-state-owned-enterprises.html)) that we should be able to model with any schema changes.
- [ ] List the proposed changes to the schema (or codelists).
- [ ] Test that the proposed changes will support the modelling of the scenarios (iterate on these 3 steps until the proposed changes are adequate).
- [ ] Create json examples/tests based on one or two of the scenarios.
- [ ] Make schema and/or codelist changes, testing against the json examples.
- [ ] Write a new documentation page with the same format as the [SOE modelling guidance](https://standard.openownership.org/en/0.3.0/schema/guidance/repr-state-owned-enterprises.html). See this [guidance on image creation](https://github.com/openownership/bods-dev-handbook/blob/master/diagram_creation.md).
- [ ] Specify any non-schema-based validation checks that should be added to the Data Review Tool

**Comment by StephenAbbott** [comment]
Thanks @kd-ods. Agree that following the SOEs scenarios model would be very appropriate here to provide dedicated documentation for implementers

**Comment by Blueskies00** [comment]
I'm wondering if instead of the terms 'nominee' and 'nominator' we use 'agent' and 'principle'?

This would allow flexibility for other types of arrangement that may eventually be captured, and with the entity sub-type we can still capture the type of arrangement - in this case a nominee type.

**Comment by StephenAbbott** [comment]
Any views on this? ☝️ @tymonk

**Comment by tymonk** [comment]
@Blueskies00 what other types of arrangements do you have in mind?

Nominee and nominator are specifically defined by FATF which may mean people more readily understand what we're referring to. From the [glossary](https://www.fatf-gafi.org/en/pages/fatf-glossary.html#accordion-a13085a728-item-054eacaff0):

> Nominee is an individual or legal person instructed by another individual or legal person (“the nominator”) to act on their behalf in a certain capacity regarding a legal person.

This is arguably quite a flexible definition that covers many different types of agent/principal relationships, but not if e.g. involuntary/uninstructed, such as power of attorney in the event that somebody has lost their mental capacity.

Would be useful to discuss what other types of arrangements could be covered.

**Comment by Blueskies00** [comment]
Just making a note of this element of discussion (https://github.com/openownership/data-standard/issues/328#issuecomment-1772984901) as it will impact the naming of the entitySubtypes being proposed here.

**Comment by StephenAbbott** [comment]
Thanks @Blueskies00 for confirming that we're sticking with nominee and nominator for now.

Once work is completed on this issue, please add any relevant comments/notes to https://github.com/openownership/data-standard/issues/466 so we have them in mind when we come to work on that feature in future versions of BODS.

**Comment by kd-ods** [comment]
@Blueskies00, @kathryn-ods  - thinking about how this work, and [representing trusts](https://github.com/openownership/data-standard/issues/328) interact. I think it's possible that Trustees nominate another legal person to act as trustee. If that's the case, maybe we need a further arrangement entitySubtype, 'nominee trusteeship'?

**Comment by kathryn-ods** [comment]
yeah seems to be a thing for charitable trusts https://www.gov.uk/government/publications/appointing-nominees-and-custodians-cc42/appointing-nominees-and-custodians-guidance-under-s194-of-the-trustee-act-2000-cc42#definitions-of-nominee-and-custodian

**Comment by tymonk** [comment]
To add, I have also read about beneficiaries and settlors being nominees, albeit in cases of wrong-doing.

**Comment by kathryn-ods** [comment]
Yeah we have also been discussing people acting as nominees for minors who are party to a trust in RSA which could apply to various roles. Maybe 'nominee-trust' or 'nominee-other' would work. Or would it be possible to have one entity subtype for 'nominee' and specify the specific type elsewhere (this is kind of what we landed on for trusts)

**Comment by kd-ods** [comment]
@kathryn-ods (@Blueskies00 ) I think this is where we need to have a discussion on modelling, since I can envisage a proliferation of 'nominee XXXX'-style codes as entitySubtypes of arrangements. We should consider the pros and cons of a simple 'nomination' entitySubtype, I think. Best worked out in conversation. With diagrams :-)

**Comment by kathryn-ods** [comment]
Thanks @kd-ods - I've suggested a time for next week when @Blueskies00 is back :)

**Comment by Blueskies00** [comment]
Non-schema validation tests required for the data review tool:

- If entitySubtypeCategory == nomination, then entityType must be arrangement, else error.
  -  Error message: "When the entitySubtypeCategory is 'nomination' then the entityType must be 'arrangement'."
- If entitySubtypeCategory == nomination, then where the entity record is the subject of a relationship record the interestType must be nominator OR nominee, else error.
  -  Error message: "Only interestType 'nominator' or 'nominee' should be used when the subject entity has the entitySubtypeCategory  'nomination'."

**Comment by kathryn-ods** [comment]
Is it possible for a nominee arrangement to have more than 2 parties?

This website mentions a case where multiple shareholders are grouped under one nominee https://www.informdirect.co.uk/shares/nominee-shareholder/ 

The FATF glossary also says 'Nominator is an individual (or group of individuals) or legal person...' 

If yes - we may want to include this as an example diagram. Would you just have one entity statement with multiple nominators or an individual entity statement for each nominator?

If no - we should include this limitation in the test schema.

**Comment by kd-ods** [comment]
> Would you just have one entity statement with multiple nominators or an individual entity statement for each nominator?

Good question. I don't think there's a simple answer. It would really depend on how the arrangement was set up between the group of people and the nominee. If they are acting as a group and - as a group - have a single contract or arrangement with the nominee, then the group itself could be represented by an entity statement (type: arrangement). But if they have individual agreements with the nominee then the modelling would (maybe) need to represent that.

**Comment by kathryn-ods** [comment]
Thanks Kadie - I think in that case it would make sense to have a limit of one nominee and one nominator per arrangement. 

Maybe it would be worth having an example of the arrangement representing a group of shareholders in the future but prob enough of an edge case we can leave that for now.

**Comment by kd-ods** [comment]
> it would make sense to have a limit of one nominee and one nominator per arrangement.

I don't think it makes sense to set a formal limit (i.e. as a requirement in BODS). There are cases where joint shareholding may be executed via a nominee so you'd have a couple of nominators and a nominee.

I do agree that these are edge cases though. So we don't need to cover them in a scenario (yet).

**Comment by kathryn-ods** [comment]
cool we can park that thought for now then :) PR for the documentation is https://github.com/openownership/data-standard/pull/514

**Comment by StephenAbbott** [comment]
Plus one from me for no formal limit and parking this thought for now. 

We have forthcoming publications about investment funds and public listed companies which may help shed light on these types of scenarios to inform future documentation about edge cases.
