### ISSUE TITLE
Representing declarations in BODS - a proposal (alternative to #317)

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#334]
Information about beneficial ownership will most often be declared to state bodies and published from Business registers or similar. Beneficial ownership declarations are made via online or paper forms and are a familiar concept.

Identifying and working with declarations in BODS 0.2 is hard. The concept does not map to any object or data structure in the standard. Isolating a single declaration for a given entity or person in a dataset (or even finding out how many declarations are contained in a dataset) involves making assumptions, relatively complex code, a lot of graph traversal or a mix of all those things.

By making the concept of a declaration more visible in the standard, we can simplify some of this work. It is also likely to help with designing publication systems which report change over time (which was the main motivation of the suggestion in #317).

There are 3 elements to this proposal:

**Element 1**

We should be advising state registers to use the `source` property to group statements into declarations. (What Tim's called a 'disclosure' in #317, I'd call a declaration.)

```
"source": {
    "type": "selfDeclaration",
    "description": "confirmation statement number 0004955938537",
    "assertedBy": [
        {
            "name": "ArtTech Group Ltd."
        }
    ]
}
```

OR we could (and possibly should) make this explicit by adding a `declarationId` property to the Source object.

**Element 2**

We should be advising publishers to ensure that each declaration is an isolated 'component' and does not connect to, or draw from, information from other declarations or sources. In the following example, if Optima UAB and TechSys Inc. are declaring to the same authority, we would expect to see (at least*) two EntityStatements for TechSys Inc.

![image](https://user-images.githubusercontent.com/35495305/104622938-c6c15780-5689-11eb-8d96-0eb3709629fe.png)

\* TechSys might appear in other declarations as an intermediary.

**Element 3**

In the BODS schema, we should add an is-declaring-subject type flag to EntityStatements and PersonStatements. At the moment, declaring entities can only be identified if one of the agent names in the source.assertedBy array matches the Entity name (or one of the Person names). (Or they could be identified as the root of components in a directed graph. Complex.)

**Comment by stevenday** [comment]
I think it would be helpful to list the user needs that the concept of a 'disclosure/declaration' serves, on both the publisher and consumer sides, because it fundamentally feels like a bit of a compromise to me. We're asking for more data, more identifiers and requiring more of data collection systems that want to publish BODS, so we need to be clear why the benefits outweigh that extra work. Why do we need to identify declarations (vs owners), or count them?

**Comment by kd-ods** [comment]
As a researcher/analyst/data user, I want to know how many entities (or people) are reporting their beneficial ownership in a given dataset so that I can understand its scope.

As a data journalist, I want to be certain about the 'boundaries' of the declaration of company X, so that I can have a clear picture of how they declared that their beneficial ownership changed over time.

As a Business Register Analyst, I want to know how to represent a correction to a recently published declaration (which includes both voiding and replacing statements), so that I can specify what our developers need to do.

As a Business Register Analyst, I want to know how to represent the new declaration of a company which is declaring it no longer has BOs, so that I can specify what our developers need to do.

> We're asking for more data, more identifiers and requiring more of data collection systems that want to publish BODS.

That's kind of true. But I hope these features simply enable publishing of data that business registers will already have. The information about where declarations start and end is needed by users and is currently implicit (at best) in datasets.

**Comment by kd-ods** [comment]
... plus, see the publisher questions in https://github.com/openownership/data-standard/issues/9#issuecomment-613957978. Having the kind of set-up I describe here would make modelling decisions easier.

**Comment by kathryn-ods** [comment]
Closing as 0.4 includes representing declarations
