### ISSUE TITLE
Proposed interest type: enjoyment of assets and/or usufruct

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#344]
Individuals can extract benefit from a legal entity by using assets owned and controlled that entity.

This is recognised in BOT regimes in a couple of ways:

- One draft law that we have seen talks about use and enjoyment.
- Other systems relate this to the concept of [usufruct](https://en.wikipedia.org/wiki/Usufruct), which is the "the right to use and enjoy the proceeds of another’s property for a given term" ([ref](https://rebeccajowers.com/2017/12/26/what-is-usufructo/)). Usufruct is explicitly declarable under some BOT regimes, and I think implicitly declarable under others.

So I think we do want to add something around enjoyment and use - but am unsure at this stage whether we want to unbundle 'use and enjoyment' from 'use and right to profit', or if there is a substantive difference at all.

**Comment by kd-ods** [comment]
Unbundling seems like the right approach to me since that reflects common legal distinctions wrt ownership. I also wonder whether we need to highlight the asset-centredness of these types of interest in the way we name them. Since assets are hidden by the data model, it might help with future integration with asset-centred data. Practically, this might mean naming them sthg like:

- assets: enjoyment and use
- assets: right to derive profit

This will help clarify the difference between the latter interest and the existing 'rights-to-profit-or-income' code.

**Comment by siwhitehouse** [comment]
I agree with the unbundling. 

Currently we have ```rights-to-profit-or-income``` in the schema and we are proposing to add _assets: right to derive profit_ 

These interestTypes should cover two distinct situations

1. ```rightsToProfitOrIncome```
  Where somebody has the right to derive profit or income from the entity

2. assets: right to derive profit
  Where somebody has the right to derive profit or income from an asset owned by the entity

In which case it makes sense for them to be distinguished only by asset, making the code ```rightToProfitOrIncomeFromAssets```

My proposal to implement these two new codes is below

| Code | Title | Description |
| ------ | ------- |  ---------------|
| enjoymentAndUseOfAssets | Enjoyment and use of assets | A controlling interest in an asset owned by an entity. Defined as the right to make use of assets belonging to an entity.|
| rightToProfitOrIncomeFromAssets | Right to profit or income from assets | An economic interest in an asset owned by an entity. Defined as the right to derive profits and/or income from assets belonging to an entity. |

Note that the definition for ```rightToProfitOrIncomeFromAssets``` differs significantly from ```rightsToProfitOrIncome``` and I'll raise a separate issue to suggest a change to its definition.

**Comment by siwhitehouse** [comment]
This has been implemented and pushed up as a [commit ](https://github.com/openownership/data-standard/commit/5b5d98cccd0d7fe9e9d4593c49d3bc0b76a0308a) on the [simon-369-interest-types](https://github.com/openownership/data-standard/compare/simon-369-interest-types) branch.

As this is one of a number of changes to the interestTypes codelist I will make a PR when the remaining changes have been committed to the branch.

See https://github.com/openownership/data-standard/issues/369 for the feature ticket describing the full list of potential changes to the codelist.

**Comment by siwhitehouse** [comment]
[Merged](https://github.com/openownership/data-standard/pull/413/files)
