### ISSUE TITLE
Feature: Represent market listing information for companies (PLCs)

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#359]
_[This ticket helps track progress towards developing a particular feature in the Beneficial Ownership Data Standard (BODS) where changes or revisions to the standard may be required. It should be placed on the [BODS Feature Tracker](https://github.com/openownership/data-standard/projects/4), under the relevant status column._

_See [Feature development in BODS](https://openownership.github.io/bods-dev-handbook/feature_development.html) in the Handbook._

_The information in this first post on the thread should be updated as necessary so that it holds up-to-date information. Comments on this ticket can be used to help track high-level work towards this feature or to refine this set of information.]_

### Feature background

**What user needs are met by introducing or developing this feature in BODS?** _[Summarise these needs. Link to user stories, reports, blogs and other evidence where possible. Or add user stories here directly.]_

The [Open Ownership Principles](https://www.openownership.org/principles/comprehensive-coverage/) suggest that details of PLC intermediaries should be disclosed in beneficial ownership declarations; also, that where PLCs are exempt from disclosing their beneficial owners, they should declare the company's identity and the basis of the exemption. 

Publicly listed companies (PLCs) are often exempt from full beneficial ownership disclosure (on the basis that information about their ownership and control should already be public). Even if this information can be discovered from public filings and documents, there is a need to unambiguously identify PLCs in BODS data and facilitate the discovery and linking of related datasets. 

Open Ownership released a technical note, *[Beneficial Ownership and Listed Companies](https://www.openownership.org/uploads/technical-note-beneficial-ownership-and-listed-companies.pdf)* with advice on when and how to require disclosure of details of a publicly listed company, for the sake of beneficial ownership transparency. The Appendix of the document sets out what information should be published about PLCS.

**What impact would not meeting these needs have?**
If BODS could not hold identifying and useful information about PLCs:

i) The information would be collected and published in non-standard ways
ii) Insufficient information might be collected for the purposes of identifying PLCs
iii) Complete pictures of beneficial ownership would be more difficult to uncover in particular cases.

**How important is it to meet the above needs?**

Very. Publishing details of public companies' listings is an integral part of transparency of beneficial ownership, as reflected by the Open Ownership guidance linked to above. 

**How urgent is it to meet the above needs?**

Very. The Extractives Industry Transparency Initiative requires the collecting and publishing of PLC information under the [beneficial ownership requirement](https://eiti.org/document/eiti-standard-2019#r2-5) of their standard. Countries such as Armenia are already [collecting that information](https://www.e-register.am/en/companies/1340197/declaration/c51e08a7-6fdb-4ab7-a55c-c74a68a8f54c) and have no way of publishing it in a standardised way in BODS.

**Are there any obvious problems, dependencies or challenges that any proposal to develop this feature would need to address?**

The general challenge of this feature is developing BODS for interoperability with market data, when there are open questions about the format and any standardisation of market data. More research on that side of things would be valuable. 

### Feature work tracking

Progress: 

- Proposal ticket: https://github.com/openownership/data-standard/issues/326

- Schema changes and examples added: https://github.com/openownership/data-standard/commit/610ee1615012df5096bfc6fb00c1074c6573ea11

- Proposed updates to documentation - #388

**Comment by Blueskies00** [comment]
Implemented in BODS v0.3.
