### ISSUE TITLE
Modelling Issue: Address standards

### ISSUE THREAD

**Issue by jljordan42** [openownership/data-standard#36]
Addresses ... difficult for sure.

There are well established postal standards in North America at least from Canada Post and US Postal service. (e.g. https://www.canadapost.ca/tools/pg/manual/PGaddress-e.asp)

As well as implementation examples: Here is a Province of British Columbia example
https://github.com/bcgov/api-specs/blob/master/geocoder/singleLineAddressFormat.md

Also .. https://schema.org/PostalAddress might be useful 

I raise this as addresses are notoriously digitally unfriendly and would be nice if we don't introduce further entropy into this particular data world.

**Comment by timgdavies** [comment]
See #18  - where we've proposed semi-structured addresses for data exchange (just separating country and postal code - and trusting good parsers) and leaving it to other implementing systems to manage the best data capture approach based on their local needs.
