### ISSUE TITLE
Feature: Represent State-Owned Enterprises (SOEs)

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#360]
_[This ticket helps track progress towards developing a particular feature in the Beneficial Ownership Data Standard (BODS) where changes or revisions to the standard may be required. It should be placed on the [BODS Feature Tracker](https://github.com/openownership/data-standard/projects/4), under the relevant status column._

_See [Feature development in BODS](https://openownership.github.io/bods-dev-handbook/feature_development.html) in the Handbook._

_The information in this first post on the thread should be updated as necessary so that it holds up-to-date information. Comments on this ticket can be used to help track high-level work towards this feature or to refine this set of information.]_

### Feature background

**What user needs are met by introducing or developing this feature in BODS?** _[Summarise these needs. Link to user stories, reports, blogs and other evidence where possible. Or add user stories here directly.]_

People publishing and interpreting BODS data should be able to:

- Model SOEs in a way that allows for accurate identification and useful analysis. This should include modelling the jurisdiction and, where appropriate, the state body that controls the entity.
- Identify a declaring or an intermediary entity as an SOE, either directly (within a declaration) or by aggregating declarations.
- Declare that an entity is exempt from declaration because it is an SOE, while retaining as much information about the controlling jurisdiction as is available.
- Potentially, describe control within SOEs with appropriate interest types.

The [Open Ownership Principles](https://www.openownership.org/principles/comprehensive-coverage/) suggest that disclosure regimes include state-owned-enterprises (see [related blogpost from January 2021](https://www.openownership.org/blogs/state-owned-enterprises-a-new-frontier/)). And Open Ownership has published [recommendations](https://www.openownership.org/blogs/state-owned-enterprises-and-beneficial-ownership-disclosures) around collecting and publishing information about state-owned enterprises. As a minimum BODS should enable publishers to implement those recommendations.

In 2021, Open Ownership launched the [Opening Extractives programme](https://www.openownership.org/news/collective-action-on-extractive-sector-corruption-can-turn-the-tide/), a five-year joint partnership with the Extractives Industries Transparency Initiative (EITI). [Requirement 2.6 of the EITI Standard](https://eiti.org/document/eiti-standard-2019#r2-6) outlines disclosure of ownership requirements related to SOEs operating in the oil, gas and mining sector. Better modelling of the ownership of SOEs is crucial so that members of national EITI multi-stakeholder groups can judge whether or not countries and extractives companies are fulfilling this requirement of the EITI Standard.

**What impact would not meeting these needs have?**

It is not currently possible to represent state-ownership and control in a standard way within BODS 0.2. Therefore accurate identification of SOEs to enable useful analysis is not possible. Not addressing this is likely to mean that publishers represent SOEs in diverse and non-standardised ways, making data sourced from different jurisdictions more difficult to analyse in aggregate.

**How important is it to meet the above needs?**

Very. Disclosure of state interests is a particular requirement in the field of mining and extractives transparency, which is not currently met in BODS 0.2. 

**How urgent is it to meet the above needs?**

Very. Countries signed up to the EITI are already publishing BO data.

**Are there any obvious problems, dependencies or challenges that any proposal to develop this feature would need to address?**

1. We know that the BODS entity classification structure needs to be revisited. So any proposal to address representation of state-ownership or control should be aligned with developments and thoughts expressed in:

https://github.com/openownership/data-standard/issues/336
https://github.com/openownership/data-standard/issues/339

2. There is no fixed definition of 'State-owned enterprise'. BODS should not assume or rely upon any particular definition.

### Feature work tracking

_[Link to proposals, bugs and issues in the repository to help track work on this feature]_

First implementation proposal: #363

**Comment by StephenAbbott** [comment]
Worth us noting here for the record that being able to better represent state-owned enterprises in BODS would help avoid issues we have seen with data being submitted to the Global Open Ownership Register where data submitters have been trying to hack their way to a solution in the absence of specific guidance: https://github.com/openownership/register/issues/27

**Comment by kd-ods** [comment]
A couple of useful resources which might inform this work. From @StephenAbbott:

> - [Online Mapping Tool of State-owned Enterprises and their subsidiaries](https://www.oecd.org/dev/online-mapping-tool-state-owned-enterprises-their-subsidiaries.htm): "pilot of this tool maps 10 state-owned enterprises (SOEs) and their subsidiaries from Colombia, People’s Republic of China, Kazakhstan, Indonesia, Brazil, South Africa, Thailand and Republic of the Congo" 
> - [Online Stocktake of Company Reporting Requirements in Key Trading Hubs](https://www.oecd.org/dev/company-reporting-requirements-different-trading-hubs-stocktake.htm): focused on PLCs, this project aims to "take stock of current transparency, reporting and anti-corruption requirements across key global trading hubs".

**Comment by StephenAbbott** [comment]
👏 👏 👏 👏 👏  @kd-ods @ScatteredInk
