### ISSUE TITLE
Implementation proposal: Represent State-Owned Enterprises (SOEs) no.1

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#363]
_[This ticket proposes a particular approach to implementing a feature in BODS. In most cases, a proposal should be made only after the problem it tries to solve is described in a 'feature' ticket._

_See [Feature development in BODS](https://openownership.github.io/bods-dev-handbook/feature_development.html) in the Handbook._

_Comments on this ticket can be used to question, refine and develop this implementation proposal. Interactions and work on this ticket represent a collaborative process. Proposals may be paused, withdrawn, or developed into draft implementation plans. Update the 'Proposal status' as thinking progresses on this thread. Highlight changes or updates to the proposal within thread comments, with a clear 'Updated proposal' heading.]_

## Implementation proposal for: Represent State-Owned Enterprises (SOEs)

**Feature ticket link** #360

Implementation proposal status: **ACTIVE** (Not: paused | withdrawn | being implemented)

### Initial proposal

_[Broadly, what changes do you propose are made to the BODS schema or documentation in order to develop the feature in question.]_

**Overview**

Given the needs and constraints set out in the feature ticket, #360, this proposal is that: states and state bodies are represented by types of Entity Statement. They can then be connected in the standard way via Ownership-or-control Statements with other entities. Companies and other entities will not be flagged (within their statements) as being ‘state-owned’. Rather, their connections within the data to states or state bodies will be evident.

This allows BODS to (1) remain un-tied to any particular definition of ‘state-owned enterprise’, and (2) represent the gamut of ways in which states, directly or indirectly, own and control enterprises.

**Proposed changes to the schema**

1) To the [entityType codelist](http://standard.openownership.org/en/0.2.0/schema/reference.html#entitytype) we’d add ‘state’ and ‘stateBody’ types.

2) In [Entity Statement](http://standard.openownership.org/en/0.2.0/schema/reference.html#entitystatement), add a new `entitySubtype` property which takes an object with `general` (enum) and `local` (string) properties. The value of `general` would be taken from a stateBodyType codelist:

- Government department
- State Agency
- Other

The value of `local` would provide the locally-used descriptor for the state body type.

3) In Entity Statement, change 'Incorporated In Jurisdiction' property to just 'Jurisdiction'. (And change the description to 'The jurisdiction in which this entity was registered (for legal and registered entities, and arrangements). Or the state's jurisdiction (for states and state bodies).')

4) Add a 'formedByStatute' property & object to the top of the Entity Statement. The object would have `name` and `date` properties.

**Example usage**

```
{
  "statementType": "entityStatement",
  "name": "Valtioneuvoston kanslia",
  "entityType": "stateBody",
  "entitySubtype": {
    "general": "governmentDepartment",
    "local": "ministeriö"
  },
  “jurisdiction”: {
    “name”: “Finland”,
      “code”: “nl”
  }

[...]

}
```

```
{
  "statementType": "entityStatement",
  "name": "National Pension Scheme Authority (NAPSA)",
  "entityType": "stateBody",
  "entitySubtype": {
    "general": "stateAgency"
  },
  "jurisdiction": {
    "name": "Zambia",
    "code": "zm"
  },
  "formedByStatute": {
    "name": "National Pension Scheme Act no. 40",
    "date": "1996"
  }

[...]

}
```

**Implications for modelling**

We’ve set out how [particular scenarios](https://docs.google.com/document/d/1-Cqy9OO-_84hxCQAen4kV4ZFiwynTYLKw6m0CayHDrY/edit#heading=h.xia8q848ii00) would be modelled if this proposal were accepted. Comments can be added to that document (or to this ticket where that makes more sense).

**Comment by kd-ods** [comment]
@ScatteredInk - just letting you know that the SOE proposal is now in the repo.

**Comment by ScatteredInk** [comment]
@kd-ods Thanks, this looks good to me. My only slight hesitation is with `general` as a field name: it wasn't entirely obvious to me what this meant at first, but I also can't think of a great alternative.

**Comment by StephenAbbott** [comment]
@kd-ods Took me a while to grasp the general / local field names too when reading over this. Would `category` work as a replacements for the `general` field name? And should `local` be more descriptive like `locallyKnownAs`?

**Comment by kd-ods** [comment]
@ScatteredInk @StephenAbbott ...Would this work:

- entitySubtype.generalCategory
- entitySubtype.localTerm

?

**Comment by StephenAbbott** [comment]
Thumbs up from both @ScatteredInk and I to the proposal above, @kd-ods 👍

**Comment by kd-ods** [comment]
**Additional proposed change to the schema**

5. Amend the description of 'legalEntity' in the [entityType](http://standard.openownership.org/en/0.2.0/schema/reference.html#entitytype) codelist. It currently reads 'A body with distinct legal personality, such as a government department or international institution, but which is not otherwise uniquely identified in some official register.' It can be amended to read: 'A body with distinct legal personality, such as an international institution, but which is not otherwise uniquely identified in some official register.'

**Comment by kd-ods** [comment]
Additional thought on proposed change (2) ("In Entity Statement, add a new entitySubtype property..."). In defining the state body subtypes 'government department' and 'state agency', we *could* define these as central state bodies (and add entries for subnational/sub-federal levels of government). I think, however, that we should not, on the basis that: (a) most state-owned enterprises will be controlled by central government, and (b) on the rare occasion that they are controlled at a more local level, that should be evident from use of the ISO 3166-2 code in the Jurisdiction field.

If that rationale doesn't hold water, let me know.

**Comment by kd-ods** [comment]
I'm not sure how an 'unknown SOE' would appear in data @Convincible. I can _imagine_ a declaration system where a mining company - for example - ticks a box on declaration form stating 'Exempt from disclosing beneficial owners on the basis of being majority owned by a State-owned enterprise'. In this case we have minimal information about the mining company and its links to another enterprise (which meets some local definition of 'state-owned').

The key thing is that there is no standard definition of what a state-owned enterprise is. So, in BODS, what we do is allow representation of the links between companies and the state, so that users of the data can employ whatever definition fits their context. No individual company in BODS is ever directly flagged as 'a state-owned enterprise'.

**Comment by Convincible** [comment]
@kd-ods is it feasible we will want to draw a diagram including an SOE that is in some sense unknown? If so, I need to work out how to visualise that!

If this is feasible, would the "unknown-ness" be 1, 2, both or neither (above)?

**Comment by kd-ods** [comment]
@Convincible - I think I'd need to know more about the context of the diagram/icon: what it's trying to communicate. DM me and we can look at it.

**Comment by kd-ods** [comment]
Closed with the above merges.
