### ISSUE TITLE
Schema - statementType - minor typos in description

### ISSUE THREAD

**Issue by odscjames** [openownership/data-standard#381]
Is

    " This should always be 'entityStatement."

Remove space at start and add quote

    "This should always be 'entityStatement'."

Also, the person statement one is missing a quote and the ownershipOrControlStatement one uses a different style of quotes.

(did say it was minor)

Think this will involve a checkin with translations tho?

**Comment by kd-ods** [comment]
> Think this will involve a checkin with translations tho?

I don't think so. (We're merging edits like this into the main branch. Then, later on, we'll take a release branch off the main branch and translate everything at once for the release.) We'd only need to consider translation implications if we were proposing to apply this as a patch to v0.2 or something. 

I'm going to add this issue to the 0.3 backlog.

**Comment by odscjames** [comment]
> Think this will involve a checkin with translations tho?

Should have been clearer, sorry. I think the foreign translation strings use the English string as a key, so if we change anything - even a full stop - the I18N tool will suddenly say it can't find the foreign strings. Going into the I18N tool and copy and pasting the translations from the old English string to the new one will solve that and save someone doing a translation again from scratch.

**Comment by kd-ods** [comment]
> if we change anything - even a full stop - the I18N tool will suddenly say it can't find the foreign strings

Thanks, James. You're right to highlight this. It's a general occupational hazard, though, and there will be plenty of little breakages like this when we do the 0.3 translation. I think the answer is to support translators to access the last version of the source file & translation while doing new translations. So I wouldn't worry about it. (cc @siwhitehouse @rhiaro )

**Comment by odscjames** [comment]
Found another inconsistency - should it be "This should always be X" OR "This should always be set to X"? The later seems better to me.

**Comment by kd-ods** [comment]
I think the punctuation is key here. So, single straight quotes for the value and word like so:

"This MUST be 'X'."

**Comment by odscjames** [comment]
>  single straight quotes

Using the other quotes means that it is rendered in a special style in the docs, and we have seemed to use that elsewhere in the schema

**Comment by kd-ods** [comment]
Backquotes are used for property names and object names. Single quotes are used for property values. ([Styleguide](https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md#bods-schema))

**Comment by odscjames** [comment]
Done - thanks!
