### ISSUE TITLE
Docs: add a page on date fields across the schema

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#387]
Date fields are scattered across the schema's statements and it can be difficult for publishers and data users to understand the different meanings of the fields. E.g.

> statementDate vs publicationDetails.publicationDate.
> 
> Is the purpose of having the two separated that statementDate is when the statement was submitted but that it might not be published till a later date depending on the cadence with which a register is updated, hence need for publicationDetails.publicationDate to show that information may be published on a date quite different/later than the date the statement was first made.

A dedicated docs page could address all the different types of dates and their meanings. (There's a [useful list here](https://github.com/openownership/data-standard/issues/162#issuecomment-964155980) of dates in the schema.)

**Comment by lgs85** [comment]
Need to check how much of this can be resolved/changed as part of #469

**Comment by StephenAbbott** [comment]
Good documentation about the correct use of date fields for publishers is important to change over time updates https://github.com/openownership/data-standard/issues/392

**Comment by kd-ods** [comment]
Work in progress on date formats across the BODS 0.4 schema is here #486.

**Comment by kd-ods** [comment]
The crucial date fields to cover in this guidance page will be:

- [Statement.statementDate](https://standard.openownership.org/en/0.2.0/schema/reference.html#entitystatement)
- [Interest.endDate](https://standard.openownership.org/en/0.2.0/schema/reference.html#interest)
- [Interest.startDate](https://standard.openownership.org/en/0.2.0/schema/reference.html#interest)
- [PublicationDetails.publicationDate](https://standard.openownership.org/en/0.2.0/schema/reference.html#publicationdetails)
- [Source.retrievedAt](https://standard.openownership.org/en/0.2.0/schema/reference.html#source)

Producing this page for the 0.4 release is likely to raise questions about [republishing and provenance](https://github.com/openownership/data-standard/issues/464). Reflections and insights can be stashed on that feature ticket for revisiting later, if necessary.

@Blueskies00 - assigning to you. This should be an interesting bit of work.

**Comment by kd-ods** [comment]
With @Blueskies00 on leave, I'm assigning over to you @kathryn-ods .

[This page in the 'Building an auditable record of beneficial ownership' technical guidance](https://www.openownership.org/en/publications/building-an-auditable-record-of-beneficial-ownership/feature-one-reliable-and-comprehensive-dates-and-times/) sets out our general thinking on dates in BO data. 

I find [this diagram](https://www.openownership.org/en/publications/building-an-auditable-record-of-beneficial-ownership/introduction/) helpful when I think about information flow and time.

Also, in addition to the list of date fields above, you may want to mention:

- [foundingDate](https://standard.openownership.org/en/0.2.0/schema/reference.html#entitystatement)

**Comment by kd-ods** [comment]
@kathryn-ods - the other thing to bear in mind as you approach this, is how this documentation fits with the [planned new page](https://docs.google.com/spreadsheets/d/1gaARj0p7UShhDcHP83RFoRXPSstM8Zc4al5UZRA6AJQ/edit#gid=1592918667) 'Representing record updates'. I think this is an open question for now. Focusing on what the normative guidance is re representing dates in BODS data will probably be a good starting point.

**Comment by kathryn-ods** [comment]
Thanks Kadie starting the reading today

**Comment by kathryn-ods** [comment]
https://docs.google.com/document/d/1ZufLxRGTslgPedoixNLDlg13DXioyoIFV0r2I2E5mGo/edit?usp=sharing

**Comment by kathryn-ods** [comment]
@kd-ods please could you have another look over the edits I have made this morning? https://docs.google.com/document/d/1ZufLxRGTslgPedoixNLDlg13DXioyoIFV0r2I2E5mGo/edit?usp=sharing

**Comment by kd-ods** [comment]
@kathryn-ods - looking good! I don't think it's worth doing much more work on it until I've started work on the new 'Representing record/information updates' page. So that we can fit it all together neatly.

**Comment by kd-ods** [comment]
I've taken a look at this and left a few comments.

I have an observation... but no idea what to do about it. This is going to be one of the only pages we have which is in the Data standard section but contains no normative content. It really is just additional guidance. (But it is really useful additional guidance imo since it brings all the important date fields together and shows how you can recreate a timeline from them.)

I think we probably leave it in that section for the moment, but when we have a few non-normative guidance pages we should group them together elsewhere in the docs.
