### ISSUE TITLE
Documentation proposal: Represent market listing information for PLCs no.1

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#388]
## Documentation proposal for: Represent market listing information for PLCs

**Feature ticket link**: #359

Implementation proposal status: **ACTIVE** (Not: paused | withdrawn | being implemented)

### Initial proposal

**Overview**
I don't think extensive documentation around the new facility to include information about publicly listed companies is necessary. This is because the new fields are in a discrete block within the Entity Statement and there are no data modelling decisions for publishers to make when representing a PLC in BODS. The new property descriptions are carefully written to support understanding, but there are a couple of things that we should do to aid use of the new fields:

- Edit the [Example Data page](https://standard.openownership.org/en/0.2.0/examples/index.html) to point to the [repo directory holding the two PLC examples](https://github.com/openownership/data-standard/tree/master/tests/data/entity-statement/valid), 

- Edit the [Real world identifiers page](https://standard.openownership.org/en/0.2.0/schema/guidance/identifiers.html) to include a section on 'Market identifier codes'. (At first glance it can be confusing to be presented with both a `marketIdentifierCode` and an `operatingMarketIdentifierCode` within a security listing block. This new section in the docs would provide some explanation.) 

**Proposed changes to the docs**

[Draft text is available here](https://docs.google.com/document/d/1FXP0PRJSDLLNkIl21E7xFGwEnxZc7_kLwdj0lIN134Y/edit#). Comments and feedback are welcome.

**Comment by kd-ods** [comment]
@siwhitehouse - another thing for you to review when you have 45 mins. Could you have a read through of the [proposed text changes](https://docs.google.com/document/d/1FXP0PRJSDLLNkIl21E7xFGwEnxZc7_kLwdj0lIN134Y/edit?pli=1#heading=h.p6sa644u3261) and suggest any edits or additions? Thanks!

**Comment by siwhitehouse** [comment]
@kd-ods My apologies for the delay. I've made a few suggestions in the document, but only minor edits
