### ISSUE TITLE
Translation framework: update handbook

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#398]
Whatever happens after #397, the following handbook pages will need to be reviewed, rationalised and updated:

- [Translation](https://github.com/openownership/bods-dev-handbook/blob/master/translations.md)
- [Translations and releases](https://github.com/openownership/bods-dev-handbook/blob/master/standard_releases.md#translations-and-releases) (In particular it's not true that "changes to the standard or documentation do not need to wait for translation before they can be released". New releases for the standard must be translated into supported languages, as set out in the [BODS Language Support Policy](https://docs.google.com/document/d/1E15uIOO_JRU2_hFvetaMu4L66hJSrJMuK1U0lenDiyA/edit))
- [Release process](https://github.com/openownership/bods-dev-handbook/blob/master/standard_releases.md#release-processes)

**Comment by rhiaro** [comment]
Should we move the translation process details from the data-standard/README to the handbook, to have it all in one place? (And do a bit of a reorganise to make it make sense that way of course.)

**Comment by kd-ods** [comment]
> Should we move the translation process details from the data-standard/README to the handbook, to have it all in one place?

Yes. I've added this to the post-release cleanup list (Notion).
