### ISSUE TITLE
Use case research - narrative cases

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#4]
Design choices in the development of the Beneficial Ownership Data Standard must be based around identified user needs. We will be mapping user needs through a three stage process:

![image](https://cloud.githubusercontent.com/assets/342624/21458364/cc5ccdd4-c92d-11e6-860e-159e1632ebdb.png)

A [draft report with eight use case narratives is ready for first review](https://docs.google.com/document/d/1s1qqFAK3cDjTGAlCaQvPOb8KzKkssn9xu2HzWeY6amE/edit).

The use case narratives considered are:

* Data supply
  * Public Registers of Beneficial Ownership
  * Self-submitted data
  * Third-party submitted data
  * Self-published data
* Data use
  * Procurement & onboarding screening and audit
  * General investigations
  * Data-led investigations
  * Data validation

Feedback is invited either directly on the document, or in the thread here.

**Comment by sebbacon** [comment]
Seems like a comprehensive list!

Two main observations:

## Scope

For me the biggest question is about scope. S2, S3 and S4 imply support for a comprehensive register of asset relationships including things like minority shareholdings without control.

If we support recording the minutiae of how assets are structured then we enable a graph of influence to be constructed. This would be immensely powerful.

On the other hand, the appeal of Beneficial Ownership is that it is binary. The power there is that it's less amenable to interpretation and more appropriate for registers that have legal force. And as Gert pointed out, these are the things that have teeth and impact.

If we were to include minority shareholdings, then it would make sense also to include many other forms of economic interest such as control or ownership of assets (landlords, significant lessors of plant, etc).

Again, this would be powerful but if we went down this route we should be careful to guard against producing a standard that is hard to implement.

## Prioritisation

Is there any sense in which it's some narratives are more important than others? For example, while I love the idea of self-published data, my sense is it might be pretty niche overall.  On the other hand, if we can get emerging national registers all to use the same standard that would be a huge win.

**Comment by timgdavies** [comment]
A summary of the use-case report will be included in the latest version of the documentation (posted later today).
