### ISSUE TITLE
Proposed changes to interestType values relating to trusts and other legal arrangements

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#40]
The [OECD Common Reporting Standard for Automatic Exchange of Tax information](http://www.oecd.org/tax/automatic-exchange/common-reporting-standard/schema-and-user-guide/#d.en.345315) contains the following enumeration of controlling person types (for the controlling person of an account). 

```xml

<xsd:simpleType name="CrsCtrlgPersonType_EnumType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">Controlling Person Type</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CRS801">
				<xsd:annotation>
					<xsd:documentation>CP of legal person - ownership</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS802">
				<xsd:annotation>
					<xsd:documentation>CP of legal person - other means</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS803">
				<xsd:annotation>
					<xsd:documentation>CP of legal person - senior managing official</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS804">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - trust - settlor</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS805">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - trust - trustee</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS806">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - trust - protector</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS807">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - trust - beneficiary</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS808">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - trust - other</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS809">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - other - settlor-equivalent</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS810">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - other - trustee-equivalent</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS811">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - other - protector-equivalent</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS812">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - other - beneficiary-equivalent</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRS813">
				<xsd:annotation>
					<xsd:documentation>CP of legal arrangement - other - other-equivalent</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
```

**Comment by timgdavies** [comment]
Reviewing the above list, I see that all the trust related interests are now captured in the [`interestType` codelist](http://standard.openownership.org/en/0.2.0/schema/reference.html#interesttype). 

However, we do not have interest codelist entries for:

* Controlling person of legal arrangement - settlor-equivalent, trustee-equivalent etc..

and, our codelists entries are trust specific (e.g. settlor-of-trust).

@ScatteredInk Do you have a view on:

* Do we need 'controlling person of legal arrangement' codelist entries?

* If yes, could this be handled by making our interestType codelist less specific (e.g. settlor rather than settlor-of-trust) and determining e.g. settlor of what by virtue of the entity the interest is in? 

or

* Is it better handled by addition of codelist entries?

**Comment by ScatteredInk** [comment]
> Do we need 'controlling person of legal arrangement' codelist entries?

Not specifically, I don't think. But it would probably be useful to neutralise/universalise the language in the standard, so that it matches the headline terms used in FATF recommendations ("Transparency and beneficial ownership of legal arrangements").  

My preference is to make the trust/arrangement control types role-based rather than create an ever-expanding codelist - so the option of just dropping 'of-trust' is best, I think.

**Comment by kd-ods** [comment]
Noting that this thread links to #327

**Comment by siwhitehouse** [comment]
The trust-specific values in the `interest-type` codelist are:

settlor-of-trust
trustee-of-trust
protector-of-trust
beneficiary-of-trust
other-influence-or-control-of-trust

I think it's straightforward to rename to 'settlor', 'trustee' and 'protector'. I think there is an argument for using 'beneficiary-of-legal-arrangement' as 'beneficiary' on its own is too vague in the context of beneficial ownership. 

We already have 'other-influence-or-control' and so I I'm interpreting this as a suggestion that we remove 'other-influence-or-control-of-trust' from the codelist.

**Comment by kd-ods** [comment]
> there is an argument for using 'beneficiary-of-legal-arrangement' as 'beneficiary' on its own is too vague in the context of beneficial ownership.

True.

Where does enjoyment of assets fit here? It's something we don't currently cover in the codelist. A beneficiary of a trust may be benefitting by enjoyment of assets, or by future enjoyment of assets. Again: a case for separating role and mechanism eventually? #327

**Comment by kd-ods** [comment]
I think you're right to remove 'of Trust' from these codes. (The CRS codes bind together roles and entities, BODS frees us from that necessity.) 

I wonder whether re-ordering and re-wording the content in the descriptions would be helpful for readers. Especially since the term 'controlling interest' has a very [specific meaning](https://www.investopedia.com/terms/c/controllinginterest.asp), so is probably best avoided. For example, the Settlor definition could be altered from:

"A controlling interest in a trust or other legal arrangement. Defined as the person who gives property into a trust or other legal arrangement for the benefit of beneficiaries. In some legal systems, a settlor is also referred to as a trustor, or occasionally, a grantor or donor." 

...to:

"The person who settles property in a trust or **similar** legal arrangement for the benefit of beneficiaries. In some legal systems, a settlor is also referred to as a trustor or, occasionally, a grantor or donor."

(This also leads me to consider the code names and how we might handle the interest-role tension for the moment. For example we could move to: 

- Ownership **via** shareholding
- Control **via** voting rights
- Control **as** settlor 
- Ownership **as** beneficiary of a legal arrangement

But all of this final editing can wait until the new interests are in.
 )

**Comment by StephenAbbott** [comment]
@tymonk @oalannao Thoughts on this question above in light of OO's recent trusts briefings?

**Comment by kd-ods** [comment]
@tymonk, you commented elsewhere:

> "As I read it, as roles and entities are split it seems fine to remove “OfTrust” from the roles (as the role will be tied to the entity/arrangement “Trust” I assume?)

Yes

> Any reason to not stick to the glossary definitions for consistency?

I'll leave @siwhitehouse to consider alignment with the glossary.

> What is the reason to preserve “OfLegalArrangement” (while axing “OfTrust”)?
> One consideration is whether we are talking of BO of trusts vs. BO of legal entities via trusts, in which case the interest-role wording may need to allow for the different permutations to be clear."

The issue as I understand is: in a Beneficial Ownership Data Standard, it would be potentially confusing to have a code 'Beneficiary' whose applicability only to trusts and other similar legal arrangements is solely flagged in the description of that code. Implementers might be tempted to erroneously use this interest type to flag beneficial ownership, whereas [this is how we flag it](https://github.com/openownership/data-standard/pull/394/files). "beneficiaryOfLegalArrangement" offers clarity the code's applicability/scope only includes legal arrangements.

**Comment by siwhitehouse** [comment]
Thanks to @kd-ods and @tymonk for your comments.

I'm inclined to reuse the Open Ownership Glossary definitions, as suggested by Tymon. These have been agreed internally and so they must represent our best understanding and definition of the relevant terms. Doing this is an additional reason for publishing the glossary.

@tymonk
> What is the reason to preserve “OfLegalArrangement” (while axing “OfTrust”)?
> One consideration is whether we are talking of BO of trusts vs. BO of legal entities via trusts, in which case the interest-role wording may need to allow for the different permutations to be clear."

All of the terms we are editing in this issue relate to legal arrangements. I am proposing that we axe 'OfTrust' from most of the codes so that they are more general. In practice, they could have 'OfLegalArrangement' appended to them. As @kd-ods points out, we can't have 'beneficiary' as a code because of the possible confusion with beneficial ownership.

I'll update the PR with these suggested changes. 

Does anyone want to make the case for adding 'OfLegalArrangement' to all of these codes?

**Comment by kd-ods** [comment]
> Does anyone want to make the case for adding 'OfLegalArrangement' to all of these codes?

Not me.

**Comment by siwhitehouse** [comment]
Here is an example of a definition from the Open Ownership Glossary:

| title | description |
| :-- | :-- |
| Settlor | A settlor is a person who, either actually or by operation of law, creates a trust. In some legal systems, a settlor is also referred to as a trustor, or occasionally, a grantor or donor. |

So, we need some wording that allows for the code to be used for settlor equivalents in other/similar legal arrangements. My suggestion is to add a third sentence as below.

| title | description |
| :-- | :-- |
| Settlor | A settlor is a person who, either actually or by operation of law, creates a trust. In some legal systems, a settlor is also referred to as a trustor, or occasionally, a grantor or donor. Also to be used for a person with a settlor-equivalent role in any legal arrangement that is similar to a trust |

**Comment by tymonk** [comment]
OK this is clear.

The only thing is I can't say with confidence that the roles of settlor, trustee, protector also apply to all other legal arrangement types, but maybe you know this already. (From a quick scan of FATF and [Wiki](https://en.wikipedia.org/wiki/Waqf#Comparisons_with_trust_law), I think they do apply to most.) And I suppose there is still `otherInfluenceOrControl` to cover additional roles.

I'd be in favour of amending the glossary to apply more broadly, maybe by simply applying the following.

title | description
-- | --
Settlor | A settlor is a person who, either actually or by operation of law, creates a trust **or similar legal arrangement**. In some legal systems, a settlor is also referred to as a trustor, or occasionally, a grantor or donor.

**Comment by siwhitehouse** [comment]
I don't have anything more definite than you @tymonk. The [OECD Common Reporting Standard for Automatic Exchange of Tax information](http://www.oecd.org/tax/automatic-exchange/common-reporting-standard/schema-and-user-guide/#d.en.345315) that Tim quoted at the start of this issue uses the phrases 'protector-equivalent´, 'settlor-equivalent' etc. and the [Common Reporting Standard Implementation Handbook](https://www.oecd.org/tax/exchange-of-tax-information/implementation-handbook-standard-for-automatic-exchange-of-financial-information-in-tax-matters.pdf) [PDF] also contains the following

> In legislation implementing the CRS, jurisdiction C has defined that in respect of an entity Controlling Persons are the natural persons who exercise control over the entity (interpreted in a manner consistent with FATF Recommendations (as amended)) and includes (a) in the case of a trust: (i) its settlors, (ii) its trustees, (iii) its protectors (if any), (iv) its beneficiaries, ( regardless of whether or not any of them exercises control over the trust) and (v) any other natural persons exercising ultimate effective control over the trust; and (b) in the case of a legal arrangement other than a trust, persons in equivalent or similar positions to those described above.

Based on that, I don't think we should make the settlor definition broader in the way that you suggest. 

The suggested description states that where someone performs a role equivalent to a `Settlor`, in legal arrangements similar to a trust, then the `Settlor` code should be used. This places the interpretation on the implementor, which I think is fair.

Changing the glossary definition as you suggest would make it incorrect, as someone performing a settlor equivalent role in a similar legal arrangement may well not be called a settlor, as your research demonstrates.

It's a marginal point, I grant you.

**Comment by tymonk** [comment]
Good point. I think we should also change the language of the second sentence to encompass names of potential settlor-like roles we have not yet come across, as it currently reads like an exhaustive lists. I think we're in agreement about the purpose here. Possibly something along the following lines (although possibly final sentence is more useful for glossary than it is for BODS?)

> A settlor is a person who, either actually or by operation of law, creates a trust. Also to be used for a person with a settlor-equivalent role in any legal arrangement that is similar to a trust. Settlors and settlor-equivalent roles can have different names depending on the legal system and specific trust or trust-like legal arrangement in question, including trustor, grantor, donor and founder.

**Comment by StephenAbbott** [comment]
> > Does anyone want to make the case for adding 'OfLegalArrangement' to all of these codes?
> 
> Not me.

Nor me.

**Comment by siwhitehouse** [comment]
@tymonk I've kept with my [original suggestion above](https://github.com/openownership/data-standard/issues/40#issuecomment-1033674285).

I've made a pull request with the changes and I'll add you as a reviewer now in case you want to make any more suggestions.

**Comment by tymonk** [comment]
Thanks @siwhitehouse. I've never done a review before. Is it self explanatory? If not would appreciate a run through so I don't mess anything up.
