### ISSUE TITLE
CSV tests apply to built schema only - as expected?

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#401]
I made a change to the entityType enum in entityStatement.json, adding a couple of new codes. I also added these in the related codelist. 

When I ran pytest, I got a fail: the new enums in the entityStatement.json weren't being 'picked up'. Confusing. Looking at the error output:

> data-standard/tests/test_json.py::test_codelist_enums[/home/kadie/code/data-standard-sphinx-theme/data-standard/docs/_build_schema/entity-statement.json-entity-statement.json-data0]
>   Codelist mismatch:
>   
>                       entityType.csv: 
>   
>                       ['registeredEntity', 'legalEntity', 'arrangement', 'anonymousEntity', 'unknownEntity', 'state', 'stateBody']
>   
>                       entity-statement.json enum:
>   
>                       ['registeredEntity', 'legalEntity', 'arrangement', 'anonymousEntity', 'unknownEntity']

So the tests were looking in _build_schema for the entity statement (but not the codelist csv, apparently). Sure enough, when I rebuilt the docs, the codelists passed.

So - is this expected behaviour? Am I wrongly using pytest? 

Assigning to @rhiaro and @odscjames who might know.

**Comment by rhiaro** [comment]
You're not doing anything wrong. It looks for all JSON files in the directory tree to compare against, but if it's not helpful to have it also check the built schema I can exclude that.

**Comment by kd-ods** [comment]
> ...but if it's not helpful to have it also check the built schema I can exclude that

Yes - I think we should exclude that since, effectively, it's just testing whether the schema (or docs) have been built.

**Comment by rhiaro** [comment]
This was fixed in https://github.com/openownership/data-standard/commit/0498c23fbba3c73bd535c8347e266fdfc11cbe82
