### ISSUE TITLE
Documentation: clarify/separate processes for building docs and running tests

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#408]
I think this is probably just a case of a few different sub-headings but at the moment I find the Readme confusing, as it is framed around building the docs and so plays down how/why we run tests as part of standard development.

I would probably have:

- One heading for "Technical Documentation"
- A subheading for "Installation and setup" or similar with the install instructions
- Further sub-headings for "Tests", "Documentation", and "Translations".

**Comment by kd-ods** [comment]
There's nothing in the ReadMe at all about running schema tests (the ['Build & test the docs locally' heading](https://github.com/openownership/data-standard#build--test-the-docs-locally] relates to the docs tests run as part of the docs build I think).

But - yes - we should have a minimal section in the ReadMe about the schema tests. Fuller documentation of the test setup should be added to the handbook (see [this issue](https://github.com/openownership/bods-dev-handbook/issues/8)).

**Comment by ScatteredInk** [comment]
> There's nothing in the ReadMe at all about running schema tests (the ['Build & test the docs locally' heading]([https://github.com/openownership/data-standard#build--test-the-docs-locally]](https://github.com/openownership/data-standard#build--test-the-docs-locally%5D) relates to the docs tests run as part of the docs build I think).

Ah got you - I see that line on running tests is relatively new. I was coming at this from the perspective of writing induction materials. When I see the heading "test the docs locally", I expect the tests to relate to the docs - they don't, really. If I made a change to the schema, I would therefore be confused about why all of those tests failed.

**Comment by kd-ods** [comment]
> There's nothing in the ReadMe at all about running schema tests

I was completely wrong on that front, @ScatteredInk - and you were very right. I'm just doing an edit now. Hoping you can review it.
