### ISSUE TITLE
Update homepage text and Primer documentation to ensure it is aligned with latest Open Ownership research and style guide

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/data-standard#416]
Revisit the following pages to check alignment with latest Open Ownership research and style guide. Where possible, link to OO tools, research or content for further information:

- [x] [Homepage](https://standard.openownership.org/en/0.2.0/index.html) - flesh out with more detail like [OCDS landing page](https://standard.open-contracting.org/latest/en/)?
- [x] [Primer](https://standard.openownership.org/en/0.2.0/primer/index.html)
- [x] [What is beneficial ownership?](https://standard.openownership.org/en/0.2.0/primer/whatisbo.html)
- [x] [What is the Beneficial Ownership Data Standard?](https://standard.openownership.org/en/0.2.0/primer/whatisthebods.html)

Discuss how to update BODS documentation to best flag/showcase connections with the [Open Contracting Data Standard](https://standard.open-contracting.org/latest/en/guidance/map/beneficial_ownership/) and to thematic areas of interest to users like procurement, anti-corruption, banking, tax, etc...

**Comment by siwhitehouse** [comment]
@StephenAbbott Could you elaborate on the changes you'd like to see to the Index page over on #385, please?

It is the one bit of duplication across the two issues that I can see.

**Comment by StephenAbbott** [comment]
@siwhitehouse Think I should combine this issue with https://github.com/openownership/data-standard/issues/385 so we've just got one for all the documentation changes? I was using this for changes to main Index page and Primer section while https://github.com/openownership/data-standard/issues/385 is for changes to the About section documentation.

To answer your question, I'd very simply like to update the intro page with some more text about BODS so that the "What is BODS?" info isn't buried three or four layers down in the Primer section.

**Comment by StephenAbbott** [comment]
Making a note to say that we agreed we need more time to complete this task and will aim to do so for a BODS v0.4 release

**Comment by StephenAbbott** [comment]
@kathryn-ods Thanks Kathryn. This is looking really good.

Couple of questions/things I've spotted:

1. The bullet points listed following 'BODS allows publishers to provide statements that describe:' at the bottom of the primer seem to have lost all their links to other documentation
2. Where we say 'visit [the Open Ownership Website](https://www.openownership.org/en/)' at the end of 'What is beneficial ownership?', could you please add a full stop at the end and turn the w of website into lower case?
3. As we've moved/removed the technical requirements section, the link for that is not working in the second bullet point under 'Within BODS'. Could you fix that?
4. We need to spell out what BODS means before the acronym first appears in the 'What is beneficial ownership?' section. Can you just change 'In BODS' to 'In the Beneficial Ownership Data Standard (BODS)' there?

**Comment by kathryn-ods** [comment]
> The bullet points listed following 'BODS allows publishers to provide statements that describe:' at the bottom of the primer seem to have lost all their links to other documentation

@kd-ods had this feedback so I took those links out. I'm thinking maybe we should have one clearer CTA after those bullets to make it clear where people should go next? Where do we want folks to go after reading the primer?

> I don't think it's necessarily helpful to readers to include these links. They lead to very specific bits of the standard which are unlikely to be that useful if someone is at the stage of reading the primer. I'd rather they went exploring via the other links in this section.

I've fixed those other typos in a patch and will get them merged in

**Comment by kathryn-ods** [comment]
homepage merged on #645
