### ISSUE TITLE
Real-world example data

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#42]
We'd like to test the standard by building example BODS data using a variety of organisational structures, ownership chains and sources of data. A start has been made in the exampledata branch, but if you have any particularly good examples or edge cases, please add a link to a source here and I will attempt to model in BODS.

**Comment by timgdavies** [comment]
We are now tracking example data internally in OpenOwnership, with plans to release more examples in future versions of the documentation. Closing this issue, as no-one has given us any links to model (but happy to re-open if someone wants to challenge Jack with an interesting modelling problem...!)
