### ISSUE TITLE
[BUG] - Remove the word "Co-operative" when referring to Open Data Services

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#425]
**Summary of the bug or issue**
Most co-ops don't add the word Co-operative to their name when referring to themselves in public. The Open Data Services style guide has been updated to be in line with that.

**Suggested resolution**
If the way to resolve the problem is not obvious, do you have a preferred solution?
When [updating the BODS About/Governance pages for v0.3](https://github.com/openownership/data-standard/pull/424) the word 'Co-operative' has been removed. The remaining references are in the README.md file

**Comment by StephenAbbott** [comment]
@siwhitehouse Sorry about this one. Wasn't sure what to use and Open Ownership style uses Open Data Services Co-operative and Open Data Services interchangably. 

We should amend the OO style guide too. I will suggest a change to that doc now

**Comment by siwhitehouse** [comment]
@StephenAbbott to be fair, I think we have led the way when it comes to this inconsistency!

**Comment by Blueskies00** [comment]
OO's style guide is updated with this, and a search of the data standard documentation site yields no results for "co-operative" or "cooperative".
