### ISSUE TITLE
[i18n] Update transifex client

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#428]
The transifex client is being deprecated completely in November 2022 in favour of a new one. I just had a poke around at updating now, but right now the new one seems to have some options we need missing from the config, and is reportedly 10x slower than the old one (despite being advertised as faster) so decided to leave it.

Also at the moment part of our process uses sphinx-intl which uses the old transifex client (they have [an issue about upgrading](https://github.com/sphinx-doc/sphinx-intl/issues/60)).

The new client is written in Go rather than Python, so won't be installed with pip as the current one. New installation instructions in the readme would look something like:

> You need to install the transifex commandline client. On Linux and Mac this will most likely work:
> 
```bash
curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
```
> 
> **Restart your shell**, and run `tx --version` to check it installed correctly.
> 
> Please verify this is up to date and also [see other instructions for installation in various environments](https://github.com/transifex/cli#installation).

Just opening this issue to keep an eye on things, and as a reminder as November gets closer.

**Comment by kd-ods** [comment]
Noting here that according to a colleague https://weblate.org/en-gb/ is open source and has better git integration. One to watch.

**Comment by kd-ods** [comment]
Just realised this wasn't on the 0.4 project board. Added now.

**Comment by jpmckinney** [comment]
FYI OCP transitioned to the new tx client with no issue. We also contributed fixes to sphinx-intl to restore feature parity with the old client (at least for our usage, but I think it is paired in general).

**Comment by kd-ods** [comment]
Thanks, @jpmckinney - that's good to know.

**Comment by kd-ods** [comment]
Is a more automated workflow possible? I suspect there would be huge benefits for the translators to be able to see their translated work in situ, and for reviewers to start their work by reading it in situ (without a tech person having to be on call to pull, process and merge edits).

I think we've probably looked at the [GitHub-Transifex integration](https://help.transifex.com/en/articles/6265125-github-installation-and-configuration) option before, but I suspect that our codelist CSV and SVG workflow makes things challenging.
