### ISSUE TITLE
New SVGs don't contain translatable strings

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#429]
There are some new SVG files in recent updates to the documentation that have been created in such a way that there are no text strings to extract for translation. These should be converted to a format that contains actual text.

```
RepresentingChainsBODS-RealWorld.svg
RepresentingChainsBODS-Statements.svg
SOE-scenario1.svg
SOE-scenario2.svg
SOE-scenario3.svg
SOE-scenario4.svg
SOE-scenario5.svg
SOE-scenario6.svg
SOE-scenario7.svg
```

**Comment by kd-ods** [comment]
Darnit. That's my problem. Will take a look. Glad you spotted this @rhiaro .
