### ISSUE TITLE
[docs] Pages / sections missing from menu

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#433]
There are a few bits of the docs that are not accessible from any of the menus. Should they be? They show up in search, but obviously only if you know what to search for:

* [Toolbox](https://standard.openownership.org/en/latest/toolbox/index.html)
* [Use cases](https://standard.openownership.org/en/latest/usecases.html)
* [User Guides](https://standard.openownership.org/en/latest/userguides/index.html)

I note Toolbox is completely empty. Perhaps we could delete unneeded pages, rather than keep them around to clutter up my console with warnings every time the docs are built? :)

**Comment by StephenAbbott** [comment]
[User guides](https://standard.openownership.org/en/latest/userguides/index.html) empty too once you click past the headings. 

I vote for deleting all of these and then as part of https://github.com/openownership/data-standard/issues/416 we will make sure to point to more up-to-date thinking, research and resources
