### ISSUE TITLE
Schema effectively forces publishers to use UUIDs

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#44]
Our documentation on identifiers says:

 > Publishers MUST generate globally unique and persisent identifiers for each statement.

>These SHOULD start with a uuid to avoid any clash between identifiers from different publishers, and MAY be suffixed with additional characters to distinguish versions of a statement as required by local implementations.

> In many implementation scenarios, it will be appropriate to simply generate a distinct uuid for each statement.

The schema says:

`    "ID": {
      "title": "ID",
      "description": "A persistent globally unique identifier for this statement.",
      "type": "string",
      "minLength": 32
    }`

The documentation reads as if UUIDs are optional but desirable but the schema suggests that it is enforcing use of UUIDs, or IDs of equivalent length. This is either forcing publishers down the UUID route, or pushing them to create longer IDs.

We could remove the minLength requirement and make the documentation clearer.

**Comment by timgdavies** [comment]
This is an issue for the current Open Ownership export.

Essentially we want to split here:

* Schema requirement - which might be as simple as minLength: 1
* Guidance and validation - where we want to **warn** for lengths of < 32 digits

This could be addressed through work on the validation framework for BODS.

**Comment by timgdavies** [comment]
We [also have this page](http://beneficial-ownership-data-standard.readthedocs.io/en/master/identifiers.html#statement-ids) that currently states:

> Whilst the schema is agnostic as to the exact strategy that data publishers use to generate statement ids, it enforces a minimum length of 32 characters (the length of a hexidecimal UUID) in order to avoid use of ids that are likely to fail a uniqueness test.

I'm leaning back towards idea that we **should** require 32 characters for the statement identifiers, with the option open to publishers to pad any shorter identifiers in their internal systems with a guid-style prefix (which could be a constant).

**Comment by timgdavies** [comment]
Having reviewed the [statement identifier guidance](http://standard.openownership.org/en/0.2.0/schema/guidance/statement-identifiers.html?highlight=statement%20identifiers), taking into account that we will be likely to produce updated guidance on statements identification as part of the next version of the standard, and leaving #11 open to track further work on this, I'm closing this issue.
