### ISSUE TITLE
Coordinate translation of BODS v0.3 into es and ru

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/data-standard#443]

**Comment by kd-ods** [comment]
@StephenAbbott (cc @siwhitehouse) - I think it might be helpful if, at the point we freeze development on the main branch, we build the master branch on ReadTheDocs. So that the translators can see strings in context where helpful. I'll leave it up to you to make a call on that.

**Comment by StephenAbbott** [comment]
@kd-ods Thanks Kadie. So this would mean building the master branch on bods-main to see strings in context and then transferred all strings over to bods-v03 where the translators will be working, right?

**Comment by kd-ods** [comment]
@StephenAbbott - there's no dependency between the translation workflow and use of ReadTheDocs to build the docs for a particular branch. (Obviously RTD will show existing translations for strings where there have been no changes since 0.2.) I think that's fair to say, @siwhitehouse

**Comment by StephenAbbott** [comment]
@kd-ods OK. Please do the ReadTheDocs build then as a useful thing for translators

**Comment by siwhitehouse** [comment]
@StephenAbbott Gotcha. We can build the docs on ReadTheDocs once we have frozen development and uploaded the strings to Transifex.

I think this issue really needs to have the steps of the process outlined in the description so we can keep a track of our progress @StephenAbbott

**Comment by Blueskies00** [comment]
BODS 0.3 released.
