### ISSUE TITLE
Add documentation to state-owned enterprises guidance about modelling data on SOEs owned or controlled by regional government

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/data-standard#447]
Following internal discussions, carry out work to add an additional scenario to the Representing state-owned enterprises technical guidance created as part of the BODS v0.3 release.

This scenario would show how Open Ownership would recommend capturing data on the ownership or control relationship that a regional state government or local authority could exercise over a state-owned enterprise in contrast to a national government where the regional body has autonomous control without the national government having a relationship to the SOE.

In this scenario, the entity statement for the jurisdiction would use `entityType` of state but reference an ISO_3166-2 sub-division code in the `jurisdiction.code` field.

https://standard.openownership.org/en/0.2.0/schema/reference.html#jurisdiction

**Comment by kd-ods** [comment]
The action here is to add a scenario to this page of the docs: https://standard.openownership.org/en/latest/schema/guidance/repr-state-owned-enterprises.html.

The whole page and diagrams should be edited in line with the schema changes agreed for BODS 0.4.

**Comment by kd-ods** [comment]
@Blueskies00 before you work on the nominee ticket #329 we should cowork on this since it will use lots of the techniques you'll need there.

**Comment by kd-ods** [comment]
Scenario text: "Ownership-or-control by a regional state government is known and a statement about ownership is possible."

**Comment by Blueskies00** [comment]
Done and merged in #492.
