### ISSUE TITLE
Loose validation

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#45]
The `jurisdiction` and `nationalities` string fields both specify a `maxLength` property:

```        
"nationalities": {
          "title": "Nationality",
          "description": "An array of ISO 2-Digit country codes",
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 2,
            "minLength": 2
          }
``` 

```
"jurisdiction": {
          "title": "Jurisdiction",
          "description": "The jurisdiction in which this entity is registered, expressed using an ISO ISO_3166-2 2-Digit country code, or ISO_3166-2 sub-division code, where the sub-division in question (e.g. a sub-national state or region) has relevant jurisdiction over the registration of operation of this entity.",
          "type": "string",
          "minLength": 2,
          "maxLength": 10
        }
```

The source material for these fields does not always require information in ISO 3166-2 form, and so these restrictions can be seen as a barrier to publishing. The other side of this argument is that, if we allow jurisdiction information to include "British", "England", "uk", "Unknown" when then value should be "GB", then the data is less useful, and it is harder to push the policy argument for open ownership information further.

**Comment by ScatteredInk** [comment]
Thinking about this a bit more, we are *already* allowing for imperfect information in other fields that respects the imperfections in the source material. Our date fields say 'one of an ISO 8601 Date time *or* YYYY-MM *or* YYYY'.

Given that publishing ownership data beneficial ownership data is more of a process than a single decision, we probably want our validation to be flexible/minimal and to put much more effort into documenting best practices on policy, systems implementation and data collection.

**Comment by CountCulture** [comment]
I agree. We want people to be collecting to best practice, but requiring best practice is more problematic. I wonder what the best way of specifying best practice in the standard (vs alternative, less good forms)

**Comment by ScatteredInk** [comment]
Open Contracting uses the concept of 'basic' through to 'advanced' fields and also uses the five-star model to incentivise publishers to improve. I've drafted this basic definition of what five-star BODS publishing could look like:

> Adopt granular descriptions of beneficial ownership interests, anonymised unique identifiers for natural persons and link beneficial ownership to other relevant data (e.g., government contracting data).

**Comment by ScatteredInk** [comment]
Another out-of-schema validation model, and one that is more granular than the five-star model, is the [rulesets](http://iatistandard.org/202/rulesets/) used in IATI. Something to consider as we build validation tooling, I think.

**Comment by ScatteredInk** [comment]
Another aspect of this is secondary validation outside the schema. Entity identifiers, for example, expect a `scheme` from the org-id list.

In internal discussions, we have talked about allowing strict and loose validation models to allow for data produced to the standard and data produced by external systems to be represented.

**Comment by ScatteredInk** [comment]
I've opened #74 for discussion on a way to move forwards on this.

**Comment by ScatteredInk** [comment]
This work is now being done in #80

**Comment by timgdavies** [comment]
This was handled in #80 and no further action required on this issue at present.
