### ISSUE TITLE
[BUG] - 0.3 - is PublicListing/securitiesListings required?

### ISSUE THREAD

**Issue by odscjames** [openownership/data-standard#454]
**Summary of the bug or issue**
https://github.com/openownership/data-standard/blob/master/schema/components.json#L588 says it is.
But if so, why not companyFilingsURLs?
And why does https://standard.openownership.org/en/master/schema/reference.html#publiclisting say it is NOT required?

(https://standard.openownership.org/en/master/schema/schema-browser.html#entity-statement correctly shows required fields)

**Suggested resolution**
Whatever it is, there is maybe a bug in the reference widget we should look into?

**Comment by odscjames** [comment]
https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema 0.5.0 may solve this?

**Comment by Blueskies00** [comment]
Another issue relating to this is when publicListing/hasPublicListing is marked as FALSE. The data review tool then shows the error: "securitiesListings is missing but required. Check that the field is included and correctly spelled." as per the schema. However, if hasPublicListing is FALSE that means there's no details to be included with securitiesListings.

**Comment by kd-ods** [comment]
securitiesListings should not be a required property of PublicListing. (I think it was erroneously maintained as such when the hasPublicListing boolean was moved inside the PublicListing block.)
