### ISSUE TITLE
[BUG] - Link missing on key concepts page

### ISSUE THREAD

**Issue by lgs85** [openownership/data-standard#455]
The [Direct and indirect ownership and control](https://standard.openownership.org/en/latest/schema/concepts.html#direct-and-indirect-ownership-and-control) section of the key concepts page should contain a link to the new page on [representing beneficial ownership](https://standard.openownership.org/en/latest/schema/guidance/repr-beneficial-ownership.html).

**Comment by kd-ods** [comment]
@Blueskies00 - I've reassigned this to myself, since I'm going to take on the rewriting of the Key concepts page.

**Comment by kathryn-ods** [comment]
@kd-ods I think this section has been removed now so this isn't relevant anymore
