### ISSUE TITLE
[BUG] - Lock theme version

### ISSUE THREAD

**Issue by odscjames** [openownership/data-standard#459]
**Summary of the bug or issue**

0.2.0 locks version of the theme - good! https://github.com/openownership/data-standard/blob/0.2.0/requirements.txt#L8

0.3.0 does not! https://github.com/openownership/data-standard/blob/0.3.0/requirements.txt#L7 When did this happen? Looks like when we switched to compile tools?

**Suggested resolution**
Fix by starting to lock again.

Or maybe this is something in favour of just merging the theme & standard repositories?

**Comment by kd-ods** [comment]
@radix0000 - have assigned this to you while AG is off.

**Comment by kd-ods** [comment]
Probably worth looking at https://github.com/openownership/data-standard-sphinx-theme/issues/81 at the same time.
