### ISSUE TITLE
Tweaks to feature request template

### ISSUE THREAD

**Issue by lgs85** [openownership/data-standard#460]
The feature request template is a really valuable way of structuring feature tickets. Having completed a few I wanted to suggest a couple of minor tweaks:

- In the feature background, suggest adding a subsection at the start along the lines of 'Briefly describe the purpose of this feature'. (would need to make sure it's clear this is a high level description not an implementation proposal)
- I think that the question of importance is well covered in the questions on user needs and the impact of not meeting needs, and I think this could be removed
- The question on urgency could be reframed to be less subjective and more open. e.g. 'what impact would delaying meeting these needs have'.

**Comment by kd-ods** [comment]
@lgs85 - do you want to have a crack at editing the template? It can be done here: https://github.com/openownership/data-standard/issues/templates/edit. I think if you hit the 'propose changes' button it spins up a PR, so I can review changes there.

**Comment by lgs85** [comment]
looks like it just makes the edits using this approach, so i've edited the md file locally on a new branch and will submit a PR that way
