### ISSUE TITLE
Upgrade to JSON Schema Draft 2020-12

### ISSUE THREAD

**Issue by lgs85** [openownership/data-standard#469]
BODS uses JSON Schema [Draft 4](https://json-schema.org/specification-links.html#draft-4). We should consider updating to the latest schema [Draft 2020-12](https://json-schema.org/draft/2020-12/release-notes.html). This issue is intended to be the start of a discussion rather than a detailed implementation proposal at this stage.

# Benefits

There are a number of reasons to upgrade the schema version. The below are illustrative examples and by no means comprehensive.

## Clarity around keywords
- `$id` replacing `id`, reducing potential confusion with instance properties
- `$defs` replacing `definitions`, for similar reasons
- `exclusiveMinimum` changed to represent a number (and replace `minimum`) instead of a boolean, reducing redundancy

## New features and keywords
- `examples` can be embedded into the schema
- `const` can be used to specify constant values
- `if` `then` and `else` can be used for [conditional application of subschemas](https://json-schema.org/understanding-json-schema/reference/conditionals.html#if-then-else)

## New formats

Many new formats, including:
- `date`
- `time`
- `email`
- `uuid`
- `iri`

# Considerations

Updating the JSON Schema version will require a substantial amount of work in addition to the schema changes themselves, potentially including:
- Updating documentation reference pages
- Updating the BODS validation tool
    - CoVE will work with JSON Schema 2020-12, but changes to keywords may cause additional checks to fail
    - Some validation that are currently additional checks may be able to be embedded within the schema itself
- Updating example data (e.g. to deal with changes to `exclusiveMinimum` and `exclusiveMaximum`

Proposals for new BODS features including change over time, separating core data from metadata, and representing declarations, will all involve substantial structural changes to the Schema. Using draft 2020-12 may help to facilitate some of these changes, and this is something that will require further research. In the meantime, it may make sense to consider an upgrade of the current schema as-is to JSON 2020-12.

**Comment by lgs85** [comment]
I tried plugging the [entity statement schema](https://raw.githubusercontent.com/openownership/data-standard/master/schema/entity-statement.json) into alterschema and [got something](https://gist.github.com/lgs85/eee2102b384385821b56e53d8e159a80) that looks very sensible on first glance. Obviously this won't do any new/subjective stuff but looks like a very useful starting point.

**Comment by duncandewhurst** [comment]
Using draft 2020-12 for the Open Fibre Data Standard hasn't caused us any issues yet and we've found some of the new features, keywords and formats to be useful. We actually missed renaming the `id` and `definitions` keywords, although that hasn't caused any issues with tooling. I'm sure you'll do a full audit of which keywords are used in the BODS schema, but another to watch out for is the [renaming of `additionalItems` to `items`](https://json-schema.org/understanding-json-schema/reference/array.html#additional-items) for array validation.

If it is possible to replace some additional checks with schema validation, then I think that is a very good benefit from a tooling point of view.

**Comment by StephenAbbott** [comment]
Thanks @duncandewhurst. Appreciate the advice

**Comment by rhiaro** [comment]
Headlines from the version update:

* The only thing that results in changes to data are the `exclusiveMinimum` and `exclusiveMaximum` changes.
* The following terms removed from the metaschema:
  * `deprecated`: now a JSON Schema keyword, though BODS wasn't using it
  * `omitWhenMerged`: not used by BODS
  * `versionId`: not used by BODS
  * `wholeListMerge`: not used by BODS

Further improvements that require a bit more work (in no particular order):

* we can probably tighten up closed codelist validation by using `prefixItems` properly
* can we replace `oneOfEnumSelectorField` with `if/then/else`?
* can we use dynamic refs to fix the problem in the comments in https://github.com/openownership/data-standard/blob/main/tests/bods_validate.py#L45
* (how) can we take advantage of `$vocabulary`
* adding examples and comments to the schema itself
* where can we take advantage of `uuid`, `duration`, `date`, `time` and `regex` formats
* we should make sure we're using `$ref` properly to refer to subschemas, and work out how this affects the schema compilation process (aka, do we need to 'build' the schema any more to validate it at all? Should we look at [bundling](https://json-schema.org/understanding-json-schema/structuring.html#bundling)?)
* `contains`/`minContains`/`maxContains` - I don't think there are any BODS arrays for which these are useful, but worth double checking.
