### ISSUE TITLE
Translate version 0.4 documentation into French, Spanish and Russian

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/data-standard#471]

**Comment by kd-ods** [comment]
14th Feb 2023 notification from Transifex:

> As some of you already know, we have been working on improving and enhancing our existing GitHub and BitBucket integrations. As of the 16th of February, our old integrations will be replaced. 
> 
> Since you have been using one of the two integrations in Transifex, or both, we would like to give you a heads-up that you will be automatically migrated to the new ones on that day.
> 
> The most important thing is that you don’t have to take any action from your side! We assure you that there will be no data loss or disruption of your workflow. 
> 
> Best Regards,
> 
> The Transifex Team

**Comment by StephenAbbott** [comment]
Email from Transifex team received on 16th February 2023:

> Due to unforeseen technical issues during our final testing stages, we will be delaying the release of the GitHub and Bitbucket updates until our team ensures everything is up to the highest standards.
> 
> We appreciate your patience and understanding as we work to ensure that it's released in its best possible form.
> 
> Thank you for your continued support.
> 
> Best Regards,
> 
> The Transifex Team

**Comment by StephenAbbott** [comment]
@StephenAbbott to consider introducing French translation of BODS for version 0.4 for the first time
