### ISSUE TITLE
Rename Master branch to Main

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#478]
**Summary of the bug or issue**

Version control systems are moving to use 'main branch' terminology, instead of 'master branch'. We should modernise our setup similarly.

**Suggested resolution**

We first need to ascertain what related tooling and links might be affected by such a change. Here's a few things we'll need to check, off the top of my head.

- [ReadTheDocs build](https://standard.openownership.org/en/latest/) for the main branch
- Translation pipeline
- [BODS development handbook](https://github.com/openownership/bods-dev-handbook)

Calling @rhiaro @odscjames @radix0000 for any other tooling/link considerations.

@rhiaro - should we assign to you?

**Comment by rhiaro** [comment]
Use of `main` has been in place for years at this point, and most systems like readthedocs will be able to automatically adjust. I expect we will mostly just need to check our own documentation.

**Comment by kd-ods** [comment]
@StephenAbbott - is it ok to add this isse to the 0.4 release board and have @rhiaro take a look at it?

**Comment by rhiaro** [comment]
* [ ] Update bods-dev-handbook
* [ ] Update data standard documentation
* [ ] Update transifex settings
* [ ] Rename master to main

Once renamed, tomaster update your local environment you will need to do:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Github should automatically tell anyone trying to push to the repo to do this.

**Comment by kathryn-ods** [comment]
@rhiaro am I ok to close this?
