### ISSUE TITLE
Edit of schema and codelist descriptions for v0.4 release

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#480]
The [proposed implementations](https://github.com/openownership/data-standard/discussions) for the 0.4 features mean:

 - structural changes in the schema
 - updating the conceptual model
 - terminology changes
 
This means that descriptions across the schema and codelists will need a thorough edit to bring language and concepts into line.

**Comment by kathryn-ods** [comment]
Making sure that any normative requirements are clearly identified and stuff that isn't normative doesn't sound like it is

**Comment by kathryn-ods** [comment]
Generate a spreadsheet of different schema/codelist descriptions using OCDS tools and work through the edits there.

**Comment by kathryn-ods** [comment]
See https://docs.google.com/spreadsheets/d/1_bpusGnp6W7bVFFeESVijMvfM_FTuAEumTIQh1fPTto/edit?usp=sharing for list of field names and codelist names

**Comment by kd-ods** [comment]
Noting here, that this ticket covers a final, stylistic edit of the schema before release. Where particular issues related to schema descriptions are being uncovered as part of the schema redesign (#487) and validation work (#516), they are being logged individually and labelled with ['schema descriptions'](https://github.com/openownership/data-standard/labels/schema%20descriptions)

**Comment by kd-ods** [comment]
Agreed that I'd work directly on the schema files next week with reference to the content and comments on the spreadsheet.
