### ISSUE TITLE
BODS v0.4 schema redesign

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#487]
This ticket covers the work to implement the proposals on:

- #482
- #477
- #475

The work consists of:

- [x] Create new test and example data
- [x] Rework the json schema files. At a high level:
  - bods-package.json -> statement.json
  - entity-statement.json -> entity-record.json
  - person-statement.json -> person-record.json
  - ownership-or-control-statement.json -> relationship-record.json
- [x] Update existing test and example data
- [ ] Update docs and add 'To do' flags where pages will need ongoing work before the 0.4 release

**Comment by jpmckinney** [comment]
And the links to the features for those proposals:

#463 
#465
#392

**Comment by kd-ods** [comment]
@rhiaro - with the merging of https://github.com/openownership/data-standard/pull/510 , shall we call this ticket done?

(I'm satisfied that all the remaining work on related documentation, validation and fixing the docs build is captured in the remaining tickets on the [project board](https://github.com/orgs/openownership/projects/4).)

**Comment by rhiaro** [comment]
@kd-ods I'm happy if you're happy. Still things to do / iterate on, but the fundamental changes have been made, and we're better off working to to tickets that represent specific smaller changes at this point.

**Comment by kathryn-ods** [comment]
Noting that this feature is complete as of BODS 0.4 see - https://standard.openownership.org/en/0.4.0/standard/index.html
