### ISSUE TITLE
Modelling trusts

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#49]
The beta version of the standard has a simple model of trusts, reflecting the lack of publicly-available data on ownership and control.

Trusts are covered under the `entity` type `arrangement`. An arrangement is described in the documentation as an artificial entity "associating one or more natural or legal persons together in an ownership or control relationship, but without implying that the parties to this arrangement have any other form of collective legal identity".

With the proposed changes to the EU's Fourth Anti-Money Laundering Directive, beneficial ownership information on trusts is likely to be stored in central registers and this information, in turn, _may_ be made available to the public. There is therefore a strong argument that BODS will need to model trusts in a more sophisticated way in order to fully meet its selling point of describing who owns and controls wealth.

There are two parts to this:

1. Modelling beneficiaries, controllers and other natural persons involved in trusts. See #40 
2. Modelling trusts as a legal structure, as opposed to a black-box `arrangement`, if scoping research show that this is the appropriate path to take.

**Comment by ScatteredInk** [comment]
The revised AMLD, and desired inter-operability with OECD Common Reporting Standard, requires a way to represent trusts. In the absence of any implemented data publication (besides basic information published by trusts who have obtained GLEIs), the model I have proposed here remains relatively simple.

First, new types of control have been introduced in the interest type object, as follows:

| Interest type  | Description |
| ------------- | ------------- |
| `senior-managing-official`  | Senior managing official  |
| `settlor-of-trust`  | Settlor of trust  |
| `trustee-of-trust` | Trustee of a trust. |
| `protector-of-trust` | Protector of a trust |
| `beneficiary-of-trust` | Beneficiary of a trust |
| `other-influence-or-control-of-trust` | Other influence or control of a trust |

These control types allow trusts and their beneficial owners to be represented, and are in line with CRS definitions.

Second, an `agreement` field can be used to provide detail on classes of beneficiaries or the purpose of a trust. This is in line with FIBO representations of trusts.

Further information may be provided using annotations as required.

In addition, the UK's PSC declaration regime has 'rights to surplus assets' as a form of control for limited liability partnerships. This is proposed as an additional form of control.

| Interest type  | Description |
| ------------- | ------------- |
| `rights-to-surplus-assets`  | Rights to surplus assets |

**Comment by timgdavies** [comment]
This makes good sense to me.

**Comment by timgdavies** [comment]
See also #98

**Comment by timgdavies** [comment]
I've staged this for schema-beta-2
