### ISSUE TITLE
Guidance on statement ordering for BODS v0.4

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#490]
At the moment in BODS we state that:

> Each of the [entityStatements](https://standard.openownership.org/en/0.2.0/schema/reference.html#schema-entity-statement) or [personStatements](https://standard.openownership.org/en/0.2.0/schema/reference.html#schema-person-statement) referenced by a particular [ownershipOrControlStatement](https://standard.openownership.org/en/0.2.0/schema/reference.html#schema-ownership-or-control-statement) MUST appear before that particular ownership-or-control statement in the ordered array.

(From: https://standard.openownership.org/en/0.2.0/schema/guidance/serialization.html)

In BODS 0.4, relationship statements will connect to entity and person information via recordId, not via statementId. What are the implications of this for guidance on statement order in a dataset?

I think we still need at least one statement for a related record to occur before the recordId is used in a relationship record to support efficient processing. @radix0000 @rhiaro - does that seem right?

**Comment by kathryn-ods** [comment]
@kd-ods noticed this is listed in in progress but doesn't have anyone assigned currently. Did you get an answer to this question elsewhere?

**Comment by kd-ods** [comment]
Thanks, @kathryn-ods for the nudge.

No - this is still an open question. I've put it back into the 'to do' column.

@radix0000 @rhiaro - your opinions on this issue would be valuable.

**Comment by kd-ods** [comment]
There also needs to be a similar requirement (to be added to the Serialization page) that: within a BODS dataset, the declarationSubject value of each Statement must match the recordId value of at least one other Statement.

This might have implications for statement ordering too: i.e. for more efficient processing Entity (or Person) Statements of declaration subjects must be the first Statements in a dataset.

But such stringent requirements on statement ordering may be extremely difficult for publishers to comply with. 

(There's also a requirement on statement ordering related to [use of componentStatementIDs](https://standard.openownership.org/en/latest/schema/guidance/repr-beneficial-ownership.html#intermediaries).)

**Comment by kd-ods** [comment]
In [BODS 0.4](https://standard.openownership.org/en/main/schema/guidance/serialization.html#statement-order) we decided NOT to add a requirement to the effect that "the declarationSubject value of each Statement must match the recordId value of at least one other Statement". The rationale was that this is a stringent requirement which is a relatively heavy lift for the publisher without there being evidence that there is a need for it at the user end. Additionally, with clarity in 0.4 about representing changing BO info over time, there is at least one publishing pattern which would not align with this requirement. That is: a publisher might make regular snapshot datasets available, releasing delta files in between times. Minimal delta files wouldn't meet this additional requirement. 

(Note: the same thing can be said about the existing (updated) requirement:

> the interestedParty and subject values of a Relationship statement, when they are a recordId value, MUST match the recordId value of at least one other prior Statement in the array.

A separate issue will be logged so that its removal in future can be considered.)
