### ISSUE TITLE
Upgrade To More Modern Python Version

### ISSUE THREAD

**Issue by radix0000** [openownership/data-standard#499]
Latest changes have bumped Python version from 3.8 to 3.9, without issue, but active support for 3.9 still ended a year and a half ago and security support ends in less than 2 years. Suggesting that we upgrade to 3.11 before BODS 0.4 is released. In theory this should only require a few hours work, unless there are any compatibility issues.

**Comment by kd-ods** [comment]
@rhiaro - see @radix0000 ' suggestion. Is this something that you've already done as part of the schema update and looking at dependencies?

If not: do you have any opinion on when we should tackle this on the backlog of BODS 0.4 work?

**Comment by rhiaro** [comment]
This will be fixed when #510 is merged, running the tests fine locally so far but haven't tested docs yet. I had a look at the difference between the versions and there's no obvious reasons to expect compatibility issues.
