### ISSUE TITLE
Handling protected information

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#5]
The UK Persons of Significant Control register has two [categories of 'protection'](http://xmlforum.aws.chdev.org/t/persons-with-significant-control-protection-regime/23) ([see also](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514416/Protection_regime_company_guidance.pdf)):

(1) Excluding Usual Residential Address (URA) from the details shared with groups like Credit Reference Agencies.

(2) Excluding all details of the PSC from the register (called 'Super Secure')

Case (1) doesn't raise many issues, as it does not change the public record (which does not contain residential addresses in the first place, just a correspondence address). 

The standard may, however, need to handle case (2) where the register would show that there is a 'Super Secure' PSC, but not their details. 

Some category to indicate where redacted information is given should be used.

**Comment by sebbacon** [comment]
We need to consider that personally identifying information can be leaked through the combination of improperly anonymised related information. For example, if someone is BO through shareholding in a company, and the person is redacted and the company isn't, then, in some jurisdictions it would be easy to guess who that person was.  In the linked example, persons with 790ZG protection must do most of their Companies House filings on paper to protect against this.

I don't know enough about this to provide any practical suggestions, but something to bear in mind.

**Comment by timgdavies** [comment]
Related to #22

**Comment by timgdavies** [comment]
A [`PersonStatement`](http://standard.openownership.org/en/0.2.0/schema/reference.html#personstatement) may have an `unspecifiedPersonDetails` with a `reason` from a [codelist](http://standard.openownership.org/en/0.2.0/schema/reference.html#unspecifiedreason) and a free text `description`. 

This addresses the initial issue, but does not fully cover @sebbacon's point regarding risks of re-identification, which should be covered separately by guidance on privacy.
