### ISSUE TITLE
[BUG] - Broken links on Schema reference page

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#502]
There are several links on the reference page that are showing as plain text. 

These links are being pulled from the schema JSON files and the links are working in the schema browser but not on the reference page. 

I tried to fix myself locally when I noticed the first link but since it seems to be an issue with links in general I need some support figuring out the problem. 

- 'Statement Fragment Pointer | An RFC6901 JSON Pointer (https://tools.ietf.org/html/rfc6901) '
- 'URI | Where a persistent URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)'
- 'Scheme | For entity statements, the scheme should be a entry from the org-id.guide (https://www.org-id.guide)'
- URI | Where this identifier has a canonical URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)
- Name | An name by which this individual is known. Names should be provided in `fullName`, and may optionally be broken down in the `familyName`, `givenName` and `patronymicName` fields, based on the EC ISA Core Person Vocabulary (https://joinup.ec.europa.eu/solution/e-government-core-vocabularies) 
- License URL | A link to the license that applies to this statement. The canonical URI of the license SHOULD be used. Publishers are encouraged to use a Public Domain Dedication or Open Definition Conformant (http://opendefinition.org/licenses/)

**Comment by kathryn-ods** [comment]
I noticed that the links are working for 0.2 where markdown was being used. Possibly related to https://github.com/openownership/data-standard/pull/370?

**Comment by kd-ods** [comment]
This is a feature, not a bug. Here's the background: https://github.com/openownership/data-standard/issues/264

OK to close, @kathryn-ods?

**Comment by kathryn-ods** [comment]
Thanks Kadie! Can I just double check for 100% certainty - it was decided these links don't need to be clickable? For someone to use the link they would have to manually copy and paste it.

**Comment by kd-ods** [comment]
Yes - it was decided that they won't be marked up as links in the descriptions.

(It's platforms and software which make links clickable. And some - like the [browsing widget](https://standard.openownership.org/en/0.3.0/schema/schema-browser.html#entity-statement) we use in the docs - will detect that these are links and make them clickable anyway.)

**Comment by kathryn-ods** [comment]
That makes sense! Will close this ticket
