### ISSUE TITLE
Splitting person, entity and null statements

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#51]
We currently refer to multiple types of object in a single field, e.g. `interestedParty` can refer to an `entityStatement`, a `personStatement` or a `nullStatement`. This causes validation issues and makes analysis and database imports difficult. In the next BODS release, we should move to a pattern of having these objects in separate fields and validating that only one is present.

See https://github.com/OpenDataServices/flatten-tool/issues/182 for discussion.

**Comment by timgdavies** [comment]
@ScatteredInk Can you confirm whether there is still an issue here, or whether this can be closed?

**Comment by ScatteredInk** [comment]
We have split this out and now refer to an interested party using one of `describedByEntityStatement`, `describedByPersonStatement` or `unspecified`. So this can be closed.
