### ISSUE TITLE
[BUG] - Inconsistency in country codes requirement 

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#511]
**Summary of the bug or issue**
The country object requires a name and can have a code https://standard.openownership.org/en/latest/schema/reference.html#country
The address object requires a country code and not a name https://standard.openownership.org/en/latest/schema/reference.html#address

**Suggested resolution**
We could use the country object inside the address object to resolve this.

**Comment by kd-ods** [comment]
Yes, I think the use of the Country object within the Address object would allow for better structured address data where it's available.

**Comment by kd-ods** [comment]
Both Address and Country objects are in the [components.json schema file](https://github.com/openownership/data-standard/blob/main/schema/components.json).

Here's the [documentation](https://github.com/openownership/bods-dev-handbook/blob/main/testing.md#adding-tests) on adding tests to the repo. The idea is that schema work is test-driven, so this work can be done by:

- producing a set of **valid** JSON files which contain a single minimal entity or person statement, which demonstrate the new field structure and valid values. Adding these to the data/valid-statements directory.
- producing a set of **invalid** JSON files which contain a single minimal entity or person statement, which demonstrate the likely structural and value errors that may be made. Adding these to the data/invalid-statements directory.
- making the schema edits and running pytest tests/test_data.py to check that the schema edits are correct and the valid data is passing and the invalid data failing.
- editing the [test_invalid_files](https://github.com/openownership/data-standard/blob/df5c7f4d22f03fad3694f233aa81080eb72b4265/tests/test_data.py#L36) function in test_data.py to assert the expected error messages for the invalid data.
- making any edits to already existing test files in the valid-statements directory to ensure they are still valid given the changes to the schema.
