### ISSUE TITLE
Bring as many validation tests into the schema logic as possible

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#516]
JSON schema 2020-12 allows more validation logic to be included.

We will use [this spreadsheet](https://docs.google.com/spreadsheets/d/1W7CE17BFjapN5N7EyIZjFtIPdf-aPMeUvYc5PDYNe04/edit#gid=0) to track the validation tests which are being built into the schema.

**Comment by kd-ods** [comment]
I'll do an initial pass down the notes in this sheet.

**Comment by kd-ods** [comment]
@rhiaro - I've been reviewing this spreadsheet again. I'm satisfied that we have brought as many local tests into the schema as we can... or we have dedicated open tickets for remaining logic to be added.

The outstanding question is: how complete do you think the valid and invalid test data needs to be in the repo? Are we looking at - for example - at least one valid and invalid file per field? Or should we aim to test all constraints on every field and object (i.e. put a 'y' in column F for each row).

I want to get this work set up for myself, @odscrachel and @kathryn-ods over the next day or two.

**Comment by rhiaro** [comment]
We should aim to test all constraints on every field and object.

**Comment by kd-ods** [comment]
OK.

It's fine.

It's finite.

We can do this.

**Comment by kd-ods** [comment]
Documentation on adding test data is now [in the handbook](https://github.com/openownership/bods-dev-handbook/blob/main/testing.md#adding-tests).

Valid files are being renamed to remove fermentcat_ and tecido_ prefixes. PR #616

**Comment by kathryn-ods** [comment]
closing as all possible tests have now been added in!
