### ISSUE TITLE
Update BODS example data for the 0.4 release

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#517]
The main PR for the 0.4 schema redesign (https://github.com/openownership/data-standard/pull/510) won't contain any any example data. 

@kathryn-ods and @kd-ods created some scenarios and related 0.4 data. This should be reviewed and broken down into useful examples to demonstrate various features of the schema, replacing the [existing examples](https://standard.openownership.org/en/0.3.0/examples/index.html).

**Comment by kathryn-ods** [comment]
@kd-ods to review what repo examples and what needs to be updated and which can be archived

**Comment by kathryn-ods** [comment]
valid test data from nominees and trusts work can also be used as examples

**Comment by kathryn-ods** [comment]
I will also audit the 0.3 examples and compile a list of them

**Comment by kathryn-ods** [comment]
@kd-ods I have made a list of all the test data and the example data in the 0.3 repo https://docs.google.com/spreadsheets/d/1CMBi_rsIC2FfgDoVScuLfe2ayaLr1vWu3DOHvEhiWuI/edit?usp=sharing 

difficult for me to be super opinionated about what we keep or not at this point in time - would be good to talk through what the criteria should be

**Comment by kd-ods** [comment]
@kathryn-ods - I've gone through and been loosely opinionated! I've worked on the assumption that 'example bods data' should be valid BODS lists (not single statements). In this sense they can also be used as test data packages.

I think there are about 15 which will be worth transforming into BODS 0.4. And in terms of where we ultimately store them in the repo... we might just want to add them (later) to the [new 'valid-lists' directory](https://github.com/openownership/data-standard/pull/510/files). Then we can simply pick them out from the [Examples page in the docs](https://standard.openownership.org/en/0.3.0/examples/index.html), providing useful descriptions there.

All of the 15 examples are 'snapshots in time' - i.e. they don't make use of replacesStatements (I think!). This might make transforming to BODS 0.4 a little easier. I think it's probably worth producing a script for this.

**Comment by kathryn-ods** [comment]
@kd-ods here is my WIP script for converting test data to 0.4 https://deepnote.com/workspace/open-ownership-25677d4c-15b9-48a0-9053-f64d967148f5/project/Update-Test-Data-03-greater-04-84de8e13-13d8-4bd6-9fef-66f0838f2eab/notebook/Notebook%201-c765df90872141a2a2a990bbc77427c0

and here's the test data so far https://drive.google.com/drive/folders/1jLuV5qBFPbyQ_EOArIcr9Ho7igaZlPL_ 

I will do a thorough review of these on Tuesday.

**Comment by kathryn-ods** [comment]
Example data checked using pytest on the 0.4 branch - the Python notebook does most of the work but there's a couple of non-ascii characters that need to be removed manually. Changes to the example data are in this branch https://github.com/openownership/data-standard/tree/examples-update

**Comment by kathryn-ods** [comment]
see pull request #568
