### ISSUE TITLE
Validation changes - entitySubtype and entityType

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#519]
In BODS 0.3 entitySubtype.generalCategory is only used for entities with entityType stateBody. 

In BODS 0.4 we are introducing an entitySubtype.generalCategory for trusts (#518) which will be valid for entityTypes arrangement and legalEntity. 

Currently this test https://github.com/openownership/lib-cove-bods/blob/master/libcovebods/tasks/checks.py#L622 checks the validity of an entitySubtype.generalCategory based on the prefix matching the entityType (e.g. stateBody-stateAgency) 

As 'trust' will be valid for multiple entityTypes we should:
- remove the prefixes from the codes
- find a new way to validate entitySubtype.generalCategory codes have the correct entityType

(Open contracting seem to have a system for this https://github.com/open-contracting/standard/blob/1.2-dev/schema/codelists/documentType.csv)

**Comment by kathryn-ods** [comment]
- make schema changes in #518 and #520 and here in the same branch 
- because we are using JSON schema 2020-12 we should be able to bring this into the schema logic as per #516 and not need to do this in the same way as OCDS 
- make test data including edge cases and test it against schema

**Comment by kathryn-ods** [comment]
Alongside new codes for trusts and nominees we also need to edit the SOE codes

**Comment by kathryn-ods** [comment]
Draft of validation logic needed for this https://docs.google.com/document/d/1iPaNLv9aKAnJ1kTprpZRlfvmTEHVL7aAjinRjFDyKxU/edit

We need to make some decisions around SOEs specifically. 

Currently there is an entitySubtype 'stateBody-other' - A type of state body unlike a government department or state agency.

Is this a useful code to keep in? It doesn't add any information other than the negative that this entity is not one of the other entitySubtypes for state bodies. 

Option 1) remove 'other' as a code and allow users to leave this field empty. Possible risk that users leave this empty when one of the other stateBody codes applies. 

Option 2) keep 'other' but rename something like 'otherStateBody' to make it clear what this code applies to. (We could require that an entitySubtype must be used when entityType is 'stateBody' - I think we should do this if we keep the code in as otherwise it doesn't seem to me to have a purpose.)

@kd-ods - any thoughts?

**Comment by kd-ods** [comment]
Just noting here that addressing #522 would impact how validation looks in the schema.

**Comment by kd-ods** [comment]
> Is this a useful code to keep in? It doesn't add any information other than the negative that this entity is not one of the other entitySubtypes for state bodies.

This 'negative' information seems more valuable than no information at all. For example, if there were a lot of entities in a dataset with `entityType` 'arrangement' and `entitySubtype.generalCategory` 'other', at least you'd know that whatever these entities were, the other `generalCategory` codes has been considered and were not applicable. Also, if we want to consider making `entitySubtype` required, then there would need to be an 'other' value (as a catch-all).

(Just today, I was talking with someone who wants to publish data in BODS format. They wanted to know whether they could represent 'projects' in BODS which several entities were involved in. I suggested that they could use an entity with `entityType` 'arrangement'. This is a prime case where 'other' would be useful. And I'd suggest to them that `localTerm` would be 'Project partnership' or similar.)

**Comment by kathryn-ods** [comment]
thanks @kd-ods! In that case we'd broaden out the scope of 'other' to more than just SOEs. Would it make sense to have it limited to SOEs and arrangements (and maybe legal entities) or would we allow a value of 'other' for all entity types? Currently registeredEntity, anonymousEntity, unknownEntity and state do not have any affiliated subtypes.

**Comment by kd-ods** [comment]
'other' would be for all entity types. I can't see any benefit to restricting it to only subtypes of stateBody.

**Comment by kathryn-ods** [comment]
@kd-ods agreed so this will be the validation requirements for the different subtypes. 

entitySubtype | valid entityTypes
-- | --
trust | arrangement, legalEntity
nomination | arrangement
governmentDepartment, stateAgency | stateBody
other | all (no validation needed)

Currently entityType is a required field. We could make entitySubtype a requirement for certain entityTypes - it might make sense to require it for stateBody and arrangement. But that might be a bit too prescriptive.

**Comment by kathryn-ods** [comment]
I've closed 583 as it was getting quite outdated and made a new PR just for the structural changes not the logic #640 

We could validate the subtypes based on the value of the type instead which would remove the need for the _if not null_ clause 

**options**

if stateBody -> then governmentDepartment/stateAgency/other

if arrangement -> then trust/nomination/other

if legalEntity -> then trust/other 

if not stateBody/arrangement/legalEntity -> then other 

**or**

if not null

	if trust -> then arrangement/legalEntity 

	if nomination -> then arrangement 

	if governmentDepartment/stateAgency -> then stateBody
