### ISSUE TITLE
Guidance and schema for representing transliterated and original content

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#52]
There is a use-case for BODS to represent source material in its original form and a transliterated version in another alphabet.

**Comment by timgdavies** [comment]
I've updated title to reflect that there may be both **schema** and **guidance** issues here. We should first identify if there are required schema changes in a future version. 

## Transliteration and original content in schema 

There are a range of free-text fields subject to user-input where this may be relevant:

* (a) Names of persons and entities
* (b) Addresses
* (c) Descriptive fields, including `pepStatusDetails/missingInfoReason`, `unspecifiedPersonDetails/description`, `source/description`, `unspecifiedEntityDetails/description`

In (a), we have the existing `personStatement/names` array has support for transliteration, and #268 is exploring adoption of a similar model for entity statements. 

For (b) and (c) we do not currently have field-level support for transliteration, but an `annotation` could be used to point to a given statement and describe original content that has been transformed through transliteration. 

This is what we currently say in the [Languages and Transliteration guidance](http://standard.openownership.org/en/0.2.0/schema/guidance/languages.html?highlight=transliteration). 

@ScatteredInk Given the above, do you see a need for schema updates to support transliteration better? If so - can you have a first go at sketching out. If not, we can update the title of this issue to reflect the need for expanded guidance only. 

## Guidance on transliteration

Regardless of schema updates, we should improve our transliteration guidance, providing examples if appropriate.

**Comment by kathryn-ods** [comment]
We have improved the guidance on this in 0.4 but I'm not sure whether schema changes need further consideration

**Comment by kd-ods** [comment]
The updated, renamed page ['Representing alternative languages'](https://standard.openownership.org/en/main/standard/modelling/languages.html) is an improvement. I'm closing this. If further improvement or guidance is needed, a new ticket can be opened.
