### ISSUE TITLE
Update JSON pointers in docs to reflect 0.4.0 schema updates

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#521]
**Summary of the bug or issue**
After bringing my dev environment in line with the updated requirements_test.txt, I tried building the docs on the 0.4.0-schema-resdesign branch. I got the following error.

```
Exception occurred:
  File "/home/work/.local/lib/python3.9/site-packages/pygments/styles/__init__.py", line 53, in get_style_by_name
    raise ClassNotFound("Could not find style class %r in style module." % cls)
pygments.util.ClassNotFound: Could not find style class 'OodsStyle' in style module.
The full traceback has been saved in /tmp/sphinx-err-6chqkzst.log, if you want to report the issue to the developers
```
Using 'cat' to view the content of /tmp/sphinx-err-6chqkzst.log gives me nothing.

**Comment by rhiaro** [comment]
I've pushed a _temporary_ fix to that error to the 0.4 branch - it now hits the json pointer errors with the docs builds as before.

A quick look, and the version of Pygments has been upgraded by several, so the API for including custom styles might have changed. Will need to dig in further, but it's only syntax highlighting so we can live without it in the meantime. I'm spinning this specific issue into https://github.com/openownership/data-standard-sphinx-theme/issues/85

**Comment by kd-ods** [comment]
OK. Here's the jsonpointer error:

```
Exception occurred:
  File "/home/work/.local/lib/python3.9/site-packages/jsonpointer.py", line 291, in walk
    raise JsonPointerException("member '%s' not found in %s" % (part, doc))
jsonpointer.JsonPointerException: member 'Agent' not found in OrderedDict [...]
```
We think this will be fixed when, in the docs, the pointers on reference.rst page are updated in line with the schema redesign.

**Comment by kathryn-ods** [comment]
I've edited the JSON pointers on the branch https://github.com/openownership/data-standard/tree/0.4.0-schema-redesign-reference-pointers and have uncovered a new error #546

**Comment by kathryn-ods** [comment]
Cherry picked this change into a new branch to avoid various merge conflicts. See pull request #569
