### ISSUE TITLE
Change to entityType and entitySubtype structure

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#522]
Currently in the schema we we have 
- entityType 
- a separate entitySubtype object which contains entitySubtype.generalCategory and entitySubtype.localTerm

Could type and subtype be grouped into one object? 

Also is localTerm necessary as a field? Under interests we have interest.details which can be used for a local name 'This field may be used to provide the local name given to this kind of interest, or any further semi-structured or unstructured information to clarify the nature of the interest held.' Would it be more consistent to use this terminology here as well?

So maybe something like 

entityType {
    type, 
    subtype, 
    details}

**Comment by kathryn-ods** [comment]
@kd-ods might not be viable for 0.4 but wanted to write this down while I was thinking about it

**Comment by kathryn-ods** [comment]
Thanks @kd-ods sounds good!

**Comment by kathryn-ods** [comment]
@rhiaro @kd-ods - we should probably make a decision on this before adding in the entityType/entitySubtype logic

**Comment by kd-ods** [comment]
I'm still keen to see this implemented. If `entityType.type` isn't too clunky let's go for @kathryn-ods 's origin suggestion where the `entityType` field takes an object with properties: `type`, `subtype` and `details`.

@rhiaro - how does this look to your eye?

**Comment by rhiaro** [comment]
That looks good to me, I think it'll be a lot more straightforward to validate any dependencies between types and subtypes that way

**Comment by kathryn-ods** [comment]
thanks both! I will make a branch and start working on this

**Comment by kathryn-ods** [comment]
I think entityType.type might not be advisable as type is also used in the schema to denote the data types - so either entityType.entityType or entityType.mainType?

**Comment by kd-ods** [comment]
> I think entityType.type might not be advisable as type is also used in the schema to denote the data types

`type` is used in JSON schema as a property, but I don't think that's reason to steer away from using it in our schema, is it? I can't see any indication in the [2020-12 spec](https://json-schema.org/draft/2020-12/json-schema-validation) that it's a reserved term.

**Comment by kathryn-ods** [comment]
Maybe it's fine then! I'll try it and see what happens

**Comment by rhiaro** [comment]
Yeah once it's nested under `properties` it's treated like any other property afaik

**Comment by kathryn-ods** [comment]
Yes you're both correct it does work fine :)

**Comment by kathryn-ods** [comment]
Noting that this feature is complete as of BODS 0.4 see - https://standard.openownership.org/en/0.4.0/standard/index.html
