### ISSUE TITLE
make statementDate a required field 

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#523]
statementDate isn't currently a required field, I think it should be. 

It represents the point in time that a claim has been made about ownership. This is an essential piece of info. 

Currently publicationDetails.publicationDate is required. The date of publication could be some time after the original submission.

**Comment by kd-ods** [comment]
Yes - this has been [proposed here too](https://github.com/openownership/data-standard/discussions/477#discussioncomment-6806457). Good to get this into an issue - thanks!
