### ISSUE TITLE
New Page - Representing record updates

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#525]
New page in documentation as per https://docs.google.com/spreadsheets/d/1gaARj0p7UShhDcHP83RFoRXPSstM8Zc4al5UZRA6AJQ/edit?usp=sharing

**Comment by kd-ods** [comment]
@kathryn-ods - this page is ready for an initial review. As I mentioned... it is quite dry.

(Also - I've not included guidance on post-hoc redaction. I'll do that in the 'Generating statements' page.)

**Comment by kathryn-ods** [comment]
@kd-ods I've added some notes in the doc :)
