### ISSUE TITLE
New Page - Record identifiers

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#526]
New documentation page as per https://docs.google.com/spreadsheets/d/1gaARj0p7UShhDcHP83RFoRXPSstM8Zc4al5UZRA6AJQ/edit?usp=sharing

This page will include advice/normative guidance on constructing record identifiers

**Comment by kathryn-ods** [comment]
I made some notes on this a while back and haven't followed up since - do you think it needs more work still?

**Comment by kd-ods** [comment]
I've just pushed the branch with this on, and asked for your review on the PR, @kathryn-ods :-)
