### ISSUE TITLE
Review schema browser content

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#527]
We will need to review the written content in https://standard.openownership.org/en/latest/schema/schema-browser.html and 

Including updating the reference to the JSON schema

**Comment by kathryn-ods** [comment]
initial thoughts https://docs.google.com/document/d/1JpPV977vYfjR1oA767eaoC65j32mVAv7GDbiIign8V4/edit?usp=sharing

**Comment by kd-ods** [comment]
The doscon widget which provides the navigable schema views is no longer working. Have spun up this issue to note the problem:  #557

**Comment by kd-ods** [comment]
@kathryn-ods - OK if I pick this up tomorrow, if you don't have time? I'll use the text you've prepared. (I want to see how badly the docson widget fails.)

**Comment by kathryn-ods** [comment]
@kd-ods moving this to done
