### ISSUE TITLE
Update attention boxes for 0.4 pages 

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#529]
Several pages include an attention/warning box at the top of the page. This will need updating

'Attention

This is v0.3 of the Beneficial Ownership Data Standard. It includes updates to the data model and codelists as well as additional technical guidance.

Implementers should be aware that future changes are anticipated, before a version 1.0 release. See the [Changelog](https://standard.openownership.org/en/latest/schema/changelog.html) and [About](https://standard.openownership.org/en/latest/about) pages for more information.

MUST and SHOULD are used in the schema to denote required and recommended elements of the Standard, as defined in [RFC2119](https://tools.ietf.org/html/rfc2119).'

**Comment by StephenAbbott** [comment]
@kathryn-ods Should we capture here or on a separate bug ticket that the attention boxes don't appear for any version 0.2 pages? https://standard.openownership.org/en/0.2.0/

**Comment by kathryn-ods** [comment]
@StephenAbbott I am seeing them on 0.2 pages - wonder why you're not getting them.

I am seeing the warnings on 
https://standard.openownership.org/en/0.2.0/schema/concepts.html
https://standard.openownership.org/en/0.2.0/schema/schema-browser.html
https://standard.openownership.org/en/0.2.0/schema/reference.html

'Attention

This is v0.2 of the Beneficial Ownership Data Standard. It includes updates to the data model and additional codelist information. Implementers should be aware that future changes are anticipated, before a version 1.0 release. See the [Changelog](https://standard.openownership.org/en/0.2.0/schema/changelog.html) and [About](https://standard.openownership.org/en/0.2.0/about) pages for more information.

MUST and SHOULD are used in the schema to denote required and recommended elements of the Standard, as defined in [RFC2119](https://tools.ietf.org/html/rfc2119).'

**Comment by StephenAbbott** [comment]
@kathryn-ods Do you see warnings on Homepage / Primer / Example data / About section pages?

https://standard.openownership.org/en/0.2.0/index.html
https://standard.openownership.org/en/0.2.0/primer/index.html
https://standard.openownership.org/en/0.2.0/examples/index.html
https://standard.openownership.org/en/0.2.0/about/index.html

I can also see the warnings on the pages in Data Schema section - but not in other sections or on the homepage.

**Comment by kathryn-ods** [comment]
@StephenAbbott looking at the source files the only pages that include the warning are below, this is the same for the 0.2 and 0.3 docs. I don't think we necessarily need a warning on pages that aren't specifically detailing the schema. We could add it on to other pages if needed though. 

- concepts
- index (data schema)
- reference
- schema-browser
- index (technical guidance)

Currently the warning is being manually added to each page - when we get round to updating these we should also consider whether the warning could be referenced from one source to minimise the need to update each warning individually.

**Comment by kathryn-ods** [comment]
see #544 which saves the warning box in one file and references out to it

**Comment by kathryn-ods** [comment]
@kd-ods yes this can close if we are happy with the current text - I think we should remove the final sentence as it isn't really a warning. 

" This is v0.4 of the Beneficial Ownership Data Standard. It includes updates to the data model and codelists as well as additional technical guidance.
   
   Implementers should be aware that future changes are anticipated, before a version 1.0 release. See the Changelog and About pages for more information.
   
   MUST and SHOULD are used in the schema to denote required and recommended elements of the Standard, as defined in RFC2119."

**Comment by StephenAbbott** [comment]
@kathryn-ods @kd-ods Checking here: do we have two separate warning messages? Was checking https://github.com/openownership/data-standard/pull/544 but can't tell.

The text above suggested by Kathryn is good as a warning for viewers of version 0.4 pages appearing at the top of - for example - the schema browser page as it does for v0.3 https://standard.openownership.org/en/0.3.0/schema/schema-browser.html (happy with suggestion to remove final sentence, @kathryn-ods).

But we'll also need a different warning message for older versions of BODS to say something like "You are not reading the most recent version of this documentation. [0.3.0](https://standard.openownership.org/en/0.3.0/primer/index.html) is the latest version available" as we currently do on pages like [this](https://standard.openownership.org/en/0.1.0/primer/index.html). 

I can only seem to see one file - warningbox.rst - in https://github.com/openownership/data-standard/pull/544. Am I getting that right?

**Comment by kathryn-ods** [comment]
Yes the previous versions have their own warning messages in their respective repos. 

I haven't made the change to make it quicker to edit in those repos (might be worth doing if they're likely to keep changing) 

 I've made #560 to organise those changes.

**Comment by StephenAbbott** [comment]
Ah. Thank you. Got it

**Comment by kathryn-ods** [comment]
Small change to the wording of the warning for 0.4 in #561
