### ISSUE TITLE
Review page - Real world identifiers

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#530]
Review of https://standard.openownership.org/en/latest/schema/guidance/identifiers.html 

- remove information that is not relevant to this section/repeated elsewhere
- edit in line with style guide

**Comment by kathryn-ods** [comment]
Yes agreed there's some bigger picture things to consider here around identifiers. 

> We should consider whether a primary aim with editing a page like this is to bring into the schema (and onto the reference page) as much normative content as possible. If that's a principle we should follow, then we should note it in the handbook too.

I am generally in favour of doing this. On the current page there's a breakdown of the different fields in the identifier object - I think this sort of content should be reserved for the reference page. The style guide does say we should avoid repeating information, we could also add more specific guidance on where types of information should go.

**Comment by kathryn-ods** [comment]
@kd-ods now that the schema descriptions have been reviewed now might be a good time to come back to this. I'm a bit concerned parts of this page are repeating/contradicting what the guidance says.

**Comment by kd-ods** [comment]
@kathryn-ods - Once I started making suggested edits and saw your comments, I realised this page needs a wholesale re-write, putting in some thought to what we usefully want to say beyond what's in the schema.

OK if I take a crack at that Thurs?

**Comment by kathryn-ods** [comment]
@kd-ods ok with me!

**Comment by kd-ods** [comment]
@kathryn-ods - this docs page is ready for you to take a look at now: https://docs.google.com/document/d/1IDMZKXrrPMSwRk5eNTxYyeJeUaCUbahcnTEkbKQkugo/edit?pli=1

(It's not a revolutionary re-write because I still think it's useful to have a page which summarises all the places in the schema where interoperability is supported by allowing inclusion of 3rd party identifiers.)

**Comment by StephenAbbott** [comment]
@kd-ods @kathryn-ods Is there a good place in updated version to link to the reliable identifiers guidance? https://www.openownership.org/en/publications/using-reliable-identifiers-for-corporate-vehicles-in-beneficial-ownership-data/
