### ISSUE TITLE
Move old 'Sources and annotations' page content to 'Schema reference' page

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#537]
**Summary of the bug or issue**

The [information here](https://standard.openownership.org/en/latest/schema/guidance/provenance.html#provenance) would sit better as part of the [Schema reference](https://standard.openownership.org/en/latest/schema/reference.html) page. (There may be normative requirements that would better sit in the schema too.)

**Comment by kathryn-ods** [comment]
Extracting the normative statements from this page 

>  Each statement SHOULD contain information on its source, and whether or not the information it contains has been verified.

In the schema this could be **Each statement SHOULD contain a source object with a valid source.type.** With regards to verification we could have **If data has been verified source.type should include 'verified.'** A separate boolean 'verification' field within source might be better (see #271)

> The source property of each statement MAY be used to provide provenance information.

This potentially contradicts the first statement as we are saying you SHOULD include source information and then that you MAY use this object to do so? 

Currently the source object says 'The source object is used to explain where information in a statement originated from, and to link to supporting information.' I think this is fine as is. 

> The annotations property of each statement MAY be used to provide additional contextual information

The annotations description is 'An annotation provides additional information about ownership or control data being provided. Annotations can be provided in free-text, and can apply to a whole statement, an object or a single field. Additional extended properties can be included on the annotation object to provide structured data where required.' I think that is fine as is.

> In some cases, systems processing BODS data may make changes to clean, enhance or otherwise update the data, such as reconciling company names against identifiers. In this case, details of these changes SHOULD be recorded as annotations

I think this shouldn't be included as a normative statement as there's no way to validate this. You could maybe put something about this under the real-world identifiers page.
