### ISSUE TITLE
Source.asssertedBy description - remove requirement to match entity or person name

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#539]
**Summary of the bug or issue**
The current description for [Source.assertedBy](https://standard.openownership.org/en/latest/schema/reference.html#source) is:

> "Who is making this statement? This may be the name of the person or organisation making a self-declaration (in which case, please make sure the name field matches the organisation or person name field), or the name or description of some other party. If this statement has been verified, this may also include the name of the organisation providing verification."

Alongside a good edit, the whole "please make sure the name field matches the organisation or person name field" can be removed from BODS 0.4 (since use of the declarationSubject field now fullfils the same function).

**Comment by kathryn-ods** [comment]
"If this statement has been verified, this may also include the name of the organisation providing verification." 

So in this case the array would have 2 entries - one for the submitting/declaring person/organisation and one for the verifying organisation? But there wouldn't be a way to know which entry played which role? 

Is there otherwise a hypothetical situation where one statement is being submitted by multiple people/agencies simultaneously? I suppose 2 board members could be filling it out together or similar.

**Comment by kd-ods** [comment]
> Is there otherwise a hypothetical situation where one statement is being submitted by multiple people/agencies simultaneously? I suppose 2 board members could be filling it out together or similar.

Potentially, the information available in a single statement could have been supplied by a company and verified by a registered/licensed agent.

**Comment by StephenAbbott** [comment]
> Potentially, the information available in a single statement could have been supplied by a company and verified by a registered/licensed agent.

This is the case for the UK Register of Overseas Entities, for example. A UK-regulated agent registers with Companies House to get an agent assurance code and then the representative of the overseas entity has to go to the agent to get them to carry out checks on the BO information for the overseas entity before it is submitted to Companies House:

https://www.gov.uk/guidance/register-an-overseas-entity
https://www.openownership.org/en/blog/a-first-quick-look-at-the-verification-mechanism-of-the-new-uk-register-of-overseas-entities/

**Comment by kathryn-ods** [comment]
I think what I am getting at is why have an array for assertedBy rather than 2 separate fields assertedBy and verifiedBy? Because in this current format you wouldn't be able to know who was asserting and who was verifying? Does that matter?

**Comment by kd-ods** [comment]
It's a good question, which touches on the [big issue of how/whether verification should be a facet of BODS data](https://github.com/openownership/data-standard/issues/366). 

I'm not sure it's worth dealing with the `source` object problems this time around.

**Comment by kathryn-ods** [comment]
> I'm not sure it's worth dealing with the source object problems this time around.
Yeah very fair agree we might not wanna go down that rabbit hole right now. 

How is 

"An array of objects representing who is making this statement. This may be the name of the person or organisation making a self-declaration or the name of some other party making a declaration on their behalf. If this statement has been verified, this may also include the name of the organisation providing verification."

**Comment by kd-ods** [comment]
Looks good. Maybe a slight edit:

"...If this statement has been verified, **the array** may also include the name of the organisation providing verification."

**Comment by kathryn-ods** [comment]
agreed - will make that change

**Comment by kathryn-ods** [comment]
change made in #606
