### ISSUE TITLE
PublicListing.hasPublicListing description should be edited to remove normative language

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#540]
**Summary of the bug or issue**

The current description of hasPublicListing is:

> "This value MUST be true if the entity is known to be a publicly listed company."

It would be better to word as: "Whether the the entity is known to be a publicly listed company."

**Comment by kathryn-ods** [comment]
Is there a reason to include 'known to be'? If it is a PLC that information should be readily available?
