### ISSUE TITLE
Resolve jsonref urn error when building docs

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#546]
After doing #521 I am now getting a new error as jsonref doesn't seem to be able to process urns. 

Replicate by trying to build the docs on https://github.com/openownership/data-standard/tree/0.4.0-schema-redesign-reference-pointers

File "/home/work/.local/lib/python3.9/site-packages/jsonref.py", line 132, in callback
    raise self._error(
jsonref.JsonRefError: Error while resolving `urn:components#/$defs/UnspecifiedRecord`: URLError: <urlopen error unknown url type: urn>

**Comment by kathryn-ods** [comment]
@rhiaro made a ticket for the bug I mentioned yday

**Comment by kd-ods** [comment]
Moving to ready and prioritising on the project board.

**Comment by kathryn-ods** [comment]
this has been fixed

**Comment by kd-ods** [comment]
No - it's not been fixed AFAIK. @rhiaro edited/disabled some bits to make sure we could build the docs on main without errors.

**Comment by rhiaro** [comment]
@radix0000 

The work to do here is to dig into the jsonref library and find out what it's actually doing with the `$id` values. If it has a block or allow list for protocols, but isn't actually trying to resolve them, we can either a) make a PR to the library to allow URNs (which are valid in JSON Schema 2020-12) or b) use https URIs.

If it's trying to resolve them to find the contents, the ideal solution would be to update jsonref (or our sphinx extension on top of it) to use the new ref resolution functions in the latest jsonschema library, but that's likely to be a bit more involved.
