### ISSUE TITLE
Removing the agent object

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#548]
In the current draft of 0.4 https://github.com/openownership/data-standard/tree/0.4.0-schema-resdesign the Agent object has been removed. 

In 0.3:

- Agent contains 2 fields - name and uri https://standard.openownership.org/en/latest/schema/reference.html#agent
- Source.assertedBy is an array of Agent objects 
- Annotation.createdBy has the same fields as Agent but doesn't explicitly reference the object in the schema 
- publicationDetails.publisher has the same fields as Agent but doesn't explicitly reference the object in the schema

**Comment by kd-ods** [comment]
I'm all for rationalising this and using the same object for all three fields.

**Comment by kathryn-ods** [comment]
I think in @rhiaro's draft the object has been removed altogether in favour of just having the two named fields rather than referencing out to Agent - are you happy with that approach rather than changing those 2 fields to reference agent?

**Comment by kathryn-ods** [comment]
closing as this has been merged in
