### ISSUE TITLE
Field description for familyName contains an error

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#549]
**Summary of the bug or issue**

The familyName value in the field description (below) should be recorded as 'de Cervantes Saavendra', as 'de' is the prefix.

> A family name is usually shared by members of a family. This attribute also carries prefixes or suffixes which are part of the Family Name, e.g. 'de Boer', 'van de Putte', 'von und zu Orlow'. Multiple family names, such as are commonly found in Hispanic countries, are recorded in the single Family Name field so that, for example, Miguel de Cervantes Saavedra's Family Name would be recorded as 'Cervantes Saavedra.'

Spotted by @miranda-ae.

**Suggested resolution**

Edit the field description

**Comment by kathryn-ods** [comment]
Noted in the field mappings doc #480
