### ISSUE TITLE
Add documentation on representing that an entity has no (qualifying) beneficial owners

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#550]
**Summary of the bug or issue**
We have the [UnspecifiedReason codelist](https://standard.openownership.org/en/0.3.0/schema/reference.html#unspecifiedreason) value 'noBeneficialOwners' and its description 'There are no beneficial owners who need to disclose ownership according to the rules under which this statement is made.' This is the only current documentation hinting at how publishers represent a declaration that an entity has no (qualifying) beneficial owners. 

Publishers need more guidance than this about how to represent this situation.

**Additional context and details**

We also need to bear in mind this ticket being worked on for 0.4: #467 

**Suggested resolution**

I think we should add information to the [Representing beneficial ownership](https://standard.openownership.org/en/main/schema/guidance/repr-beneficial-ownership.html) page.

**Comment by kathryn-ods** [comment]
assigning to @kd-ods as she is editing this page
