### ISSUE TITLE
[BUG] - docson widget  on schema browser page not resolving urns

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#557]
**Summary of the bug or issue**

We are building the main branch docs [here on ReadTheDocs](https://standard.openownership.org/en/main/schema/schema-browser.html). On that page, the reader should see the navigable docson widget, as for [BODS 0.3](https://standard.openownership.org/en/0.3.0/schema/schema-browser.html). As of 16th Feb, it looks like the current version on main of the docson widget is not handling the 2020-12 schema.

**Comment by kd-ods** [comment]
@rhiaro - I think you know about this? But I don't think we'd captured it in an issue.

**Comment by kd-ods** [comment]
Let's resolve #527 before tackling this. We've not even edited the docson pointers yet.

**Comment by kd-ods** [comment]
The new schema is showing up in the docson widgets now that the paths have been edited on the page. (This can be seen on branch 527-docs-schema-browser which will be merged via #581.) The remaining issue seems to be resolution of urn refs, so https://github.com/openownership/data-standard/issues/546 is relevant.

I'm editing the title of this issue to reflect this update.

**Comment by rhiaro** [comment]
See https://github.com/openownership/data-standard/issues/546#issuecomment-2063776776
