### ISSUE TITLE
Conditional validation of address types

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#558]
Valid address types are dependent on the type of statement. Can we validate this in the schema? 

**Person only**
placeOfBirth
residence
service

**Entity only**
registered
business

**Both**
alternative

**Comment by kathryn-ods** [comment]
I'm going to experiment with this and see if I can get the validation working

**Comment by kathryn-ods** [comment]
@kd-ods do you think we should restrict placeOfBirth to only being in the dedicated field? I think it's better to only have one place it can go.

**Comment by kd-ods** [comment]
Yes, I agree - the 'placeOfBirth' code should only be used for that field.
