### ISSUE TITLE
Create a Jupyter notebook that gives pass/fail validation for BODS data

### ISSUE THREAD

**Issue by robredpath** [openownership/data-standard#56]
We need a way to validate BODS data. Initially, this should be a Jupyter notebook. Over time, this will need to be a cmdline tool and ultimately a web app. 

It doesn't need to run entirely automatically at first. It's ok if there are steps which have to be done manually. It just needs to go through the process. 

The initial users for this are @ScatteredInk and @kd-ods

**Comment by robredpath** [comment]
Depends on #62 and folder structure to be finished. Needs some sample data as well. 

Initial work can start before they're done. 

Key outcome is learning for CoVE.

**Comment by Bjwebb** [comment]
What’s done (most of this is in 0.1-dev, but there’s still a pull request outstanding https://github.com/openownership/data-standard/pull/66):
* Functions to validate a BODS statement or package
* Similar functions that iterate over all errors for a BODS statement or package
* The above include detecting the appropriate statement schema from `statementType`
* Checking that statements referenced by a beneficialOwnershipStatement exist previously in a file https://github.com/openownership/data-standard/issues/59
* Running tests of example and test data with py.test on Travis

What’s not done:
* Jupyter notebook - @ScatteredInk will create the notebook/scripts he needs from the functions I’ve written. I’m available to answer any queries about this.
* JSON lines - but, I feel comfortable this should be straightforward to add.
* Useful validation messages - the tests I’ve written only use [ValidationError](https://python-jsonschema.readthedocs.io/en/latest/errors/#jsonschema.exceptions.ValidationError)’s message attribute. Additionally, path information doesn’t specify which statement the error was in. This is probably a priority to fix in the next sprint.

Other notes for doing this in CoVE:
* BODS validation is different from 360/OCDS, but it should just be a matter of replacing jsonschema’s `iter_errors` method with our custom functions.
* Sets of ids are going to be majority of memory usage. If this becomes a problem we may need to write these to disk (using a sqlite db would be a fairly straightforward approach)

**Comment by ScatteredInk** [comment]
I've put together a cleaner version of this now, using @Bjwebb's test functions, in #67 

The use case for the notebook that I see at the moment is primarily around writing and checking new example data, so this notebook is primarily about loading in JSON and then showing the validation errors.

At this point, I'm not sure we need much else - unless you have any thoughts @kd-ods @timgdavies ?

**Comment by timgdavies** [comment]
You can take that two-year silence as no thoughts from us.. ;) 

Closing this issue (though perhaps a ping to @ScatteredInk that if this Notebook is still around and useful, it should be logged in our internal products directory - as I'd forgotten all about it!)
