### ISSUE TITLE
Update the warning messages on older versions of the docs

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#560]
Update the warnings on the versions of the docs <0.4 

Currently only 0.1 has a warning about being an older version. We need to add this onto the 0.2 and 0.3 pages. 

> Note
>You are not reading the most recent version of this documentation. [0.3.0](https://standard.openownership.org/en/0.3.0/schema/schema-browser.html) is the latest version available.

**Comment by kathryn-ods** [comment]
The version warning on 0.1 docs has been automated https://github.com/openownership/data-standard-sphinx-theme/issues/67 

So we need to make the same thing apply to 0.2 and eventually 0.3

**Comment by kathryn-ods** [comment]
See whether a message can be added within the theme

**Comment by kathryn-ods** [comment]
Possibly move this ticket to theme repo

**Comment by kd-ods** [comment]
I've just realised this issue is already in the theme repo: https://github.com/openownership/data-standard-sphinx-theme/issues/81

Closing this, in favour of that one.
