### ISSUE TITLE
Image formatting: Key concepts 

### ISSUE THREAD

**Issue by odscrachel** [openownership/data-standard#592]
On the key concepts page https://standard.openownership.org/en/main/schema/concepts.html the image formatting needs to be adjusted - this is true for a number of the diagrams where the text overhangs the boxes. I'm using Ubuntu/Firefox.
![image](https://github.com/openownership/data-standard/assets/59564404/17da6762-cec0-4cbd-9f7c-1d467730dfac)

**Comment by kathryn-ods** [comment]
Looking at the text file for this diagram the font being used is liberation sans - it should be arial. I think on the site it has defaulted to TNR or something else which might be the reason the formatting is a bit off.

**Comment by kd-ods** [comment]
@odscrachel  - I just want to double-check that these images now look ok to you on [this build](https://standard.openownership.org/en/main/schema/concepts.html)? If so, can you close this and check that it's set to 'done' on the project board. Thanks!

**Comment by odscrachel** [comment]
Yes, all the text now appears in the right place. Only other thing is the dotted line in this image but I wasn't sure if this is expected/wanted  
![image](https://github.com/openownership/data-standard/assets/59564404/e3eb99a7-3912-42e6-be0a-56ad158ee1b8)

**Comment by kd-ods** [comment]
Yes - the line and title indicates that there are interests in the statement... they're just not detailed.
