### ISSUE TITLE
Explore ownership share: intervals and exact values

### ISSUE THREAD

**Issue by anderspeders** [openownership/data-standard#6]
One value which I understand will vary across jurisdictions is the value of ownership share. 

In some countries you can assign an interval "above XX%" while in other it will be an exact value eg. 29%. 

I may have missed this from the report but did not see it discussed. 

One living example where we have **interval disclosures** is the EU Transparency register where companies must disclose their lobbying spending: 
https://lobbyfacts.eu/reports/lobby-costs/all

This gives some interesting results.

**Comment by jpmckinney** [comment]
Perhaps it can be a structured value, with one field containing the value (e.g. `29`) and another containing a modifier (e.g. `greater than`). Not sure if necessary, but we can also add a `unit` field for either `percentage` or `share` if some places report numbers of shares instead of percentages.

**Comment by sebbacon** [comment]
@jpmckinney, my experience is that we would have to support shares and percentages. If we're trying to be comprehensive, we would also want to support "between".

It is not clear to me that we need this to be a structured field.  Sometimes a 5% share could be a controlling stake, sometimes a 75% share. The meaning of control is only loosely coupled with the notion of share ownership.

This relates to [my query about scope](https://github.com/openownership/data-standard/issues/4#issuecomment-272115035). If we are making a general register of asset ownership and influence of which BO is a subset, then a use case *show me all shareholdings greater than 25%* is relevant. If this is only about control, then I think the relevant use case is "*show me all control relationships which are via shares*" (or similar) is more relevant.

**Comment by jpmckinney** [comment]
@sebbacon Agree on all points!

**Comment by timgdavies** [comment]
Our model for shares, with exact, min, max and exclusiveMin and exclusiveMax properties is here: http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#share
