### ISSUE TITLE
Apply theme from Outlandish's recent work to new docs site

### ISSUE THREAD

**Issue by robredpath** [openownership/data-standard#61]
- install bootstrap 4 theme 
- Set up outline navigation
- @kindly to work with Matt from Outlandish and @kd-ods to get additional info required to translate his work into CSS. This needs to be on Weds or Fri next week due to working days. 

'Done' is when the basics are done but the edges aren't finished, and we know how to do everything else.

**Comment by kd-ods** [comment]
Once bootstrap 4 is installed, can @kindly check whether the `[glossary directive](http://www.sphinx-doc.org/en/master/markup/para.html#directive-glossary)` works out-of-the-box? (Ideal behaviour for glossary terms picked out in the text would be for the definition to appear in a [popover](https://drive.google.com/open?id=1kyWt_8Mj5xQi05qAeM17cJqoDfcrbQ7G) on click. I think that's too much to expect on this sprint, but just wanted to make a note of it.)

**Comment by kd-ods** [comment]
Noting the final comment as an [enhancement idea](https://github.com/openownership/data-standard/issues/168) and closing this issue.
