### ISSUE TITLE
Refactor schema into multiple sub-schemas for validation

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#62]
We have recognised that for validation of a fully flat model, we need to:

* Detect the statement type;
* Validate with a statement specific schema;

This suggests we may want to restructure into sub-schemas for each statement type, and then an overall schema that pulls these together.

**Comment by robredpath** [comment]
Met this morning to discuss this work. The validation work depends on this being at least started. Can we confirm:
- When this is likely to start, and when we can meet to discuss details
- That @timgdavies and @ScatteredInk are actually doing this work, and it's not waiting on the developers

**Comment by Bjwebb** [comment]
I think this was done in https://github.com/openownership/data-standard/commit/24ea3ad9a7ecb3db30b7849565065ef57955b797
