### ISSUE TITLE
Add redirects for renamed docs pages

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#665]

**Comment by kathryn-ods** [comment]
initial draft of what will need to be redirected https://docs.google.com/spreadsheets/d/1d-vXBG0brajv8MA9v8AnDDmpWiH3IGWRieaFFW7uOjs/edit?usp=sharing

Will these need to be set up for both /0.4.0/ and /latest/? Currently testing using /main/ 

Should redirects also be set up for older versions? E.g should 0.3.0/standard redirect to 0.3.0/schema? I've set up a general redirect for all broken pages -> homepage for that version (if there's isn't another redirect specified)

**Comment by kathryn-ods** [comment]
Agreed with Kadie to:

- draft the redirects for /en/ before code freeze
- test after code freeze when the /0.4.0/ branch is live to test on 
- add redirects for other languages in when translation is completed

**Comment by kathryn-ods** [comment]
Redirects are drafted - leaving this ticket open until we can do tests

**Comment by kd-ods** [comment]
Just realised this:

> test after code freeze when the /0.4.0/ branch is live to test on

Actually, there will not be a 0.4.0 branch until after the translations are done. That's when we create a release branch off main.

**Comment by kd-ods** [comment]
It would be good to add a 404 redirect for https://standard.openownership.org/en/**main**/... to https://standard.openownership.org/en/**latest**/... if that's possible.

**Comment by kathryn-ods** [comment]
> It would be good to add a 404 redirect for https://standard.openownership.org/en/**main**/... to https://standard.openownership.org/en/**latest**/... if that's possible.

done :)

**Comment by kathryn-ods** [comment]
I have added redirects for all languages now and tested all the redirects for each language. The main -> latest redirect is also now active across languages
