### ISSUE TITLE
Add version warnings for BODS data review tool

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#680]
If there's a delay before the data review tool is able to process 0.4 data we may want to add warnings on the review tool and in the BODS docs?

**Comment by kd-ods** [comment]
Missed our chance on this one. Yes - it would have been a good idea. 

I've [updated](https://github.com/openownership/bods-dev-handbook/blob/main/standard_releases.md#a-new-release) the release docs to add this as an action for next time.
