### ISSUE TITLE
Draft: Conceptual framework, core components and data serialisation

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#7]
[This document](https://docs.google.com/document/d/1-nvxqKLVkWHOpu1bbr3s7E_ZCO416MrjjIMzivYjPgQ/edit#) sets out a proposed conceptual framework for the Beneficial Ownership Data Standard and identifies core components that the standard must represent, along with the relationships between these components. It presents initial an initial approach to data serialisation and exchange. 

This draws upon research into existing standards, the development of standard use-cases and requirements, and examination of existing beneficial ownership and control data. 

The diagram below summarises the **statement centric** conceptual model we are exploring. This is detailed in the document with worked examples. 

![image](https://cloud.githubusercontent.com/assets/342624/22198388/3defb136-e14e-11e6-8da5-82ab84a8529d.png)

**[The document](https://docs.google.com/document/d/1-nvxqKLVkWHOpu1bbr3s7E_ZCO416MrjjIMzivYjPgQ/edit#)** is open for comments until 6th February 2017. 

Modelling issues arising from the paper are also raised in separate issues, tagged '[conceptual model](https://github.com/openownership/data-standard/labels/conceptual%20model)'

**Comment by jpmckinney** [comment]
@timgdavies In terms of process, should we leave comments in the document, or open issues in this repository?

**Comment by timgdavies** [comment]
For quick questions and clarifications - comments on the document are great. 

For anything arising that needs to be substantively followed up, and 'issue tracked' then GitHub issues please.

**Comment by timgdavies** [comment]
In draft modelling we've identified that there can be cases when an individual would think that they are making as single 'beneficial ownership statement', but where our data model requires a number of separate lines of beneficial ownership statement. 

For example:

* X reports that they jointly control Y through a partnership

In our draft conceptual model, this requires two statements:

* A statement indicating X is one party to the partnership P
* A statement indicating that partnership P controls Y

This may either raise:

(a) The need to separate the concept of 'beneficial ownership statements' from 'control', 'ownership' or 'null' statements that are contained in a one-to-many relationship inside the BOS

or 

(b) A need for careful explanation of where the data model diverges from conventional conversation
