### ISSUE TITLE
Thinking about search

### ISSUE THREAD

**Issue by robredpath** [openownership/data-standard#71]
Sphinx's built-in search is fairly basic. We should:

- Have an initial conversation to check assumptions and set scope
- Task someone with doing the research and thinking about the process
- Put together a proposed solution, potentially by starting to implement

**Comment by robredpath** [comment]
@kindly will arrange the initial call with @kd-ods , @timgdavies , probably @ScatteredInk and Tim W (to give OCDS docs perspective) (+ devs)

**Comment by robredpath** [comment]
Internal doc for discussion: https://docs.google.com/document/d/1YtlVqVZFQ4DcpjVJMRINwSRF4l4Mhcsd9S-Q1zpMFMw/edit

**Comment by robredpath** [comment]
The next thing that we need is some more input on user needs - what're the things that people want to do that they can't currently do. 

@timgdavies do you have a sense of this? Or shall I just get you, @kd-ods and @ScatteredInk to keep notes over the next few weeks to generate this?

**Comment by timgdavies** [comment]
We are not planning any specific updates to search at present. However, a separate issue on main website search could consider incorporating the data standard into the search index: https://github.com/openownership/openownership.beta/issues/8
