### ISSUE TITLE
Make sure test data and examples with annotations don't use "/" as a JSON pointer

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#732]
"/" is not a valid JSON pointer - to refer to a whole statement an empty string "" should be used.

We need to check all our examples, test data and diagrams to make sure we have followed this. Previously we have used "/"

**Comment by kd-ods** [comment]
@kathryn-ods - are you covering this in https://github.com/openownership/data-standard/pull/735?

**Comment by kathryn-ods** [comment]
Have just double checked on the 0.4.0 branch and can't see any example, test data or diagrams which use "/" or "" - the examples of annotations all have specific fields as targets.

I think I have mainly seen "/" used in mappings.
