### ISSUE TITLE
[BUG] - Example data not yet usable with the BODS visualiser

### ISSUE THREAD

**Issue by oxyuranus-scutellatus** [openownership/data-standard#734]
**Summary of the bug or issue**
- data-standard/examples/indirect-ownership.json cannot be visualized in https://www.openownership.org/en/publications/beneficial-ownership-visualisation-system/bods-data-visualiser/

**Additional context and details**
- The reason seems to be, that at least this example is not conforming to the BODS JSON Schema 0.4
- At least data-standard/examples/indirect-ownership.json does not validate in https://datareview.openownership.org/
`statementType is missing but required. Check that the field is included and correctly spelled.`

**Comment by StephenAbbott** [comment]
Hi @oxyuranus-scutellatus,

Thanks for raising this issue. We are just in the final stages of updating the BODS visualisation library to handle version 0.4 data.

You can see the ongoing work over in https://github.com/openownership/visualisation-tool

We've conducted two sprints of work in recent months and are just coming to the end of sprint 1. Here are the project boards for [sprint 1](https://github.com/orgs/openownership/projects/11/views/1
) and [sprint 2](https://github.com/orgs/openownership/projects/12/views/1).

I hope that we will be in a position to release an updated version of the visualisation library which will handle version 0.4 data by early December 2024.

I'd love to know more about how you are using the visualisation library.

If you go to https://www.openownership.org/en/about/team/stephen-abbott-pugh, you can find my email address and reach out. This would also allow me to immediately update you as soon as the latest changes are released.

**Comment by StephenAbbott** [comment]
@oxyuranus-scutellatus We are also in the process of updating the BODS data review tool and will be releasing those changes very soon. 

Here is the project board for that work: https://github.com/orgs/openownership/projects/10

New releases for both https://github.com/openownership/cove-bods/ and https://github.com/openownership/lib-cove-bods to add new tests and handle BODS version 0.4 data will be published very soon, likely in early December 2024.

**Comment by oxyuranus-scutellatus** [comment]
@StephenAbbott Thanks for your fast reply.
We had just an internal discussion about modelling indirect relationships. I remembered the Github project and thought, `indirect-ownership.json` could be a good sample to unterstand it better, first tried with the Visualization Tool, then with datareview (and I was quite confused).

**Comment by StephenAbbott** [comment]
@oxyuranus-scutellatus I've just run https://github.com/openownership/data-standard/blob/0.4.0/examples/indirect-ownership.json through the internal demo version of BODS visualisation tool which is running the soon-to-be-released code and here is the resulting image:

![Image](https://github.com/user-attachments/assets/7882c0ce-bd87-4e8a-9494-c379b92c1ca1)
