### ISSUE TITLE
Show message to users when accessing an old version of the documentation

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#76]
I assume we'll have a message like the one on [OCDS docs](http://standard.open-contracting.org/1.0/en/schema/conformance_and_extensions/) when people get to legacy pages?

**Comment by Bjwebb** [comment]
This isn't going to happen automatically, so we'll need to put some thought into how we do this (particularly since the particular mechanism used for the OCDS docs isn't available on ReadTheDocs.

**Comment by timgdavies** [comment]
As part of our next release of the standard we should consider moving to deployment on OpenOwnership servers, along the same model used for OCDS. 

This would allow the same mechanism to be used.

**Comment by odscjames** [comment]
I don't think this is enough of a reason to undertake the big work of moving to our own servers (maybe there are other reasons to do this of course, but not this in itself).

I previously handled this manually.

Every release is a branch in git, not a tag. This allows non-standard changing things to be added to a standard release after that release is made, such as - a banner saying this is old.

If you look at https://github.com/openownership/data-standard/commits/v0-0-3 it has 2 commits that master does not have - the first to solve a technical issue and the second to add a banner saying it's old.

We can do this for 0.1 now (which is missing it) and 0.2, when the time comes.

**Comment by jpmckinney** [comment]
Related: https://github.com/openownership/data-standard-sphinx-theme/issues/67

**Comment by kd-ods** [comment]
Closing this so that we track this work on one place. On: https://github.com/openownership/data-standard-sphinx-theme/issues/67.
