### ISSUE TITLE
SVG issue: fonts can't be embedded in SVGs

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#77]
It looks like we'll have to use a web-safe font-family like Arial for all the SVGs.

See https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts

Or maybe there's a way processing all the Inkscape-generated SVGs and adding font style info from a locally hosted font-file?

**Comment by Bjwebb** [comment]
Converting into PNGs for display would be one way of dealing wtih this https://github.com/openownership/data-standard/issues/78#issuecomment-386283861

**Comment by kd-ods** [comment]
Agreed- that would resolve this issue.

**Comment by kd-ods** [comment]
@timgdavies Just remembered that we've got this problem with SVG fonts. It means that images in the docs aren't going to look that pretty on many browsers. There's an ultimate fix (#78) which involves converting SVGs to pngs during the build process (which deals also with a textflow and localisation issue), and I guess there's a theme-level fix where we install/link to the requisite fonts. 

Shall we leave this to post-Tbilisi?

**Comment by timgdavies** [comment]
I think we can leave this till post-Tbilisi but attack fairly soon after as docs might get circulated more widely then.

**Comment by kd-ods** [comment]
Cool. Assigning to @odscjames and we'll pick it up in a couple of weeks.

**Comment by timgdavies** [comment]
Closing as I believe all SVG issues have been resolved, but tagging @siwhitehouse in case there is something here that should still be tracked.
