### ISSUE TITLE
SVG text box and localization issue

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#78]
For localization and 'automatic' translation of SVGs we ideally would add text to diagrams and images in such a way that longer strings could be substituted in gracefully, without wrecking the image. 

In practice, this would require placing the English text string in a substantially larger text area (which didn't interfere with any other graphical elements). However, there is not yet any standard way of encoding such a text area in SVG. See ['What about flowed text?'](http://wiki.inkscape.org/wiki/index.php/Frequently_asked_questions#What_about_flowed_text) from the Inkscape documentation.

Here's the [W3C SVG 1.2 (working draft)](https://www.w3.org/TR/SVG12/).

**Comment by Bjwebb** [comment]
One option to explore here would be working with whatever inkscape supports (as I've checked we can translate inkscape's flowed text). Then, for display on the website, we'd need to render as PNG. We should be able to automate this by running inkscape as part of the build process.

**Comment by kd-ods** [comment]
OK - that's a reasonable solution. For the moment, since SVG with flowed text doesn't render reliably across browsers, and I've placed SVGs directly into pages, I'm not using flowed text elements.

This issue will become pressing when we start translating the docs.

**Comment by Bjwebb** [comment]
Since we're not using flowed text (unless I've missed it), this isn't currently an issue for the translation.

**Comment by kd-ods** [comment]
I guess the current issue for translation, @Bjwebb, is that the length of SVG text elements might not accommodate translated strings that are longer than source strings.

**Comment by Bjwebb** [comment]
I think that we can mostly tweak the source SVGs so that translations fit - I've written a bit more in https://github.com/openownership/data-standard/pull/239

**Comment by siwhitehouse** [comment]
I've started work on this now that we have the complete Russian translation for the diagrams. I've asked for clarification of the translation for one string as "shares owned by" has been translated as "доли в собственности / акций" which is wrecking multiple images. I'm hoping to agree a shorter alternative to this during the time I am editing the other images.

In #239 @Bjwebb said

> I've looked through all the SVGs, and I think this is true of all of the text, except for one example. In [data-schema-model-1.svg](https://github.com/openownership/data-standard/blob/237-translate-update/docs/_assets/data-schema-model-1.svg), a longer string for "Interest" really won't fit in the box. We currently have "Доля участия" which is twice as long. We could fix this by making the 2 boxes taller, but I think that might be too much whitespace on the English SVG.

Is there a way to make the box wider and have the (vertical) text wrap around on two lines?

**Comment by Bjwebb** [comment]
> Is there a way to make the box wider and have the (vertical) text wrap around on two lines?

This is problematic because browsers don't consistently support text wrapping, i.e. flowed text. We would need a process to convert the SVGs to a supported file, which we've not yet looked into.

A hacky solution would be to place a second empty text box, and then translate the empty string as the second half of the russian translation.

**Comment by timgdavies** [comment]
Closing as I believe all SVG issues have been resolved, but tagging @siwhitehouse in case there is something here that should still be tracked.

**Comment by kd-ods** [comment]
Reopening since I think we're still using clunky workarounds to deal with problems around the adoption of developments in the SVG standard. That right, @siwhitehouse?

I see that Inkscape is gearing up for a 1.0 release which has improvements about [browser compatible flowed text](https://wiki.inkscape.org/wiki/index.php?title=Release_notes/1.0#Browser-compatible_flowed_text).

(To be clear, what we're looking for here is a way of creating SVG images with browser-compatible flowed-text elements. Those flowed-text elements contain the diagram's primary English language strings PLUS substantial 'reserved space' into which translated version of the strings can expand.)

**Comment by kd-ods** [comment]
I'm going to close this issue, but not because it's resolved. I'll refer to this thread from an issue on the [BODS Development Handbook](https://github.com/openownership/bods-dev-handbook/issues/35) and we can work on it from there.
