### ISSUE TITLE
Modelling issues: Artificial legal entities

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#8]
> An issues related to the [draft conceptual model](https://github.com/openownership/data-standard/issues/7)

Our draft conceptual model separates out **entity statements** and **person statements.** 

Entities can be the subject of ownership or control by an interested party (either another entity or a person), but persons cannot be the subject of ownership or control. In other words, persons can only appear at the end of a beneficial ownership chain - not in the middle. 

However, there are cases where:

* A group of people jointly constitute the interested party in an entity, distinct from cases where a group of people hold independent interests in the same entity;

* A person is acting as the nominee for another person, and so, in effect, exists in the middle of a beneficial ownership chain;

In these cases, our approach would be to model an artificial legal entity using an **entity statement**. Entities could have a range of types, including:

* Incorporated body

* Unincorporated association

* Controlled person

**Worked examples and issues**

In the jointly constituted interested party case, the data might looks something like the below, with four beneficial ownership statements, and the link between the people and the ultimately controlled entity (ES1) accessible through the intermediate artificial legal entity ES2. 

**Beneficial ownership statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Interested Party</td>
    <td>Entity</td>
    <td>Interest type</td>
    <td>Ownership percentage</td>
  </tr>
  <tr>
    <td>BOS1</td>
    <td>ES2</td>
    <td>ES1</td>
    <td>Shares</td>
    <td>100</td>
  </tr>
  <tr>
    <td>BOS2</td>
    <td>PS1</td>
    <td>ES2</td>
    <td>Member</td>
    <td></td>
  </tr>
  <tr>
    <td>BOS3</td>
    <td>PS2</td>
    <td>ES2</td>
    <td>Member</td>
    <td></td>
  </tr>
  <tr>
    <td>BOS4</td>
    <td>PS3</td>
    <td>ES2</td>
    <td>Member</td>
    <td></td>
  </tr>
</table>

**Entity statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Type</td>
    <td>Name</td>
    <td>Company number</td>
  </tr>
  <tr>
    <td>ES1</td>
    <td>Incorporated body</td>
    <td>AnyCorp Ltd</td>
    <td>12345678</td>
  </tr>
  <tr>
    <td>ES2</td>
    <td>Unincorporated association</td>
    <td>ABC Association</td>
    <td></td>
  </tr>
</table>

**Person statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Name</td>
    <td>Date of Birth</td>
  </tr>
  <tr>
    <td>PS1</td>
    <td>Mrs A</td>
    <td>April 1970</td>
  </tr>
  <tr>
    <td>PS2</td>
    <td>Mr B</td>
    <td>Jan 1982</td>
  </tr>
  <tr>
    <td>PS3</td>
    <td>Ms C</td>
    <td>10th April 1970</td>
  </tr>
</table>

In the nominee case, where, for example, ‘Mr Laws’ is acting for ‘Ms Owner’ this could be modelled through an intermediate artificial legal entity (E2) which has two beneficial ownership statements, one linking the entity to the person who controls it, and other linking to the ‘role holder’ (e.g. the person who is the nominee). 

**Beneficial ownership statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Interested Party</td>
    <td>Entity</td>
    <td>Interest type</td>
    <td>Ownership percentage</td>
  </tr>
  <tr>
    <td>BOS1</td>
    <td>ES2</td>
    <td>ES1</td>
    <td>Shares</td>
    <td>100</td>
  </tr>
  <tr>
    <td>BOS2</td>
    <td>PS1</td>
    <td>ES2</td>
    <td>Has nominee</td>
    <td></td>
  </tr>
  <tr>
    <td>BOS3</td>
    <td>PS2</td>
    <td>ES2</td>
    <td>Role holder</td>
    <td></td>
  </tr>
</table>

**Entity statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Type</td>
    <td>Name</td>
    <td>Company number</td>
  </tr>
  <tr>
    <td>ES1</td>
    <td>Incorporated body</td>
    <td>AnyCorp Ltd</td>
    <td>12345678</td>
  </tr>
  <tr>
    <td>ES2</td>
    <td>Legal Nominee</td>
    <td></td>
    <td></td>
  </tr>
</table>

**Person statements**

<table>
  <tr>
    <td>Statement ID</td>
    <td>Name</td>
    <td>Date of Birth</td>
  </tr>
  <tr>
    <td>PS1</td>
    <td>Ms Owner</td>
    <td></td>
  </tr>
  <tr>
    <td>PS2</td>
    <td>Mr Laws</td>
    <td></td>
  </tr>
</table>

**Comment by sebbacon** [comment]
Q: What is the benefit of modelling a natural person as a separate entity, rather than a `is_natural_person` flag on the Entity model?

**Comment by jpmckinney** [comment]
@sebbacon I think Tim is talking at the 'conceptual' level. Whether the two different classes are implemented as a single class with a flag is a concern of the implementation level.

**Comment by timgdavies** [comment]
There is worked example of an [arrangement in the current docs](http://beneficial-ownership-data-standard.readthedocs.io/en/master/overview.html)
