### ISSUE TITLE
jsonschema directive not building tables from JSON pointer notation?

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#81]
The jsonschema directive is building tables for person-statement.json, beneficial-ownership-statement.json and so on, but not for the objects defined in components.json. Using this:

```eval_rst
.. jsonschema:: ../schema/components.json#/definitions/StatementReference
```

...generates this error:

`/vagrant/data-standard/docs/schema.md:1: WARNING: JSON Schema file not readable: ../schema/components.json#/definitions/StatementReference`

See this markdown file for instances. https://github.com/openownership/data-standard/blob/60-refactor-docs/docs/schema.md

**Comment by Bjwebb** [comment]
You need to use `:pointer:`:

```
.. jsonschema:: ../schema/components.json
   :pointer: /definitions/StatementReference
```

(I've not checked this example, so their might be typos, but you can see this in use for OCDS at https://github.com/open-contracting/standard/blob/1.1-dev/standard/docs/en/schema/reference.md#parties)

**Comment by kd-ods** [comment]
Cheers, Bjwebb! (Is this documented anywhere except its use for OCDS?)

**Comment by Bjwebb** [comment]
Looks like it isn't, no.
