### ISSUE TITLE
jsonschema directive needs to handle child objects elegantly

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#82]
At the moment, the interestedParty property defined in the [beneficial-ownership-statement.json](https://github.com/openownership/data-standard/blob/60-refactor-docs/schema/beneficial-ownership-statement.json) schema, as so:
```
"interestedParty": {
      "title":"Interested party",
      "description":"The interested party has some level of ownership or control over the entity referenced in this beneficial ownership statement.",
      "type": "object",
      "properties": {
        "entity": {
              "$ref": "components.json#/definitions/StatementReference"
            },
        "person": {
              "$ref": "components.json#/definitions/StatementReference"
            },
        "unspecified": {
              "$ref": "components.json#/definitions/Unspecified"
            }
          },
      "oneOf": [
        { "required": [ "entity" ] },
        { "required": [ "person" ] },
        { "required": [ "unspecified" ]}
      ]
    }
```
Is rendered in a reference table as follows (though its properties can be collapsed/hidden):

![image](https://user-images.githubusercontent.com/35495305/40129917-791c4636-592d-11e8-8b4c-65f042051ec2.png)

I'd like to see something more like this, maybe (suggestions welcome):

![image](https://user-images.githubusercontent.com/35495305/40132923-119c808a-5936-11e8-9f88-6c8161a0dc71.png)

Then the interestedParty object could be rendered in its own child table; a bit like some functionality described here in the [sphinxcontrib docs](http://sphinxcontrib-opendataservices.readthedocs.io/en/latest/jsonschema/).

I suggest this because from a docs user and reference point of view, it doesn't matter whether an object is:

* defined elsewhere and referenced, or
* is defined within the same schema

Both should be rendered in the same way for reference.

(Assigning to Jack in the first instance so that he can check this makes sense.)

**Comment by timgdavies** [comment]
I agree this is a useful potential change to make to the directives. Tagging @bjwebb who might have some thoughts on how easy or not this change would be (i.e not only allowing us to cross-reference a table when there is a $ref, but also just when we collapse certain things)

For the time being I've updated the schema so that we can display it like the above imagines (by moving interestedParty into a $ref, but we should review the whole structure of the schema in terms of refs etc. before beta-3

**Comment by Bjwebb** [comment]
> Tagging @Bjwebb who might have some thoughts on how easy or not this change would be (i.e not only allowing us to cross-reference a table when there is a $ref, but also just when we collapse certain things)

This should be fairly straightforward to implement.

**Comment by kd-ods** [comment]
Noting that the original issue (inconsistencies in docs presentation of child objects) was fixed by Tim moving the interestedParty property into a 'definitions' section in the [ownership-or-control-statement.json](https://github.com/openownership/data-standard/blob/0.2-dev/schema/ownership-or-control-statement.json) schema and using a $ref.

But reviewing $refs in the schema and where the source->compile process now leaves us would be a good idea.
