### ISSUE TITLE
Dead links on Readthedocs auto-build of 60-refactor-docs branch

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#83]
In-page markdown links aren't being parsed and converted properly from .md to .html (e.g. link to provenance.md isn't being changed to provenance.html). Try the 'Governance' link here:

https://beneficial-ownership-data-standard.readthedocs.io/en/60-refactor-docs/about.html 

The master branch build is fine. See 'specification pages' link here:

http://beneficial-ownership-data-standard.readthedocs.io/en/master/index.html

--------
Edited to change the top URL. In the first one I posted some of the broken links were attributable to a different, and easily resolved, problem.

**Comment by ScatteredInk** [comment]
Looks like you might be running into this cross-referencing issue? https://github.com/rtfd/recommonmark/issues/8

There is a proposed solution in that thread - although the thread itself is quite old.

**Comment by kd-ods** [comment]
I'm not sure that's the problem, since:

- on my local build the links work just fine (which I should have mentioned before!)
- all the markdown files are in the same directory
- equivalent markdown links are building for the master branch

**Comment by odscjames** [comment]
I can replicate this on local by using https://raw.githubusercontent.com/openownership/data-standard/60-refactor-docs/requirements.txt - so the differences in versions are probably the key here. I'm trying to sort out versions ....

**Comment by odscjames** [comment]
So, if I upgrade Sphinx to version 1.7 and upgrade recommonmarks it fixes the links.

But unfortunately, it breaks "markdown" in "highlights" - see data.html

I need to put back sphinx-contrib-opendataservices and try again - that might be the solution - but we must pack up here now so I'll have to come back to this.

**Comment by odscjames** [comment]
Merged in an upgrade of Sphinx.

It fixes most links.

Some are still broken.

>  on this page https://beneficial-ownership-data-standard.readthedocs.io/en/60-refactor-docs-test/whatdoesbodscover.html the 'details' links are still linking to .md

**Comment by kd-ods** [comment]
Working in the v0.1 docs: http://standard.openownership.org/en/v0-1/primer/whatdoesbodscover.html

Closing.
