### ISSUE TITLE
Privacy notice in redesigned docs

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#85]
We now have a [privacy notice](http://beneficial-ownership-data-standard.readthedocs.io/en/master/privacy-notice.html) in the master branch of the docs from #84 .

We'll also need to have this in our re-designed documentation. Assigning to @kd-ods in the first instance to think about design aspects.

**Comment by kd-ods** [comment]
My preference to to link to the [privacy notice](http://standard.openownership.org/en/v0-1/privacy-notice.html) from some kind of new 'Footer area' in the left-hand navigation column.

@odscjames what are our options theme-wise?

**Comment by odscjames** [comment]
It should be possible to do something - I can have a look?

**Comment by kd-ods** [comment]
I'm going to add the Privacy Notice to the About menu for this 0.2 release.
