### ISSUE TITLE
Alt text markdown for images appearing incorrectly in Read the Docs

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#87]
For example this md:

`![Person A owns 100% of Company 1](_assets/Diag1-simpleOwn.svg)`

...is rendered correctly [here on GitHub](https://github.com/openownership/data-standard/blob/60-refactor-docs/docs/whatisbo.md), with 'Person A owns 100% of Company 1' being the alt text for the html image.

[On Read The Docs](https://beneficial-ownership-data-standard.readthedocs.io/en/60-refactor-docs/whatisbo.html), the phrase is appearing beneath the image.

**Comment by Bjwebb** [comment]
This will be difficult to fix, as its a property of the recommonmark library we use.

**Comment by odscjames** [comment]
@timgdavies suggested converting some pages to RST - I've done this on https://github.com/openownership/data-standard/pull/100

**Comment by odscjames** [comment]
I've done this for primer section only - have to check rest, if people are happy.

**Comment by timgdavies** [comment]
This was looking good. Would be great to update any other places we are using images.

I will work on updates for the schema reference page though - as that will need more manual work to convert to rst I think.

**Comment by kd-ods** [comment]
This particular issue is resolved, but the full move to RST is incomplete. See #169.
