### ISSUE TITLE
Alternative structure for ownership

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#91]
At the moment we represent shares using the following fields

Field | Type | Title | Description 
-- | -- | -- | -- 
exact | number |  Exact share | The exact share of this interest held (where available).
maximum | number |  Maximum share | The upper bound of the share of this interest known to be held.
minimum | number |  Minimum share | The lower bound of the share of this interest known to be held.
exclusiveMinimum | boolean |  Exclusive minimum | If exclusiveMinimum is true, then the share is at least greater than the minimum value given. E.g. if minimum is 25, the share is at least 25.1, and not simply 25.
exclusiveMaximum | boolean |  Exclusive maximum | If exclusiveMaximum is true, then the share is at least less than the maximum value given. E.g. if maximum is 50, the share is less than 49.999, and not simply 50.

However, this means that anyone looking for a share in a heterogenous dataset has look in multiple places. In testing creating and reading data, this felt like an overhead.

An alternative model would be to have:

Field | Description 
-- | -- 
value | A value or range of shares owned. Shares should be expressed using - as the separator.
type | [ exact, range, exclusiveMin, exclusiveMax, exclusiveMinMax  ]

Such that share would be expressed as:

share/value | share/type
-- | --
25 | exact 
25-50 | exclusiveMax
25-49.9 | range
50-75 | exclusiveMinMax

This gives us more economy of presentation. It means consuming applications may need to split ranges to store them, and may wish to apply their own logic when doing that with exclusiveMin / exclusiveMax ranges. 

@ScatteredInk Would welcome your thoughts on this.

We can also check for existing standardisation to draw on.

**Comment by ScatteredInk** [comment]
I agree that the current format is not intuitive when creating data. I'm in favour of this change and think the structure looks good.

I was worried that this would make inputting data in flat templates error-prone but I have done some quick scoping work on validating in a sheet and think that this looks fine: https://docs.google.com/spreadsheets/d/1t5Pdr6NJ4aDmAvSPHTR9F5AnLB0zRkSJAobaS9CX0Cc/edit#gid=0

The only question that I'm not sure of is whether there are implications for flatten-tool in having `exact` represented as a number and the other types of share/value represented as strings.

**Comment by Bjwebb** [comment]
> The only question that I'm not sure of is whether there are implications for flatten-tool in having `exact` represented as a number and the other types of share/value represented as strings.

I think this depends what the schema looks like. I'm assuming you will use `anyOf`? In that case flatten-tool will ignore that block, and rely on the spreadsheet for information about types. I think it will do what you want for xlsx - treat Excel strings as strings and Excel number as numbers. But, for CSV it will be all strings.

See also @kindly's comment on flatten-tool anyOf support https://github.com/OpenDataServices/flatten-tool/issues/182#issuecomment-348183288

**Comment by timgdavies** [comment]
I've been reflecting on this more, and considering that:

* (a) exclusiveMinimum and exclusiveMaximum are 'advanced options' (particularly if we set `exclusiveMinimum` to default to `false` and `exclusiveMaximum` to default to `true`);
* (b) for most input interfaces, there is a choice to make between collecting exact or ranges, and we should document that people need to make that choice;
* (c) the potential validation challenges (though they are navigable) with ranges (e.g. more work to check that the range is meaningful  and not '34-22' etc.) 

I'm leaning back towards sticking with the current model, or at least not changing it yet.

**Comment by timgdavies** [comment]
We did not adopt the alternative model, and we have not experienced problems with the adopted model, so closing.
