### ISSUE TITLE
Change BO statement terminology to "Ownership or control statement"

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#99]
Or should this be "Ownership and control statement"

Update across schema and docs.

**Comment by timgdavies** [comment]
I've staged a pull request (#101) that makes this change based on 'Ownership Or Control Statement' (as or is logically inclusive of and, whereas and is logically exclusive of or). 

We will still need to make updates to:

* Diagrams where the words beneficial ownership statement occur
* Other resources managed outside of the documentation

This will also need more detailed justification in the project change log.

**Comment by kd-ods** [comment]
Suggested text for change log:

### CHANGED

* beneficialOwnershipStatement has been renamed ownershipOrControlStatement . This reflects the fact that the relationship between the subject and an interestedParty of such a statement may not be one of beneficial ownership (but may be a link in a beneficial ownership chain).

**Comment by kd-ods** [comment]
As suggested by Jits, we should actually refer to **'ownership-or-control statements'** (with hyphens) in documentation and descriptions since this better reflects the fact that ownership and control are both included in this one type of statement.

(This avoids the confusion that can occur, for example, when we write "...described in an ownership or control statement". This *could* be interpreted as referring to 2 different kinds of statements.)

Note that we can still refer, eg, to 'ownership or control interests' or 'ownership or control relationships'.

Here are the places in the schema that we need to update:

- Entity statement description ([line 6](https://github.com/openownership/data-standard/blob/schema-beta-2/schema/entity-statement.json))
"A statement identifying and describing the entity that is the subject of the ownership or control described in an **ownership or control statement**."

- Ownership-or control-statement: title and description ([lines 5 & 6](https://github.com/openownership/data-standard/blob/schema-beta-2/schema/ownership-or-control-statement.json))

- Interested party description ([lines 75](https://github.com/openownership/data-standard/blob/schema-beta-2/schema/ownership-or-control-statement.json))

I'll have to correct this systematically in the docs.

**Comment by kd-ods** [comment]
I've made a pull request (#133) which fixes these 'ownership-or-control statement' references in the docs (amongst other things).

@ScatteredInk I can make the above-listed schema file edits too, but wanted to check that's OK with you first (since (a) I've not worked on the schema files before and consider them your domain :-) and (b) there might be other edits that you want to make to the schema at the same time).

**Comment by kd-ods** [comment]
Was changed for 0.1 release.
